{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/my/safe/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['my/safe/index'], function (main) {

        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="finish">
    <div class="container finish-bg-color">
        {%include file='../../../views/common/nav.phtml' current="4"%}
        <div class="finish-main">
            <div class="finish-main-title">安全中心</div>
            <div class="finish-main-grade">
                <span class="finish-grade-left">您的账号安全等级：</span>
                <div class="finish-main-grade-box">
                    <div class="finish-main-grade-box-internal" style="width: {%$userinfo.securedegree.score%}%;"></div>
                </div>
                <span class="fen">{%$userinfo.securedegree.score%}分</span>
                <a class="finish-grade-refresh">重新测试</a>
            </div>
            <div class="infor-data">
                <div class="infor-data-title">个人资料</div>
                <div class="infor-data-box">
                    <div class="infor-data-box-phone">手机号码</div>
                    <div class="infor-data-box-text">手机号是您在兴教贷重要的身份凭证</div>
                    {%if $phone == 2%}
                    <div class="infor-data-box-status cha">未认证</div>
                    <div class="infor-data-box-testing">
                        <div class="testing-content"></div>
                        <a href={%$phoneurl%} class="testing-link" id="phone">验证</a>
                    </div>
                    {%else%}
                    <div class="infor-data-box-status gou">已认证</div>
                    <div class="infor-data-box-testing">
                        <div class="testing-content">{%$phonenum%}</div>
                        <a href={%$phoneurl%} class="testing-link" id="phone2nd">修改</a>
                    </div>
                    {%/if%}

                </div>
                <div class="infor-data-box twoheight">
                    <div class="infor-data-box-phone">证件信息</div>
                    <div class="infor-data-box-text">保障账户安全，只有完成实名认证才能
                        投资、借款和基金交易</div>
                    {%if $certinfo == 2%}
                    <div class="infor-data-box-status cha">未认证</div>
                    <div class="infor-data-box-testing">
                        <div class="testing-content"></div>
                        <a href={%$certinfourl%} class="testing-link" id="papers">验证</a>
                    </div>
                    {%else%}
                    <div class="infor-data-box-status gou">已认证</div>
                    <div class="infor-data-box-testing">
                        <div class="testing-content">{%$realname%}{%$certinfonum%}</div>
                        <a href={%$certinfourl%} class="testing-link" id="papers2nd"></a>
                    </div>
                    {%/if%}

                </div>
                <div class="infor-data-box">
                    <div class="infor-data-box-phone">第三方支付</div>
                    <div class="infor-data-box-text">保障资金安全和正常投入</div>
                    {%if $thirdpay == 2%}
                    <div class="infor-data-box-status cha">未开通</div>
                    <div class="infor-data-box-testing">
                        <div class="testing-content"></div>
                        <a href={%$thirdpayurl%} class="testing-link" id="thirdpay2nd">开通</a>
                    </div>
                    {%else%}
                    <div class="infor-data-box-status gou">已开通</div>
                    <div class="infor-data-box-testing">
                        <div class="testing-content">{%$huifuid%}</div>
                        <a href={%$thirdpayurl%} target="_blank" class="testing-link" id="thirdpay2nd">查看</a>
                    </div>
                    {%/if%}

                </div>
                <div class="infor-data-box border-btm">
                    <div class="infor-data-box-phone">电子邮箱</div>
                    <div class="infor-data-box-text">获取最新的投资资讯和账户信息变化通知</div>
                    {%if $email ==2%}
                    <div class="infor-data-box-status cha">未绑定</div>
                    <div class="infor-data-box-testing">
                        <div class="testing-content"></div>
                        <a href={%$emailurl%} class="testing-link" id="email">绑定</a>
                    </div>
                    {%else%}
                    <div class="infor-data-box-status gou">已绑定</div>
                    <div class="infor-data-box-testing">
                        <div class="testing-content">{%$emailnum%}</div>
                        <a href={%$emailurl%} class="testing-link" id="email2nd">修改</a>
                    </div>
                    {%/if%}

                </div>
            </div>
            <div class="infor-data">
                <div class="infor-data-title">账户信息</div>
                <div class="infor-data-box border-btm">
                    <div class="infor-data-box-phone">登录密码</div>
                    <div class="infor-data-box-text">上次登录时间：2014-12-12 12：12：12</div>
                    <div class="infor-data-box-status gou">已设置</div>
                    <div class="infor-data-box-testing">
                        <a href={%$chpwdurl%} class="testing-link" id="pwd">修改</a>
                    </div>
                </div>
            </div>
            {%if $bindthirdlogin != 2%}
            <div class="infor-data">
                <div class="infor-data-title">第三方绑定</div>
                <div class="infor-data-box border-btm twoheight">
                    <div class="infor-data-box-phone">账号绑定</div>
                    <div class="infor-data-box-text">选择使用第三方账户登陆可与平台账号
                        绑定，方便登陆</div>
                    <div class="infor-data-box-status gou">已设置</div>
                    <div class="infor-data-box-testing">
                        {%if $thirdPlatform%}
                        <div class="testing-content testing-content-icon {%$thirdPlatform%}-pic">{%$thirdNickName%}</div>
                        {%/if%}
                        <a href={%$thirdloginurl%} class="testing-link" id="bindthird">解绑</a>
                    </div>
                </div>
            </div>
            {%/if%}
        </div>
    </div>
</div>

{%/block%}
