 {%extends file="../../../views/common/m/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/m/account/index.css" />
{%/block%} 

{%block name="script"%}
<script>   
   
</script>

{%/block%}

{%block name="content"%} 
<style type="text/css" media="screen">

 
</style> 
<div class="box-title" id="header"> 
         <img src="{%$feroot%}/m/common/img/head_pic.jpg" alt="头像" class="head-pic">
           <span class="head-username">{%$userinfo.username%}</span>
           <span class="balance">本月累计收益 <span class="balance-count">￥{%$monthProfit%}</span></span> 
</div>
  
<div class="box-content">
		<ul class="income flex-x" style="border-bottom:1px solid #e7e7ec;">
          <li style="border-width:0px 1px 0px 0px;"><span class="title">待收收益</span><span class="count">￥{%$reposPrifit%}</span></li>
          <li><span class="title">累计收益</span><span class="count">￥{%$totalProfit%}</span></li>
    </ul>	
    <ul class="income flex-x">
          <li style="border-width: 0px 1px 0px 0px;"><span class="title">待收本金</span><span class="count">￥{%$reposPrincipal%}</span></li>
          <li><span class="title">累计投资</span><span class="count">￥{%$totalInvest%}</span></li>
    </ul> 
    <div class="reset-count">
      可用余额 <span class="count">￥{%$avlBal%}</span>
    </div>
    <ul class="menus">
      <li> 
        <!-- <a href="/m/account/recharge" class="account-link"> -->
        <a href="/account/cash/recharge" class="account-link">
           <i class="icon accountfont icon-recharge"></i>
          充值
          <i class="icon accountfont icon-directionright fr"></i>
        </a>
      </li>
      <li style="border-top: 1px solid #e2e1e4;">
        <a href="/m/invest" class="account-link">
        <i class="icon accountfont icon-invest"></i>
          投资
          <i class="icon accountfont icon-directionright fr"></i>
        </a>
      </li> 
    </ul>
    <ul class="menus" style="margin-top: 10px;">
         <li>
       <!--  <a href="/m/account/withdraw" class="account-link"> -->
       <a href="/account/cash/withdraw" class="account-link">
        <i class="icon accountfont icon-withdraw"></i>
          提现
          <i class="icon accountfont icon-directionright fr"></i>
        </a>
      </li>
      <li style="border-top: 1px solid #e2e1e4;">
     <!--    <a href="/m/account/cash" class="account-link"> -->
       <a href="/account/invest" class="account-link"> 
        <i class="icon accountfont icon-investlist"></i>
          投资记录
          <i class="icon accountfont icon-directionright fr"></i>
        </a>
      </li>
    </ul>
    <a href="{%$webroot%}/user/login/signout" class="common-a-btn logout">退出登录</a>
</div> 
{%/block%}