 {%extends file="../../../views/common/m/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/m/account/index.css" />
{%/block%} 

{%block name="script"%}
<script>   
   
</script>

{%/block%}

{%block name="content"%} 
<style type="text/css" media="screen">

 
</style> 
<div class="box-title" id="header"> 
         <img src="{%$feroot%}/m/common/img/head_pic.jpg" alt="头像" class="head-pic">
           <span class="head-username">{%$user.username%}</span>
           <span class="balance">可用余额 <span class="balance-count">￥{%$user.username%}</span></span> 
</div>
  
<div class="box-content">
		<ul class="income flex-x">
          <li style="border-width: 0px 1px 1px 0px"><span class="title">待收收益</span><span class="count">￥1500</span></li>
          <li><span class="title">累计收益</span><span class="count">￥1500</span></li>
    </ul>	
    <ul class="income flex-x">
          <li><span class="title">待收本金</span><span class="count">￥1500</span></li>
          <li  style="border-width: 1px 0px 0px 1px"><span class="title">累计投资</span><span class="count">￥1500</span></li>
    </ul> 
    <div class="reset-count">
      可用余额 <span class="count">￥200.00</span>
    </div>
    <ul class="menus">
      <li> 
        <a href="" class="account-link">
           <i class="icon accountfont icon-recharge"></i>
          充值
          <i class="icon accountfont icon-directionright fr"></i>
        </a>
      </li>
      <li style="border-top: 1px solid #e2e1e4;">
        <a href="" class="account-link">
        <i class="icon accountfont icon-invest"></i>
          投资
          <i class="icon accountfont icon-directionright fr"></i>
        </a>
      </li> 
    </ul>
    <ul class="menus" style="margin-top: 10px;">
         <li>
        <a href="" class="account-link">
        <i class="icon accountfont icon-withdraw"></i>
          提现
          <i class="icon accountfont icon-directionright fr"></i>
        </a>
      </li>
      <li style="border-top: 1px solid #e2e1e4;">
        <a href="" class="account-link">
        <i class="icon accountfont icon-investlist"></i>
          投资记录
          <i class="icon accountfont icon-directionright fr"></i>
        </a>
      </li>
    </ul>
    <a href="{%$webroot%}/user/login/signout" class="common-a-btn logout">退出登录</a>
</div> 
{%/block%}