{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="/src/home/index.less" />
{%/block%}

{%block name="script"%}
<script>
    require(['home/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
{%assign var="bannerList" value=[0 => "banner-one", 1 => "banner-two", 2 => "banner-three", 3 => "banner-four"]%}
<div class="banner">
    <div class="banner-floation">
        <ul class="banner-item">
            {%foreach $bannerList as $key => $item%}
            <li class="banner-item-list">
                <a class="banner-item-list-link {%$item%}"></a>
                <div class="banner-container">
                    <div class="fix-box">
                        {%if isset($user)%}
                        <div class="fix-box-title">
                            <p class="fix-title-number logining">欢迎您
                            </p>
                            <p class="fix-title-text">{%$user.username%}</p>
                        </div>
                        <div class="fix-box-main mar-top">
                            <a href="###" class="fix-box-main-regist ">管理我的账户</a>
                            <div class="fix-box-main-box">

                            </div>
                        </div>
                        {%else%}
                        <div class="fix-box-title">
                            <p class="fix-title-number">15.8
                                <span class="fix-title-number-bai">%</span>
                            </p>
                            <p class="fix-title-text">最高年化收利率</p>
                        </div>
                        <div class="fix-box-main">
                            <a href="###" class="fix-box-main-regist">快速注册</a>
                            <div class="fix-box-main-box">
                                已有账号？<a href="###" class="fix-box-main-box-login">立即登录</a>
                            </div>
                        </div>
                        {%/if%}

                    </div>
                </div>
            </li>
            {%/foreach%}
        </ul>
        <div class="banner-select">
            <a href="###" class="banner-select-link current">●</a>
            <a href="###" class="banner-select-link">●</a>
            <a href="###" class="banner-select-link">●</a>
            <a href="###" class="banner-select-link">●</a>
        </div>
    </div>



</div>
<div class="introduce">
    <div class="container">
        <div class="introduce-left">
            <div class="introduce-left-title"><span>兴教贷</span>是什么?</div>
            <div class="introduce-left-text">兴教贷是国内首家专注于教育平台的投融资公司兴教贷是国内首家专注于教育平台的投融资公司兴教贷是国内首家专注于教育平台的投融资公司。<a href="###">查看更多></a></div>
        </div>
        <div class="introduce-right">
            <div class="introduce-right-list">
                <div class="introduce-list-logo income"></div>
                <div class="introduce-list-title">低门槛高收入</div>

                <p class="introduce-list-link-text">互联网理财100元起投</p>
                <p class="introduce-list-link-text">超过银行存款利率30倍</p>

            </div>
            <div class="introduce-right-list">
                <div class="introduce-list-logo baozhang"></div>
                <div class="introduce-list-title">全方位投资保障</div>

                <p class="introduce-list-link-text">360度实地尽调、本金保障</p>
                <p class="introduce-list-link-text">第三方资金托管</p>

            </div>
            <div class="introduce-right-list last">
                <div class="introduce-list-logo teaching"></div>
                <div class="introduce-list-title">专注教育行业</div>

                <p class="introduce-list-link-text">深挖教育行业特性</p>
                <p class="introduce-list-link-text">最权威教育行业评估体系</p>

            </div>
        </div>
    </div>
</div>
<div class="main">
    <div class="container">
        <div class="newgonggao">
            <span class="newgonggao-title">最新公告</span>
            <a class="newgonggao-txt"><span class="symbol">•</span>兴教贷产品全新上线<span class="newgonggao-time">2014-12-12</span></a>
            <a class="newgonggao-more" href="###">更多 > ></a>
        </div>
        <div class="investlist">
            <div class="investlist-title">投资列表</div>
            <div class="investlist-box">
                <div class="investlist-box-title border-bottom">
                    <div class="investlist-box-title-name name">借款标题</div>
                    <div class="investlist-box-title-name grade">评估等级</div>
                    <div class="investlist-box-title-name lilv">年利率</div>
                    <div class="investlist-box-title-name price">金额</div>
                    <div class="investlist-box-title-name time">期限</div>
                    <div class="investlist-box-title-name jindu">进度</div>
                    <div class="investlist-box-title-name status">状态</div>
                </div>
                <div class="investlist-box-title">
                    <div class="investlist-box-title-name name">
                        <span class="name-shi">实</span>
                        <span class="school">福建三明高中扩建一期</span>
                    </div>
                    <div class="investlist-box-title-name grade">
                        <span class="grade-star level-aaa"></span>
                    </div>
                    <div class="investlist-box-title-name lilv">
                        <span class="lilv-number">12</span>
                        <span class="lilv-bai">%</span>
                    </div>
                    <div class="investlist-box-title-name price">
                        <span class="lilv-number color-blank">1,000,000</span>
                        <span class="lilv-bai">元</span>
                    </div>
                    <div class="investlist-box-title-name time">
                        <span class="lilv-number color-blank">6</span>
                        <span class="lilv-bai">个月</span>
                    </div>
                    <div class="investlist-box-title-name jindu">
                        <div class="jindu-box">
                            <div class="jindu-box-inline"></div>
                        </div>
                        <div class="jindu-number">
                            <span class="lilv-number">85</span>
                            <span class="lilv-bai">%</span>
                        </div>
                    </div>
                    <div class="investlist-box-title-name status">
                        <a class="status-biding" href="###">投标结束</a>
                    </div>
                </div>
                <div class="investlist-box-title">
                    <div class="investlist-box-title-name name">
                        <span class="name-shi">实</span>
                        <span class="school">福建三明高中扩建一期</span>
                    </div>
                    <div class="investlist-box-title-name grade">
                        <span class="grade-star level-b"></span>
                    </div>
                    <div class="investlist-box-title-name lilv">
                        <span class="lilv-number">12</span>
                        <span class="lilv-bai">%</span>
                    </div>
                    <div class="investlist-box-title-name price">
                        <span class="lilv-number color-blank">1,000,000</span>
                        <span class="lilv-bai">元</span>
                    </div>
                    <div class="investlist-box-title-name time">
                        <span class="lilv-number color-blank">6</span>
                        <span class="lilv-bai">个月</span>
                    </div>
                    <div class="investlist-box-title-name jindu">
                        <div class="jindu-box">
                            <div class="jindu-box-inline"></div>
                        </div>
                        <div class="jindu-number">
                            <span class="lilv-number">85</span>
                            <span class="lilv-bai">%</span>
                        </div>
                    </div>
                    <div class="investlist-box-title-name status">
                        <a class="status-biding current" href="###">投标结束</a>
                    </div>
                </div>
            </div>
            <a href="{%$webroot%}/invest/index" class="investlist-more">查看更多标的></a>
        </div>
    </div>
</div>
<div class="bottom">
    <div class="container">
        <div class="investlist-title btm-bank-title">合作伙伴</div>
        <div class="bottom-content">
            <a href="###" class="bottom-bank zhaoshang"></a>
            <a href="###" class="bottom-bank gongshang"></a>
            <a href="###" class="bottom-bank youzheng"></a>
            <a href="###" class="bottom-bank minsheng"></a>
            <a href="###" class="bottom-bank jianshe"></a>
            <a href="###" class="bottom-bank zhongguo"></a>
            <a href="###" class="bottom-bank pufa"></a>
            <a href="###" class="bottom-bank xingye"></a>
            <a href="###" class="bottom-bank nongye"></a>
            <a href="###" class="bottom-bank jiaotong"></a>
            <a href="###" class="bottom-bank guangda"></a>
            <a href="###" class="bottom-bank shanghai"></a>

        </div>

    </div>
</div>
{%/block%}