<div class="footer footer_v2">
    <div class="container">
        <div class="footer-left">
            <ul class="footer-item">
                <li class="footer-item-list">
                    <a   class="footer-item-link">友情链接</a>
                    <span class="footer-vertical"></span>
                </li> 
                <li class="footer-item-list">
                    <a target="_blank" href="http://canedu.org.cn/" class="footer-item-link">中国民办教育协会</a>
                 </li>
                <li class="footer-item-list">
                    <a target="_blank" href="http://www.gxmbedu.com/" class="footer-item-link"> 广西民办教育协会</a>
                 </li>
                <li class="footer-item-list">
                    <a target="_blank" href="http://www.moe.gov.cn/" class="footer-item-link">中国教育部</a>
                 </li> 
            </ul> 
        </div> 
        <div class="footer-right">
             <div class="phone-box fr" style="margin-left:0px;">
                <i class="iconfont icon-phone"></i>
               <span class="phone" >400-016-2526</span>
               <span class="worktime" >周一至周五9:00-18:00</span> 
               <span class="attention-box">
                                                                     关注我们&nbsp;:
                        <a class="iconfont attention-me weixin">
                            <div class="xinlang-erweima footer-erweima">
                                <div class="triangle-top footer-erweima-top"></div>
                                <div class="triangle-bottom footer-erweima-bottom"></div>
                            </div>
                        </a>
                        <a class="iconfont attention-me weibo" href="http://www.weibo.com/u/5478735172" target="_blank">
                            <div class="xinlang-erweima footer-erweima footer-tip">
                                <div class="triangle-top footer-erweima-top"></div>
                                <div class="triangle-bottom footer-erweima-bottom"></div>
                                点击关注兴教贷微博i<br/>
                                 <span class="weibo-tip-span">@xingjiaodai</span>
                            </div>
                        </a>
                   <!--      <a class="iconfont attention-me qq" href="http://jq.qq.com/?_wv=1027&amp;k=TWWLkD" target="_blank">
                       <div class="xinlang-erweima footer-erweima footer-tip">
                           <div class="triangle-top footer-erweima-top"></div>
                           <div class="triangle-bottom footer-erweima-bottom"></div>
                           加入投资交流群<br>
                           <span class="weibo-tip-span">389780348</span>
                       </div>
                   </a> -->
                    </span>
        </div>
        </div>
         <div class="footer-bottom">
           <table class="fl" width="135" border="0" cellpadding="0" cellspacing="0" title="Click to Verify - This site chose GeoTrust SSL for secure e-commerce and confidential communications.">
				<tr>
				<td width="135" align="left" valign="top"><script type="text/javascript" src="https://seal.geotrust.com/getgeotrustsslseal?host_name=www.xingjiaodai.com&amp;size=S&amp;lang=en"></script><br />
				<a href="http://www.geotrust.com/ssl/" target="_blank"  style="color:#000000; text-decoration:none; font:bold 7px verdana,sans-serif; letter-spacing:.5px; text-align:center; margin:0px; padding:0px;"></a></td>
				</tr>
		    </table>
		   
            <div class="footer-site-left fl">
                 <ul class="footer-item">
                <li class="footer-item-list">
                    <a target="_blank" href="{%$webroot%}/about" class="footer-item-link">关于我们</a>
                   <!--  <span class="footer-vertical">|</span> -->
                </li>
                <li target="_blank" class="footer-item-list">
                    <a href="{%$webroot%}/contact" class="footer-item-link">联系我们</a>
                    
                </li>
                <li target="_blank" class="footer-item-list">
                    <a href="{%$webroot%}/guide" class="footer-item-link">新手指引</a>
                </li>
                <li target="_blank" class="footer-item-list">
                    <a href="{%$webroot%}/security" class="footer-item-link">安全保障</a>
                </li>
                 <li target="_blank" class="footer-item-list">
                    <a href="{%$webroot%}/help" class="footer-item-link">帮助中心</a>
                </li>
            </ul> 
            <ul class="footer-item" style="margin-top: 5px;">
               <li target="_blank" class="footer-item-list" style="font-size: 12px;">
                 <!--      @{%$smarty.now|date_format:"%Y"%} -->
                    Copyright © 2014-2015
                    &nbsp;&nbsp;&nbsp;&nbsp;北京百年兴教网络科技有限公司&nbsp;&nbsp;&nbsp;&nbsp;京ICP备14061443号
               </li>
            </ul>  
             
               
         </div>
    </div>

</div> 