<div class="footer">
    <div class="container">
        <div class="footer-left">
            <ul class="footer-item">
                <li class="footer-item-list">
                    <a href="{%$webroot%}/about" class="footer-item-link">关于我们</a>
                    <span class="footer-vertical">|</span>
                </li>
                <li class="footer-item-list">
                    <a href="{%$webroot%}/contact" class="footer-item-link">联系我们</a>
                    <span class="footer-vertical">|</span>
                </li>
                <li class="footer-item-list">
                    <a href="{%$webroot%}/guide" class="footer-item-link">新手指引</a>
                    <span class="footer-vertical">|</span>
                </li>
                <li class="footer-item-list">
                    <a href="{%$webroot%}/security" class="footer-item-link">安全保障</a>
                </li>
            </ul>
            <div class="footer-site">
                <span class="footer-site-left"><span>@{%$smarty.now|date_format:"%Y"%}</span>北京百年兴教网络技术有限公司&nbsp;&nbsp;&nbsp;&nbsp;京ICP备14061443号</span>
                    <span class="footer-site-me">
                        关注我们:
                        <a class="footer-site-me-xinlang weixin">
                            <div class="xinlang-erweima footer-erweima">
                                <div class="triangle-top footer-erweima-top"></div>
                                <div class="triangle-bottom footer-erweima-bottom"></div>
                            </div>
                        </a>
                        <a target="_blank" href="http://www.weibo.com/u/5478735172" class="footer-site-me-xinlang weibo">
                            <div class="xinlang-erweima footer-erweima footer-tip">
                                <div class="triangle-top footer-erweima-top"></div>
                                <div class="triangle-bottom footer-erweima-bottom"></div>
                                点击关注兴教贷微博
                                <span class="weibo-tip-span">@xingjiaodai</span>
                            </div>
                        </a>
                    </span>
            </div>
        </div>
        <div class="footer-right">
            客服电话：400-016-2526
        </div>
    </div>

</div>