<div class="footer">
    <div class="container">
        <div class="footer-left">
            <ul class="footer-item">
                <li class="footer-item-list">
                    <a href="###" class="footer-item-link">友情链接</a>
                    <span class="footer-vertical"></span>
                </li>
                <li class="footer-item-list">
                    <a target="_blank" href="http://canedu.org.cn/" class="footer-item-link">中国民办教育协会</a>
                    <span class="footer-vertical"></span>
                </li>
                <li class="footer-item-list">
                    <a target="_blank" href="http://www.p2peye.com/" class="footer-item-link"> 网贷天眼</a>
                    <span class="footer-vertical"></span>
                </li>
                <li class="footer-item-list">
                    <a target="_blank" href="http://www.wangdaizhijia.com/" class="footer-item-link">网贷之家</a>
                    <span class="footer-vertical"></span>
                </li>
                <li class="footer-item-list">
                    <a target="_blank" href="http://www.hexun.com/" class="footer-item-link">和讯财经</a>
                 <span class="footer-vertical"></span>
                </li>
                
                <li class="footer-item-list">
                    <a target="_blank" href="http://www.eol.cn/" class="footer-item-link">中国教育在线</a>
                    <span class="footer-vertical"></span>
                <span class="footer-vertical"></span>
                </li>
                <li class="footer-item-list">
                    <a target="_blank" href="http://www.hjenglish.com/" class="footer-item-link">沪江网</a>
                 <span class="footer-vertical"></span>
                </li>
                <li class="footer-item-list">
                    <a target="_blank" href="http://beijing.rong360.com/" class="footer-item-link">融360</a>
                 <span class="footer-vertical"></span>
                </li>
                 <li class="footer-item-list">
                    <a target="_blank" href=" http://www.erongtu.com/" class="footer-item-link">融途网</a>
                </li>
                 <li class="footer-item-list">
                    <a target="_blank" href="http://p2p.hexun.com/" class="footer-item-link">和讯P2P</a>
                 <span class="footer-vertical"></span>
                </li>
                 <li class="footer-item-list">
                    <a target="_blank" href="http://www.eastmoney.com/" class="footer-item-link">东方财富</a>
                 <span class="footer-vertical"></span>
                </li>
                 <li class="footer-item-list">
                    <a target="_blank" href="http://finance.sina.com.cn/" class="footer-item-link">新浪财经</a>
                 <span class="footer-vertical"></span>
                </li>
                 <li class="footer-item-list">
                    <a target="_blank" href="http://www.fromgeek.com/iof/" class="footer-item-link">新金融</a>
                 <span class="footer-vertical"></span>
                </li>
                 <li class="footer-item-list">
                    <a target="_blank" href="http://edu.people.com.cn/" class="footer-item-link">人民网教育</a>
                 <span class="footer-vertical"></span>
                </li>
            </ul> 
        </div> 
         <div class="footer-bottom">
           <table class="fl" width="135" border="0" cellpadding="0" cellspacing="0" title="Click to Verify - This site chose GeoTrust SSL for secure e-commerce and confidential communications.">
				<tr>
				<td width="135" align="left" valign="top"><script type="text/javascript" src="https://seal.geotrust.com/getgeotrustsslseal?host_name=www.xingjiaodai.com&amp;size=S&amp;lang=en"></script><br />
				<a href="http://www.geotrust.com/ssl/" target="_blank"  style="color:#000000; text-decoration:none; font:bold 7px verdana,sans-serif; letter-spacing:.5px; text-align:center; margin:0px; padding:0px;"></a></td>
				</tr>
		    </table>
		   
            <div class="footer-site-left fl">
                 <ul class="footer-item">
                <li class="footer-item-list">
                    <a target="_blank" href="{%$webroot%}/about" class="footer-item-link">关于我们</a>
                    <span class="footer-vertical">|</span>
                </li>
                <li target="_blank" class="footer-item-list">
                    <a href="{%$webroot%}/contact" class="footer-item-link">联系我们</a>
                    <span class="footer-vertical">|</span>
                </li>
                <li target="_blank" class="footer-item-list">
                    <a href="{%$webroot%}/guide" class="footer-item-link">新手指引</a>
                    <span class="footer-vertical">|</span>
                </li>
                <li target="_blank" class="footer-item-list">
                    <a href="{%$webroot%}/security" class="footer-item-link">安全保障</a>
                </li>
            </ul> 
            <ul>
               <li target="_blank" class="footer-item-list" style="font-size: 12px;">
                 <!--      @{%$smarty.now|date_format:"%Y"%} -->
                    Copyright © 2014-2015
                    &nbsp;&nbsp;&nbsp;&nbsp;北京百年兴教网络技术有限公司&nbsp;&nbsp;&nbsp;&nbsp;京ICP备14061443号
               </li>
            </ul>  
             
               
         </div>
    </div>

</div>
<a id="scrollUp"  href="#top"></a>