 <div class="nav nav-v2">
    <div class="container">
        <a href="{%$webroot%}" class="logo"><img width="100%" src="{%$feroot%}/common/img/logo_v2.png" /></a>
          {%if isset($user)%}
            <div class="header-right-login fr">
                <span class="default-fastlogin" style="">您好，{%$user.username%} 
                     {%if $user.unreadMsg%}
                     <a class="unreadmsg" style="color: #f2746a;font-size: 10px;text-decoration: none;" href="{%$webroot%}/account/message"> （{%$user.unreadMsg%}条未读）</a> 
                     {%/if%}
                </span>
               
                <a class="default-login" href="/user/login/signout">退出</a>
            </div>
            {%else%}
            <div class="login-register register-hover fr">
                <a href="{%$webroot%}/user/regist" class="register fl">注册</a>
                <a class="login fr" href="{%$webroot%}/user/login">登录</a>
            </div>
            {%/if%} 
        <ul class="nav-item fr"> 
            <li class="nav-item-list">
                <a href="{%$webroot%}/apply" class="nav-item-link">融资贷款</a>
            </li> 
            <li class="nav-item-list">
                <a href="{%$webroot%}/invest" class="nav-item-link">投资理财</a>
            </li>
            <li class="nav-item-list">
                <a href="{%$webroot%}/about" class="nav-item-link">关于我们</a>
            </li>
        </ul>
       
    </div>
</div>
