<div class="company-menu">
 
<!--       <a href="{%$webroot%}/infos/post" class="company-menu-item {%if $current == '1'%}current{%/if%}">官方公告</a>
     <a href="{%$webroot%}/infos/media" class="company-menu-item {%if $current == '2'%}current{%/if%}">媒体报道</a> -->
   <!--  <a href="{%$webroot%}/collaborate" class="company-menu-item {%if $current == '3'%}current{%/if%}">合作伙伴</a>   -->
      <a href="{%$webroot%}/infos/refund" class="company-menu-item {%if $current == '1'%}current{%/if%}">还款公告</a>
      <a href="{%$webroot%}/infos/post" class="company-menu-item {%if $current == '2'%}current{%/if%}">平台公告</a>

</div>