<div class="company-menu">
    <a href="{%$webroot%}/about" class="company-menu-item {%if $current == '1'%}current{%/if%}">关于我们</a>
    <a href="{%$webroot%}/team" class="company-menu-item {%if $current == '2'%}current{%/if%}">团队介绍</a>
    <a href="{%$webroot%}/about/join" class="company-menu-item {%if $current == '3'%}current{%/if%}">加入我们</a>
    <a href="{%$webroot%}/contact" class="company-menu-item {%if $current == '4'%}current{%/if%}">联系我们</a>
    <a href="{%$webroot%}/infos/post" class="company-menu-item {%if $current == '5'%}current{%/if%}">官方公告</a>
<!--     <a href="{%$webroot%}/infos/media" class="company-menu-item {%if $current == '8'%}current{%/if%}">媒体报道</a>
    <a href="{%$webroot%}/collaborate" class="company-menu-item {%if $current == '3'%}current{%/if%}">合作伙伴</a> -->
</div>