{%if $smarty.const.MODULE eq 'Index'%}
	{%include file='../views/common/top.phtml'%}
{%else%}
	{%include file='../../../views/common/top.phtml'%}
{%/if%}
{%block name="link"%}{%/block%}
<script>
    require(['common/global']);
</script>
</head>
<body class="result-op">
	{%if $smarty.const.MODULE eq 'Index'%}
	    {%include file='../views/common/header.phtml'%}
	{%else%}
		{%include file='../../../views/common/header.phtml'%}
	{%/if%}
    <div id="main-wraper">
        {%block name="content"%}{%/block%}
    </div>
    {%if $smarty.const.MODULE eq 'Index'%}
    	{%include file='../views/common/footer.phtml'%}
	{%else%}
		{%include file='../../../views/common/footer.phtml'%}
	{%/if%}

    {%block name="script"%}{%/block%}
    {%if $tongji%}
    <script>
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "//hm.baidu.com/hm.js?1a153ca582e27235304d94fd094eb8a1";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
    {%/if%}
</body>
</html>