{%include file='../../../views/common/top.phtml'%}
{%block name="link"%}{%/block%}
<script>
    require(['common/global']);
</script>
</head>
<body class="result-op">
    {%include file='../../../views/common/header.phtml'%}
    <div id="main-wraper">
        {%block name="content"%}{%/block%}
    </div>
    {%include file='../../../views/common/footer.phtml'%}

    {%block name="script"%}{%/block%}
</body>
</html>