{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/company/us/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['company/common/common'], function(main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="container company">
    {%include file="common/menu.phtml" current="1"%}
    <div class="company-box">
        <div class="company-part-title">
            <h2 class="company-part-titlectx">关于我们</h2>
        </div>
        <div class="company-logo"></div>
        <h3 class="h-title">公司简介</h3>
        <p class="company-intro">
            兴教贷（www.xingjiaodai.com）— 北京百年兴教网络科技有限公司旗下互联网投融资理财服务平台，是国内首个专注于教育领域融资与理财的互联网金融产品，致力于满足教育从业者投资理财需求和解决教育机构融资问题，从而推动教育多元化发展。兴教贷将借助P2P/P2C模式、融资租赁模式、担保模式、信托资管模式、基金理财模式等线上线下结合的融资模式，为教育行业提供综合性金融解决方案。兴教贷平台立志于为数千万教育从业者提供全方位金融服务，以贷兴教，以教促学，帮助3亿人接受更优质教育。
        </p>
        <p class="company-intro">
            我们通过搭建具有高度公信力的互联网金融服务平台，把亟需资金但缺乏有效融资途径的相关教育机构和有理财需求却难觅安全投资渠道的教育从业者及其他人士无缝对接起来，让具有优质信用的教育从业者、学校及其投资者快速获得融资，实现自身信用价值，同时也为有理财需求的教育从业者和其他人士提供了一条新的安全理财渠道。
        </p>
        <h3 class="h-title">我们的使命</h3>
        <p class="company-intro">
            让所有教育从业者，尤其是热爱教育而兴办教育的从业者从普惠金融中获益，为中国教育改革进程的不断深化做出贡献。<br />
            1.让教育机构享受到全面高效的金融服务；<br />
            2.让所有的教育从业者树立起健康的理财观念；<br />
            3.为中国教育改革进程提供资金支持；<br />
            4.为解决中国教育公平问题贡献自身的力量；<br />
            5.为教育从业者提供综合性金融服务；<br />
            6.建立教育行业的信用数据库，树立行业规则。
        </p>
        <h3 class="h-title">我们的愿景</h3>
        <p class="company-intro">
            教育是一国之本，我们希望用我们自己的力量，固国本，兴国运。<br />
            1.我们希望，热爱教育、热爱孩子而兴办教育的人们不再受资金的困扰，能够更加专注教育本身；<br />
            2.我们希望，所有的孩子都能同在一片阳光下，享受公平的教育资源，拥有独立的人格、缤纷的个性，让这个国家、这个世界更加丰富多彩。
        </p>
<!--        <div class="company-kouhao">-->
<!--            我们坚信：教育，是您最好的投资。<br />-->
<!--            我们的愿景 ——“助力教育，投资未来” “做您最好的投资”-->
<!--        </div>-->
    </div>
</div>
{%/block%}