{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/company/us/index.css" />
<link rel="stylesheet" type="text/css" href="{%$feroot%}/common/extra/Gallery/css/blueimp-gallery.css" />
{%/block%}

{%block name="script"%}
  
 <script> 
    require(['company/common/common'], function(main) {
        main.init();
    });  

    require(['company/us/index'], function(main) {
        main.slide();
    });  
</script>
{%/block%}

{%block name="content"%} 
  <div class="company-nav"> 
	   <div class="company-navbar">  
	      <div class="container"> 
	         {%include file="common/menu.phtml" current="1"%}
	      </div>
	   </div>
    </div>
<div class="container main-container">

<div class="container container2"> 
   <div class="company-box1">
       <div class="button_box">
             <div class="button"><a href="#jieshao">公司介绍</a></div>
              <ul class="button_list">
                    <li><a href="#shiming">我们的使命</a></li> 
				    <li><a href="#shiming">LOGO释义</a></li> 
				    <li><a href="#zizhi">企业资质</a></li> 
	    		    <li><a href="#licheng">发展历程</a></li> 
              </ul>
       </div>
   </div>
   <div id="jieshao" class="company-box2">
          <div class="company-box"> 
        <h3 class="h-title">公司介绍</h3>
        <div class="company-intro">
                               兴教贷是北京百年兴教网络科技有限公司旗下互联网投融资理财服务平台，是国内首家专注教育领域投融资与理财服务的互联网金融产品。<br/>
                               兴教贷致力于解决教育机构融资问题、教育从业者资金需求以及社会民众的教育资金问题。在兴教贷平台，投资者可以将手中的富余资金出借给兴教贷认证的教育机构或个人，并获得利息回报。<br/>
                               借助P2P/P2C、融资租赁、担保模式、信托资管、基金理财等线上线下结合的投融资模式，兴教贷为教育行业提供综合性金融解决方案。兴教贷平台立志于为教育机构、数千万教育从业者以及亿万教育相关民众提供全方位金融服务，以贷兴教，以教促学，帮助几亿人接受更优质教育。我们希望成为教育事业的新助力，让更多人投资教育，分享收益。
      
        </div>  
    </div>
   </div>
   <div class="company-img1"> </div>
   <div  id="shiming" class="company-img2"> </div>
   <div  class="company-img3"> </div>
   <div id="zizhi"  class="company-box3">
                                 企业资质 
        <div id="links">
		    <a href="{%$feroot%}/company/us/img/quality1.jpg" title="营业执照">
		        <img src="{%$feroot%}/company/us/img/quality1_s.png" alt="quality1_s.png" height="170"/>
		    </a>
		    <a href="{%$feroot%}/company/us/img/quality2.jpg" title="税务登记证">
		        <img src="{%$feroot%}/company/us/img/quality2_s.png" alt="quality2_s.png" height="170"/>
		    </a>
		    <a href="{%$feroot%}/company/us/img/quality3.jpg" title="组织机构代码证">
		        <img src="{%$feroot%}/company/us/img/quality3_s.png" alt="quality3_s.png" height="170"/>
		    </a>
		</div> 
		<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
		    <div class="slides"></div>
		    <h3 class="title"></h3>
		    <a class="prev">‹</a>
		    <a class="next">›</a>
		    <a class="close">×</a>
		    <a class="play-pause"></a>
		    <ol class="indicator"></ol>
		</div>
   </div>
   <div  id="licheng" class="company-box4">
                      发展历程
        <ul class="company-licheng">  
	        <li>
				<span>2014.10</span> 
				<em class="licheng-icon"></em>  
				<span>来自金融和互联网的教友<br/>组成创始人团队</span>
			</li>
			 <li>
				<span>2014.12</span>  
				<em class="licheng-icon"></em>   
				<span>百年兴教公司在<br/>北京市海淀区注册成立</span>
			</li>
			 <li>
				<span>2014.12</span>   
				<em class="licheng-icon"></em>  
				<span>首批教友参加全国 <br/>民办教育协会年会</span>
			</li>
			 <li>
				<span>2015.01</span>   
				<em class="licheng-icon"></em>  
				<span>与汇付天下正式签订<br/>资金第三方托管合作</span>
			</li>
			 <li>
				<span>2015.02</span>  
				<em class="licheng-icon"></em>   
				<span>兴教贷网站上线公测</span>
			</li>
	    </ul>        
   </div>
   
   
</div>
</div>
{%/block%}