<html>
    <head>
    <!--script language="javascript"type="text/javascript"> 
           window.location.href="http://www.baidu.com/search/error.html"; 
    </script -->
    	<title>兴教贷 - 专注教育领域的互联网金融投融资理财平台</title>
    	<style type="text/css">
    	body{font-size: 14px;color: #666}
    	p{line-height: 1em;}
    	blockquote{line-height: 1.5em;letter-spacing: 3px;}
    	div{text-align: center;}
    	</style>
    </head>
    <body>
	    {%if $code%}
        <p>错误代码：{%$code%}</p>
        <p>错误信息：{%$message%}</p>
	    {%/if%}
    <div id="content">
    	<h3>页面去哪了？</h3>
    	<p>抱歉，程序媛姐姐说这个页面被月亮吃掉了。让她给您读首湿以作宽慰吧：</p>
    	<blockquote>我喜欢你是寂静的，好像你已远去。<br />
    	你听起来像在悲叹，一只如鸽悲鸣的蝴蝶。<br />
    	你从远处听见我，我的声音无法企及你，<br/>
    	让我在你的沉默中安静。</blockquote>
	</div>
    </body>
</html>
