{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/my/reward/index.css" />
{%/block%}

{%block name="script"%}
 
<script>
require(['my/reward/index'], function (main) {
    main.init();
})
</script>
{%/block%}

{%block name="content"%}
<div class="finish">
    <div class="container finish-bg-color">
        {%include file='../../../views/common/nav.phtml' current="8"%}
        <div class="finish-main">
            <div class="finish-main-title">我的奖券</div>
             <div class="my-reward-tab">
                <span class="my-reward-tab-item current" data-value="2">未使用</span>
                <span class="my-reward-tab-item" data-value="3">已使用</span>
                <span class="my-reward-tab-item" data-value="4">已过期</span> 
                <span class="my-reward-tab-item-no" style="">&nbsp;</span> 
            </div>
            <div class="my-reward-tip my-reward-tip-success" style="display:none"> 
              <span class="statusInfo"></span>
              <span class="close-reward-tip" style="top: 0px; width: 20px; height: 20px; right: 0px; display: block; position: absolute;">×</span>
            </div>
            <div id="my-reward-list" class="my-reward-list"> 
                <div class="xjd-loading">&nbsp;</div>
            </div> 
            <div id="my-reward-pager" class="my-reward-pager"></div>
        </div>
    </div>
</div>

{%/block%}