{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                             Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
            {%if $status==1%}借款审核
            {%elseif $status==3%}满标审核
            {%elseif $status==4%}借款放款
            {%else%}借款列表 <small>所有借款</small>
            {%/if%}
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">借款列表</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->

            <!-- BEGIN LIST -->
            <div class="row-fluid">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>借款编号</th>
                            <th>借款用户</th>
                            <th>借款标题</th>
                            <th>金额 ¥</th>
                            <th>利率 %</th>
                            <th>期限/天</th>
                            <th>状态</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%foreach from=$arrLoan key=i item=loan%}
                        <tr>
                            <td><a href="/admin/loan/request?loanid={%$loan.id%}&userid={%$loan.user_id%}">{%$loan.id%}</a></td>
                            <td><a href="/admin/corp/detail?userid={%$loan.user_id%}">{%$loan.user_id%}</a></td>
                            <td>{%$loan.title%}</td>
                            <td>{%$loan.amount%}</td>
                            <td>{%$loan.interest%}</td>
                            <td>{%$loan.duration%}</td>
                            <td>{%$loan.status_name%}</td>
                            <td>
                            {%if $loan.status==1%}<!--借款审核-->
                                <a href="/admin/loan/request?userid={%$loan.user_id%}&loanid={%$loan.id%}">编辑 </a> 
                                <a href="/admin/loan/publish?loanid={%$loan.id%}&isopen=0" onclick = "con(this);return false;">发布上线</a>
                            {%elseif $loan.status==10%}<!--即将开启-->
                                <a href="/admin/loan/request?userid={%$loan.user_id%}&loanid={%$loan.id%}">编辑 </a> 
                                <a href="/admin/loan/publish?loanid={%$loan.id%}&isopen=-1" onclick = "con(this);return false;">下线 </a> 
                                <a href="/admin/loan/publish?loanid={%$loan.id%}&isopen=1" onclick = "con(this);return false;">开启投标</a>
                            {%elseif $loan.status==3%}<!--满标审核-->
                                <a href="/admin/loan/audit?loanid={%$loan.id%}" onclick = "con(this);return false;">确定通过</a>
                            {%elseif $loan.status==4%}<!--借款放款-->
                                <a href="/admin/loan/loan?loanid={%$loan.id%}" onclick = "con(this);return false;">放款</a>
                            {%else%}
                                {%$loan.status%}
                            {%/if%}
                            </td>
                        </tr>
                        {%/foreach%}
                    </tbody>
                </table>
            </div>
            <!-- END LIST -->
            <div id="setpage"  style = "text-align: center;font-size:17px;margin:0 auto;"></div> 
        </div>
    </div> 
    <script src = "{%$feroot%}s/global/scripts/pageCut.js"></script>
    <script>
    cpage = {%$page%}; 
    totalpage = {%$pageall%}; 
    setpage(cpage,totalpage);
    </script>
    <script>
    function con(sourceobj){
        if(confirm("您确定要进行此操作吗?")){
    		var url = $(sourceobj).attr("href");
    		art.dialog.open(url, {title: 'title',width: 400, height: 300});
    		return false;
    		}
        else{
			alert("您取消了操作");
            }
    }
    </script>
{%/block%}