{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                             Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
                             借款申请列表<small>&nbsp&nbsp所有申请</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">借款申请列表</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->

            <!-- BEGIN LIST -->
            <div class="row-fluid">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>借款编号</th>
                            <th>借款标题</th>
                            <th>学校类型</th>
                            <th>借款用途</th>
                            <th>金额 ¥</th>
                            <th>利率 %</th>
                            <th>借款人</th>
                            <th>省份</th>
                            <th>联系方式</th>
                            <th>创建时间</th>
                            <th>状态</th>
                         
                        </tr>
                    </thead>
                    <tbody>
                        {%foreach from=$arrRequest  key=i item=request%}
                        <tr>
                            <td>{%$request.id%}</td>
                            <td>{%$request.title%}</td>
                            <td>{%$request.school_typename%}</td>
                            <td>{%$request.use_typename%}</td>
                            <td>{%$request.amount%}</td>
                            <td>{%$request.interest%}</td>
                            <td>{%$request.name%}</td>
                            <td>{%$request.level_name%}</td>
                            <td>{%$request.contact%}</td>
                            <td>{%$request.create_time|date_format:"%Y-%m-%d %H:%M"%}</td>
                            <td>{%$request.refund_status%}</td>
                        </tr>
                        {%/foreach%}
                    </tbody>
                </table>
            </div>
             <div id="setpage"  style = "text-align: center;font-size:17px;margin:0 auto;"></div> 
            <!-- END LIST -->
        </div>
    </div>
    <script src = "{%$feroot%}s/global/scripts/pageCut.js"></script>
    <script>
    cpage = {%$page%}; 
    totalpage = {%$pageall%}; 
    setpage(cpage,totalpage);
    </script>
{%/block%}