{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                             Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
            {%if $loanid%}
            借款详情编辑 <small>edit</small>
            {%else%}
            申请借款 <small>request</small>
            {%/if%}
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="/admin/loan">借款列表</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">{%if $loanid%}借款详情编辑{%else%}申请借款{%/if%}（{%$user.name%}）</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div class="row-fluid">
                {%if $error_msg%}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <strong>Warning! </strong> {%$error_msg%}
                </div>
                {%/if%}

                <!-- BEGIN FORM-->
                <form role="form" method="post" action="">
                    {%if $sub_error_msg%}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <strong>Warning! </strong> {%$sub_error_msg%}
                    </div>
                    {%/if%}
                    <!-- FORM FIELDS-->
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title">借款详情</h3>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="title">借款标题</label>
                                <input type="email" class="form-control" id="title" placeholder="填写借款标题">
                            </div>
                            <div class="form-group">
                                <label for="area">所在地</label>
                                <div class="dropdown">
                                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">广西 <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">湖北</a></li>
                                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">北京</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="typeid">标的类型</label>
                                <div class="dropdown">
                                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">实地认证标 <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">信用认证表</a></li>
                                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">机构担保标</a></li>
                                    </ul>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="catid">借款类型</label>
                                <div class="dropdown">
                                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">学校助力贷 <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">教师圆梦贷</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputFile">File input</label>
                                <input type="file" id="exampleInputFile">
                                <p class="help-block">Example block-level help text here.</p>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="fresh"> 新手专项标
                                </label>
                            </div>
                            <button type="submit" class="btn btn-success">保存</button>
                        </div>
                    </div>
                    <!-- FORM FIELDS-->
                    <!-- FORM FIELDS-->
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title">项目详情</h3>
                        </div>
                        <div class="panel-body">
                            
                        </div>
                    </div>
                    <!-- FORM FIELDS-->
                </form>
                <!-- END FORM-->  
            </div>

        </div>
    </div>
{%/block%}