 {%extends file="../../../views/common/m/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/common/extra/FlexSlider/flexslider.css" />
<link rel="stylesheet" type="text/css" href="{%$feroot%}/common/extra/Gallery/css/blueimp-gallery.css" />
<link rel="stylesheet" type="text/css" href="{%$feroot%}/m/project/detail/index.css" />

{%/block%} 

{%block name="script"%}
<script>
  require(['m/project/detail/index'], function (main) {
        main.init({
            id: '{%$data.id%}',
            amountRest: '{%$data.amount_rest%}',
            userAmount: '{%if isset($userBalance.amount)%}{%$userBalance.amount%}{%else%}0.00{%/if%}',
            interest: +'{%$data.interest%}',
            days: +'{%$data.days%}',
            sTime: +'{%$data.create_time%}',
            eTime: +'{%$data.deadline%}',
            fullTime: +'{%$data.full_time%}'
        });
  }); 
</script>

{%/block%}

{%block name="content"%} 
 <style>
   #files{
    width: 100%;
   }
 </style>
<div class="invest">
   <div class="box-title">
   	  <div style="margin:0 auto;min-width:236px;" class="flex-center align-center">
   	  	<span class="name-shi" style="margin:0px;">
	    {%if $item.type_id == 1%}实
        {%else if $item.type_id == 2%}信
        {%else%}机
        {%/if%}
	  </span>
	  <span class="project-title" >
	  	 {%$data.title%}
	  </span> 
	  {%if isset({%$data.level_name%})%}
            <span class="grade-star level-{%$data.level_name%}" ></span>
      {%/if%}
  </div>
   </div>
	<div class="box-content">
	    <ul class="investlist">
	    	<li class="item" style=""> 
	    		<div class="content align-center">
	    			<span class="lilv">
	    				年利率<br/>
	    				  <span class="lilv-number">{%$data.interest%}</span>%
	    			</span>
	    			<span class="price" style="-webkit-box-flex:1;-webkit-flex:1;flex:1;">
	    				<span class="price-title flex-center">
	    					<span class="total">借款总额<label class="count">&nbsp;￥{%$data.amount%}</label></span>
	    				    <span class="lilv-day">期限<label class="count">&nbsp;{%$data.duration_day%}{%$data.duration_type%}</label></span>
	    				</span>
	    				 <span class="price-title">
	    					<span class="time">截止时间：{%$data.deadline|date_format:'%Y-%m-%d %H:%M'%}</span>
	    				</span> 
	    				<span class="price-content">  
		                     <span class="jindu-number">
		                            80%
		                     </span> 
		    				<span class="jindu">
		    					 <span class="jindu-box">
		                            <span class="jindu-box-inline" style="width: 80%;"></span>
			                     </span>
	    					</span> 
	    				</span> 
	    		    </span>  
	    		</div>
	    	</li> 
	    	<li class="item">借款编号：JK_{%$data.id%}</li>
	    	<li class="item">还款方式：{%$data.refund_typename%}</li>
	    	<li class="item flex-center" style="width:100%;padding-right: 10px;"> 
	    		<div class="span " style="width:65px;max-width:65px;">保障方式：</div>
                <div class="baozhang-box " style="-webkit-box-flex:1;-webkit-flex:1;flex:1; ">  
                 {%foreach $data.safemode as $key => $item%}
               	    <span class="baozhang-type benxi">{%$item%}</span>  
               	 {%/foreach%}  
	    	    </div>  
	    	</li> 
	    </ul>
	    <div class="pro-action" style="margin-top: 20px;">
		    <div class="pro-title">项目介绍</div>
		    <div class="pro-content" >
                     {%if isset($userBalance.amount)%}
                        {%if !empty($data.private)%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">借款人信息</div>
                            <div class="main-detail-content">
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">姓名：</div>
                                        <div class="file-left-text">{%$data.private.showname%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">所处职位：</div>
                                        <div class="file-left-text">{%$data.private.job_title%}</div>
                                    </div>
                                    <!-- <div class="file-left-box">
                                        <div class="file-left-name">婚否：</div>
                                        <div class="file-left-text">{%if $data.private.marriage == 1%}是{%else%}否{%/if%}</div>
                                    </div> -->
                                </div>
                                <div class="file-enter">
                                    <!-- <div class="file-left-box">
                                        <div class="file-left-name">单位类别：</div>
                                        <div class="file-left-text">{%$data.private.company_type%}</div>
                                    </div> -->
                                    <div class="file-left-box">
                                        <div class="file-left-name">婚否：</div>
                                        <div class="file-left-text">{%if $data.private.marriage == 1%}是{%else%}否{%/if%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">年龄：</div>
                                        <div class="file-left-text">{%$data.private.age%} 岁</div>
                                    </div>
                                </div>
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">户口：</div>
                                        <div class="file-left-text">{%$data.private.account%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">年收入：</div>
                                        <div class="file-left-text">{%$data.private.income%}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {%/if%}
                        {%if !empty($data.company)%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">借款机构</div>
                            <div class="main-detail-content">
                                <div class="main-detail-content-left">
                                    <div class="left-box flex-center">
                                        <div class="content-left-name">借款机构：</div>
                                        <div class="content-left-text">{%$data.company.school%}</div>
                                    </div>
                                    <div class="left-box flex-center">
                                        <div class="content-left-name">区域位置：</div>
                                        <div class="content-left-text">{%$data.company.area_name%}</div>
                                    </div>
                                    <div class="left-box flex-center">
                                        <div class="content-left-name">资产总值：</div>
                                        <div class="content-left-text">{%$data.company.assets%}</div>
                                    </div>
                                    <div class="left-box flex-center">
                                        <div class="content-left-name">教职工数量：</div>
                                        <div class="content-left-text">{%$data.company.employers%}+ 名</div>
                                    </div>
                                      <div class="left-box flex-center">
                                        <div class="content-left-name">成立日期：</div>
                                        <div class="content-left-text right-text">{%$data.company.years%} 年</div>
                                    </div>
                                    <div class="left-box flex-center">
                                        <div class="content-left-name">注册资金：</div>
                                        <div class="content-left-text right-text">{%$data.company.funds%}</div>
                                    </div>
                                    <div class="left-box flex-center">
                                        <div class="content-left-name">学生数量：</div>
                                        <div class="content-left-text right-text">{%$data.company.students%}+ 名</div>
                                    </div>
                                    <div class="left-box flex-center">
                                         <div class="content-left-name">借款详情：</div>
                                         <div class="content-left-text right-text">{%$data.content%} </div>
                                    </div>
                                </div>  
                            </div>
                        </div>
                        {%/if%}
                        {%if !empty($data.counter)%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">信用档案</div>
                            <div class="main-detail-content">
                                <div class="main-detail-content-left">
                                     <div class="left-box flex-center">
                                        <div class="content-left-name">成功借款：</div>
                                        <div class="content-left-text">{%$data.counter.success%} 笔</div>
                                    </div>
                                     <div class="left-box flex-center">
                                        <div class="content-left-name">还清笔数：</div>
                                        <div class="content-left-text">{%$data.counter.finished%} 笔</div>
                                    </div>
                                     <div class="left-box flex-center">
                                        <div class="content-left-name">授信额度：</div>
                                        <div class="content-left-text">{%$data.counter.limit%} 元</div>
                                    </div>
                                     <div class="left-box flex-center">
                                        <div class="content-left-name">已还金额：</div>
                                        <div class="content-left-text">{%$data.counter.refund%} 元</div>
                                    </div>
                                      <div class="left-box flex-center">
                                        <div class="content-left-name">累计借款：</div>
                                        <div class="content-left-text">{%$data.counter.total%} 元</div>
                                    </div>
                                     <div class="left-box flex-center">
                                        <div class="content-left-name">待还本息：</div>
                                        <div class="content-left-text">{%$data.counter.rest%} 元</div>
                                    </div>
                                </div> 
                            </div>
                        </div>
                        {%/if%}
                        {%if !empty($data.guarantee)%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">担保人信息</div>
                            <div class="main-detail-content">
                                <div class="main-detail-content-left">
                                     <div class="left-box flex-center">
                                        <div class="content-left-name">姓名：</div>
                                        <div class="content-left-text">{%$data.guarantee.name%}</div>
                                    </div>
                                    <div class="left-box flex-center">
                                        <div class="content-left-name">所处职位：</div>
                                        <div class="content-left-text">{%$data.guarantee.job_title%}</div>
                                    </div>  
                                    <div class="left-box flex-center">
                                        <div class="content-left-name">婚否：</div>
                                        <div class="content-left-text">{%if $data.guarantee.marriage == 1%}是{%else%}否{%/if%}</div>
                                    </div>
                                    <div class="left-box flex-center">
                                        <div class="content-left-name">年龄：</div>
                                        <div class="content-left-text">{%$data.guarantee.age%}岁</div>
                                    </div> 
                                    <div class="left-box flex-center">
                                        <div class="content-left-name">户口：</div>
                                        <div class="content-left-text">{%$data.guarantee.account%}</div>
                                    </div>
                                    <div class="left-box flex-center">
                                        <div class="content-left-name">年收入：</div>
                                        <div class="content-left-text">{%$data.guarantee.income%}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {%/if%}
                        {%if !empty($data.audit)%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">审核信息</div>
                            {%foreach $data.audit as $key => $item%}
                            <div class="renzheng-box">
                                <div class="renzheng-title">{%$key%}</div>
                                <div class="renzheng-box-main">
                                    {%foreach $item as $index => $temp%}
                                    <div class="renzheng-big-box">
                                        <div class="renzheng-box-main-box-pic {%$mapType[$temp.name]%}"></div>
                                        <div class="renzheng-box-main-box-name">{%$temp.name%}</div>
                                    </div>
                                    {%/foreach%}
                                </div>
                            </div>
                            {%/foreach%}
                        </div>
                        {%/if%}
                        {%if isset($data.audit_info)%}
                        <div class="details-main-box bor-btm">
                            <div class="main-box-detail-title">审核通过</div>
                            <div class="detail-pass">{%$data.audit_info%}</div>
                            <div class="detail-symbol"></div>
                        </div>
                        {%/if%}
                        {%else%}
                        <div class="detail-unlogin">
                            请 <a href="/m/login">登录</a> 或 <a href="/m/regist">注册</a> 后查看
                        </div>
                        {%/if%}
		    </div>
		</div>
		<div class="pro-action">
		    <div class="pro-title">文件资料</div>
		    <div class="pro-content" >
		    	 {%if isset($userBalance.amount)%} 
                    <div class="details-main-box"> 
                         <div class="main-detail-content" id="files">
                             <ul class="detail-item slides" >
                              {%if !empty($data.attach['认证材料'])%}
                                    {%foreach $data.attach['认证材料'] as $key => $item%}
                                    <li class="detail-item-list img-city">
                                        <a href="{%$item.thumb%}" title="{%$item.title%}">
                                        <img alt="{%$item.title%}" class="detail-item-list-img" src="{%$item.thumb%}" /></a>
                                        <p class="detail-item-p">{%$item.title%}</p>
                                    </li>
                                    {%/foreach%} 
                               {%/if%} 
                               {%if !empty($data.attach['合同协议'])%} 
                                    {%foreach $data.attach['合同协议'] as $key => $item%}
                                    <li class="detail-item-list">
                                         <a href="{%$item.thumb%}" title="{%$item.title%}">
                                        <img alt="{%$item.title%}" class="detail-item-list-img" src="{%$item.thumb%}" style="width: 100px;height:150px;"/></a>
                                        <p class="detail-item-p">{%$item.title%}</p>
                                    </li>
                                    {%/foreach%} 
                                {%/if%}
                                {%if !empty($data.attach['实地照片'])%} 
                                    {%foreach $data.attach['实地照片'] as $key => $item%}
                                    <li class="detail-item-list img-city" >
                                         <a href="{%$item.thumb%}" title="{%$item.title%}">
                                        <img alt="{%$item.title%}" style="" class="detail-item-list-img" src="{%$item.thumb%}" /></a>
                                        <p class="detail-item-p">{%$item.title%}</p>
                                    </li>
                                    {%/foreach%} 
                                 {%/if%}
                              </ul>
                            </div>
                    </div>
                    <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls"> 
                       <div class="slides"></div>
                        <h3 class="title"></h3>
                        <a class="prev">‹</a>
                        <a class="next">›</a>
                        <a class="close">×</a>
                        <a class="play-pause"></a>
                        <ol class="indicator"></ol>
                    </div>
                  {%else%}
                <div class="detail-unlogin">
                    请 <a href="/m/login">登录</a> 或 <a href="/m/regist">注册</a> 后查看
                </div>
               {%/if%}
		    </div>
		</div>	
		<div class="pro-action">
		    <div class="pro-title">投资记录</div>
		    <div class="pro-content">
		    	  {%if isset($userBalance.amount)%}
                        <div class="details-main-box"> 
                            <div class="main-detail-content" id="toulist">
                            </div>
                        </div>
                        <div id="page"></div>
                        {%else%}
                        <div class="detail-unlogin">
                            请 <a href="/m/login">登录</a> 或 <a href="/m/regist">注册</a> 后查看
                        </div>
                  {%/if%}
		    </div>
		</div>	
        <div class="status">
        	<a class="combtn status-biding"  href="/m/invest/bid?id={%$data.id%}">立即投资</a>	 
        	{%if isset($userBalance.amount)%}
        	  <span class="reset-count">可用余额
        		 <label class="count">￥{%$userBalance.amount_text%}</label>
              </span> 
        	{%else%}
        	      <a href="/m/login" class="color-green">立即登录</a>
        	{%/if%}
        	<span class="recharge fr">余额不足？
                 <!--  <a href="/m/account/recharge" class="to-recharge">立即充值</a> -->
                <a href="/account/cash/recharge" class="to-recharge">立即充值</a> 
            </span>	
        </div>
			
	</div>
</div>
{%/block%}