 {%extends file="../../../views/common/m/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/m/project/list/index.css" />
{%/block%} 

{%block name="script"%}
<script>   
   require(['m/project/list/index'], function (main) {
        main.init({
            page: '{%$data.page%}',
            pageall: '{%$data.pageall%}',
            pagesize: '{%$data.pagesize%}'
        }); 
    });
</script>

{%/block%}

{%block name="content"%} 
<style type="text/css" media="screen">

 
</style>
<div class="invest">
<div class="box-title {%if isset($user)%}login{%/if%}" id="header">
   	   {%if isset($user)%}
         <img src="{%$feroot%}/m/project/list/img/head_pic.jpg" alt="头像" class="head-pic">
           <span class="head-username">{%$user.username%} fanyy</span>
           <span class="balance">可用余额 <span class="balance-count">￥242,223,234.00</span></span>
       {%else%} 
         <a class="common-a-btn btn-login fl" href="{%$webroot%}/m//login" >登录</a>
         <a class="common-a-btn btn-regist fl" href="{%$webroot%}/m/regist">注册</a>
       {%/if%}
</div>
  
<div class="box-content" id="wrapper">
		<div id="scroller">
			<div id="pullDown">
			   <span class="pullDownIcon"></span><span class="pullDownLabel">加载最新</span>
		    </div>
		    <ul class="investlist" id="investlist-box">
		    	 
		    </ul>
		    <div id="pullUp">
				<span class="pullUpIcon"></span><span class="pullUpLabel">加载更多</span>
			</div>
		</div>			
</div>
 </div>
{%/block%}