 {%extends file="../../../views/common/m/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/m/login/index.css" />
{%/block%} 

{%block name="script"%}
<script>
  /*   require(['company/infos/index'], function(main) {
        main.init({
            pageall: '{%$data.pageall%}',
            page: '{%$data.page%}',
            type: 'post'
        });
    }); */
</script>

{%/block%}

{%block name="content"%}
 xxxx

{%/block%}