{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                             Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
            充值列表
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">充值列表</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
             <form class="form-horizontal" role="form" method="post" action="/admin/finance/cash">
	            <div class="form-group">
	                 <label for="username" class="col-sm-2 control-label">输入用户名</label>
	                 <div class="col-sm-4">
	                      <input type="text" class="form-control" name="username" id="username" placeholder="用户名">
	                 </div>
	                 <div class="form-group">
	                       <input type="submit" class="btn btn-default" value="查询"/>
	                 </div>
	            </div>
	         </form>
	            <div class="row-fluid">
	                <table class="table table-striped">
	                    <thead>
	                        <tr>
	                            <th>ID</th>
	                            <th>用户名</th>
	                            <th>汇付号</th>
	                            <th>手机号</th>
	                            <th>充值订单号</th>
	                            <th>充值金额</th>
	                            <th>充值日期</th>
	                            <th>状态</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                        {%foreach from=$arrUser key=i item=user%}
	                        <tr>
	                            <td>{%$user.userid%}</td>
	                            <td>{%$user.name%}</td>
	                            <td>{%$user.huifuid%}</td>
	                            <td>{%$user.phone%}</td>
	                            <td>{%$user.orderId%}</td>
	                            <td>{%$user.transAmt%}</td>
	                            <td>{%$user.orderDate%}</td>
	                            <td>{%$user.status%}</td>
	                        </tr>
	                        {%/foreach%}
	                    </tbody>
	                </table>
	            </div> 

        </div>
    </div>   
   
    <div id="setpage"></div> 
    <script src = "{%$feroot%}s/global/scripts/pageCut.js"></script>
    <script>
    cpage = {%$page%}; 
    totalpage = {%$pageall%}; 
    setpage(cpage,totalpage);
    </script>
{%/block%}
