{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/company/team/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['company/common/common'], function(main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="container company">
    {%include file="common/menu.phtml" current="2"%}
    <div class="company-box">
        <div class="company-part-title">
            <h2 class="company-part-titlectx">团队介绍</h2>
        </div>
<!--        <ul class="team-list">-->
<!--            <li class="team-item">-->
<!--                <img src="{%$feroot%}/company/us/img/logo.png" />-->
<!--                <div class="team-item-intro">-->
<!--                    <div class="team-name">-->
<!--                        跟着大哥有鱼吃 <span class="team-name-intro">总裁</span>-->
<!--                    </div>-->
<!--                    <p class="team-intro">-->
<!--                        跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃-->
<!--                    </p>-->
<!--                </div>-->
<!--            </li>-->
<!--            <li class="team-item">-->
<!--                <img src="{%$feroot%}/company/us/img/logo.png" />-->
<!--                <div class="team-item-intro">-->
<!--                    <div class="team-name">-->
<!--                        跟着大哥有鱼吃 <span class="team-name-intro">总裁</span>-->
<!--                    </div>-->
<!--                    <p class="team-intro">-->
<!--                        跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃跟着大哥有鱼吃-->
<!--                    </p>-->
<!--                </div>-->
<!--            </li>-->
<!--        </ul>-->
        <p class="company-intro">
            我们的创始团队主要来自金融（知名投行、大型银行）和互联网（百度）的跨界精英，有丰富的教育、金融与互联网经验和资源，团队成员均毕业于北大、清华、复旦等国内顶尖高校。作为国内首家专注于教育行业的互联网P2P投资理财金融服务平台，我们努力为投资人与教育机构等借款人创造透明、安全的平台环境。我们积累了丰富的教育领域投融资经验，建立了完善的教育行业风险评估体系，为投资人提供全方位的投资安全保障措施。
        </p>
        <p class="company-intro">
            我们专注于教育领域的互联网产品创新，相信互联网将在不远的未来将彻底改变教育行业的生态结构。让我们实践自身教育理想，沿着互联网的道路助力教育行业的变革，让国家和世界的未来更加美好。
        </p>
    </div>
</div>

{%/block%}