{%extends file="../../../views/common/m/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/m/open/index.css" />
{%/block%}

{%block name="script"%}
<script>
  
</script>
{%/block%}

{%block name="content"%}
 <div class="kaitong">
      <div class="kaitong-box-title flex-center">
          <div  class="logo-img">
             <img alt="兴教贷" src="{%$feroot%}/m/common/img/logo.png">
           </div>
      </div>
      <div class="success-box-content flex-center"> 
           <div class="success-box-content-bg"> 
                <img alt="兴教贷" src="{%$feroot%}/m/common/img/success.png"> 
           </div>   
       </div>  
        <a class="begin" href="/">开始投资之旅</a> 
        <a class="begin" href="m/open/activity">立即参加活动</a> 
         {%if isset($hint)%} 
        <span class="welcome">欢迎参与活动</span>
         {%/if%}  
   </div>
 

{%/block%}
