{%extends file="../../../views/common/m/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/m/open/index.css" />
{%/block%}

{%block name="script"%}
<script>
  
</script>
{%/block%}

{%block name="content"%}
 <div class="kaitong">
      <div class="kaitong-box-title">
          <div  class="logo-img">
             <img alt="兴教贷" src="{%$feroot%}/m/common/img/logo.png">
           </div>
      </div>
      <div class="success-box-content"> 
           <div class="success-box-content-bg">  
           </div>   
            <a class="begin">开始投资之旅</a>
       </div>         
      
   </div>
 

{%/block%}
