 {%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/apply/school/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['apply/school/index'], function (main) {
        main.init({%$data.minmax.min%},{%$data.minmax.max%});  
    });   
</script>
{%/block%}

{%block name="content"%} 
<div class="box1" >
    <div class="container container2  step">
     <div class="container">
       {%include file='../../../views/common/loaninfo.phtml' type="1" current="3"%}
        <div class="title">
             <i class="iconfont icon-step3"></i>
             <span>学校评估</span>
        </div>
    </div>
    </div> 
</div>
<div class="box2 loan">
    <div class="container">
        <div class="left">  
              <div class="form-default_element form-inpt"> 
                  <div class="loan-label fl">＊学校地址</div>
                  <div class="loan-input fl">  
                         <input autocomplete="off" value="{%$data.edit.address%}" type="text" name="address" data-text="学校地址" placeholder="请输入学校地址"/> 
                  </div> 
                  <div class="input-icon fl" id="address-icon"></div>
                  <div class="input-error fl" id="address-error"></div>
              </div> 
              <div class="form-default_element form-inpt"> 
                  <div class="loan-label fl">＊您的学校有多少学生</div>
                  <div class="loan-input fl">  
                         <input autocomplete="off" value="{%$data.edit.total_student%}" type="number" name="total_student" data-text="学生人数" placeholder="请输入学生人数"/> 
                  </div> 
                  <div class="input-icon fl" id="total_student-icon"></div>
                  <div class="input-error fl" id="total_student-error"></div>
              </div> 
              <div class="form-default_element form-inpt"> 
                  <div class="loan-label fl">＊您的学校有多少教职工</div>
                  <div class="loan-input fl">  
                         <input autocomplete="off" value="{%$data.edit.staff%}" type="number" name="staff" data-text="教职工人数" placeholder="请输入教职工人数"/> 
                  </div> 
                  <div class="input-icon fl" id="staff-icon"></div>
                  <div class="input-error fl" id="staff-error"></div>
              </div> 
              <div class="form-default_element form-inpt"> 
                  <div class="loan-label fl">＊您已开了几所分校</div>
                  <div class="loan-input fl">  
                         <input autocomplete="off" value="{%$data.edit.branch_school%}" type="text" name="branch_school" data-text="分校数量" placeholder="请输入分校数量" /> 
                  </div> 
                  <div class="input-icon fl" id="branch_school-icon"></div>
                  <div class="input-error fl" id="branch_school-error"></div>
              </div> 
              <div class="form-default_element form-inpt">
                  <div class="loan-label fl" style="line-height: 20px;    height: 60px;">
                        ＊兴教贷需要您的个人无限<br/>
                        连带责任担保，除了您以外<br/>
                       是否可以提供更多的担保人<br/>
                 </div>
                  <div class="loan-select fl">
                        <select class="select_hide" id="select-guarantee_count" data-text="担保人">
                          {%foreach $data.guarantee as $key=>$value%}
                          <option value="{%$key%}" {%if $key == $data.edit.guarantee_count%}selected{%/if%}>{%$value%} 人</option>
                          {%/foreach%}
                        </select> 
                  </div>
                  <div class="input-icon fl" id="ismoreguarantee-icon"></div>
                  <div class="input-error fl" id="ismoreguarantee-error"></div>
              </div>
               <div class="form-default_element form-inpt">
                   <div class="loan-label fl">＊您的贷款使用用途是</div>
                   <div class="loan-select fl">  
                        <select class="select_hide" id="select-purpose" data-text="贷款用途">
                              <option value="">选择一项</option>
                              {%foreach $data.purpose as $key=>$value%}
                              <option value="{%$key%}" {%if $key == $data.edit.purpose%}selected{%/if%}>{%$value%}</option>
                              {%/foreach%}
                        </select>
                   </div>
                   <div class="input-icon fl" id="purpose-icon"></div>
                   <div class="input-error fl" id="purpose-error"></div>
                </div> 
                 <div class="line"></div>
                <div class="title color-green fl"> 
                    学校股权结构  
                     <div class="f16 color-6" style="  margin-left: 40px;line-height:50px;">您及所有占20%以上股份的股东</div>
                </div> 
                <table cellspacing="0" cellpadding="0"  class="apply-stock fl">
                    <tbody class="stock-list"> 
                      {%foreach $data.edit.stock as $key=>$item%}
                      {%assign var="total" value=$item.weight+$total%}
                          <tr weight="{%$item.weight%}">
                            <td>{%$item.name%}</td><td class="tr"><span class="weight">{%$item.weight%}</span>%</td>
                            <td class="tc"><i class="iconfont icon-delete del-stock"></i></td>
                          </tr>
                       {%/foreach%}  
                    </tbody>  
                </table> 
               <div class="form-default_element form-inpt" style="margin-bottom: 5px;">
                      <div class="loan-label fl" style="width: 30px;"> </div>
                      <div class="loan-input stock-input fl">
                          <input autocomplete="off" type="text" name="name" data-text="股东姓名" placeholder=""/>  
                      </div> 
                     <div class="loan-input stock-input stock-bai fl">
                        <input autocomplete="off" type="text" name="weight" data-text="百分比" class=""/>  
                         <span class="dis-block fr">%</span>
                     </div> 
                      <a class="loan-btn add-stock fl">再添加一位股东</a>
                      <span class="lh40">共<span class="stock-total">{%$total%}</span>%</span>  
                </div>
                <div class="form-default_element">
                   <div class="loan-label fl" style="width: 30px;"> </div>
                   <div class="color-red fl" id="error-box">  
                        
                   </div>
                </div>  
                <div class="form-default_element form-inpt">
                   <div class="loan-label fl"  style="width: 200px;"> </div> 
                   <a class="loan-btn loan-submit fl">下一步</a> 
                </div>    
        </div>
        <div class="right">
             {%include file='../../../views/common/loaninfo.phtml' type="2"%}
        </div>
       
    </div>
</div> 
{%/block%}