this is school page step3



<?php
	array(
        'address'        => '...', //学校地址
        'totalStudent'  => '345', //您的学校有多少学生？
        'staff'          => '32', //您的学校有多少教职工？
        'purpose'        => '1', //您的贷款使用用途是？
        'guaranteeCount'=> '1', //兴教贷需要您的个人无限连带责任担保，除了您以外是否可以提供更多的担保人
        'branch_school'  => '2',  //您已开了几所分校？
        'school_stock'   => array(   //股权分配是个多值字段
        	array(
        		'name'   => 'guojinli',
        		'weight' => '40.5',
        	),
        	array(
        		'name'   => 'another',
        		'weight' => '20.5',
        	)
        )
	);
?>