{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/my/success/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['my/success/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="success">
    <div class="container">
        <div class="kaitong-box" id="success-id">
            <div class="changephone-box">
                {%if $data.status%}
                <div class="success-pic"></div>
                <div class="success-text email-box">{%$data.desc%}</div>
                {%else%}
                <div class="success-pic error-pic"></div>
                <div class="success-text email-box success-font color-red">{%$data.desc%}</div>
                {%/if%}
                <div class="success-box-time">
                    <span class="timer-span" id="time-span">6秒后自动跳转至</span>&nbsp;
                    <a class="success-link" href="{%$data.backurl%}">{%$data.backname%}</a>
                </div>
            </div>

        </div>
    </div>
</div>
{%/block%}