{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="/src/setting/email/index.less" />
{%/block%}

{%block name="script"%}
<script>
    require(['setting/email/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="login">
    <div class="container">
        <div class="changephone" id="checkemial">
            <div class="changephone-top">
                {%if $status == 1%}
                <div class="changephone-box">
                    <div class="success-pic"></div>
                    <div class="success-text email-box success-font">投标成功</div>
                </div>
                {%else%}
                <div class="changephone-box">
                    <div class="success-pic error-pic"></div>
                    <div class="success-text email-box success-font color-red">投标失败</div>
                </div>
                {%/if%}
            </div>

        </div>
    </div>
</div>

{%/block%}