this is person page step 4

array(
    'certificate'    => '身份证号码', //您的身份证号码
    'houseType'      => '住房类型',   //您目前的住房类型
    'detailAddress'  => '详细地址', //您的住房详细地址
    'cellphone'      => '15810234069',		//您的手机号码
    'telephone'      => '010-7342732',	//您的固定电话
    'cash'           => '1',			//您的现金存款账户余额
    'stock'          => '1',		//您的股票、债券等其他有价证券资产
    'criminal'       => '1',		//您是否有犯罪记录？
    'lawsuit'        => '1',		//您是否有未决诉讼
);