this is basic page step2

<?php
	array(
        'type'           => '2',  //学校类型
        'nature'         => '4',  //学校主体性质
        'province'       => '1',	//省
        'city'           => '2400', //市
        'schoolSource'   => '2',   //从哪里了解到我们
        'year'           => '2013', //建校时间
        'incomeYear'     => '1', //年收入是否超过¥5,000,000
        'profit'         => '1', //最近一年是否盈利
        'otherBusiness'  => '1', //除了本学校外，您是否还经营房地产、钢铁、采矿等类型业务
	);
?>