 {%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/apply/basic/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['apply/basic/index'], function (main) {
        main.init({%$data.minmax.min%},{%$data.minmax.max%});  
    });   
</script>
{%/block%}

{%block name="content"%}
<style type="text/css" media="all">
    
</style>
<div class="box1" >
    <div class="container container2 step">
     <div class="container">
       {%include file='../../../views/common/loaninfo.phtml' type="1" current="2"%}
        <div class="title">
             <i class="iconfont icon-step2"></i>
             <span>贷款资格评估</span>
        </div>
    </div>
    </div> 
</div>
<div class="box2 loan">
    <div class="container">
        <div class="left"> 
                <div class="title"> 
                    您申请的学校信息已被兴教贷收录，可快速审核；<br/>
                    请您仔细填写后续信息。  
                </div> 
              <div class="form-default_element form-inpt">
                  <div class="loan-label fl">＊学校地区</div>
                  <div class="loan-select loan-select-addr fl">  
                        <select class="select_hide" id="select-province"  data-text="省份">
                          <option value="">选择省份</option>
                          {%foreach $data.province as $key=>$item%}
                          <option value="{%$key%}">{%$item%}</option>
                          {%/foreach%} 
                        </select> 
                  </div>
                  <div class="loan-select loan-select-addr fl" style="margin-left: 6px;">  
                        <select class="select_hide" id="select-city" data-text="城市">
                          <option value="">选择城市</option>
                            {%foreach $data.city as $key=>$item%} 
                              {%foreach $item as $k=>$v%}
                               <option value="{%$v['id']%}" pid="{%$key%}" disabled="">{%$v['name']%}</option> 
                              {%/foreach%} 
                            {%/foreach%} 
                        </select>  
                  </div>
                  <div class="input-icon fl" id="city-icon"></div>
                  <div class="input-error fl" id="city-error">目前仅开通北京、广西地区</div>
              </div> 
              <div class="form-default_element form-inpt">
                  <div class="loan-label fl">＊学校类型</div>
                  <div class="loan-select fl">  
                        <select class="select_hide" id="select-type" data-text="学校类型">
                          <option value="" >选择一项</option> 
                          {%foreach $data.school_type as $key=>$item%}
                          <option value="{%$key%}">{%$item%}</option>
                          {%/foreach%}
                        </select> 
                  </div>
                  <div class="input-icon fl" id="type-icon"></div>
                  <div class="input-error fl" id="type-error"></div>
              </div>
               <div class="form-default_element form-inpt">
                   <div class="loan-label fl">＊建校时间</div>
                   <div class="loan-select fl">  
                        <select class="select_hide" id="select-year"  data-text="建校时间">
                              <option value="">选择一项</option>
                              {%foreach $data.year as $key=>$item%}
                              <option value="{%$item%}">{%$item%}</option>
                              {%/foreach%}
                        </select>
                   </div>
                   <div class="input-icon fl" id="year-icon"></div>
                   <div class="input-error fl" id="year-error"></div>
                </div> 
                <div class="form-default_element form-inpt">
                      <div class="loan-label fl" style="line-height: 20px;">
                        年收入是否<br/>超过 <span class="data-money"> </span> 
                      </div> 
                     <div class="loan-radio fl">
                           <div class="radiobox">
                                <input type="radio" id="is_annual_income-1" name="is_annual_income" value="1" checked=""/>
                                 <label for="is_annual_income-1">是</label>
                            </div>
                            <div class="radiobox">
                                <input type="radio" id="is_annual_income-2" name="is_annual_income" value="0" />
                                 <label for="is_annual_income-2">否</label>
                             </div> 
                      </div>
                      <div class="input-icon fl" id="password-icon"></div>
                      <div class="input-error fl" id="password-error"></div>
                </div>
                <div class="form-default_element form-inpt">
                      <div class="loan-label fl" style="line-height: 20px;">
                         最近一年<br/>是否盈利
                      </div> 
                     <div class="loan-radio fl">
                            <div class="radiobox">
                                <input type="radio" id="is_profit-1" name="is_profit" value="1" checked=""/>
                                 <label for="is_profit-1">是</label>
                            </div>
                            <div class="radiobox">
                                 <input type="radio" id="is_profit-2" name="is_profit" value="0" />
                                 <label for="is_profit-2">否</label>
                             </div> 
                      </div>
                      <div class="input-icon fl" id="password-icon"></div>
                      <div class="input-error fl" id="password-error"></div>
                </div>
                <div class="form-default_element form-inpt">
                      <div class="loan-label fl" style="line-height: 20px;  height: 60px;"> 
                        除了本学校外，您是否<br/>还经营房地产、钢铁、采矿<br/>等类型业务
                      </div> 
                     <div class="loan-radio fl">
                            <div class="radiobox">
                                <input type="radio" id="is_other_business-1" name="is_other_business" value="1" checked=""/>
                                 <label for="is_other_business-1">是</label>
                            </div>
                            <div class="radiobox">
                                <input type="radio" id="is_other_business-2" name="is_other_business" value="0" />
                                 <label for="is_other_business-2">否</label>
                             </div> 
                      </div>
                      <div class="input-icon fl" id="password-icon"></div>
                      <div class="input-error fl" id="password-error"></div>
                </div>
                <div class="form-default_element form-inpt">
                      <div class="loan-label fl" >
                         学校主体性质
                      </div> 
                      <div class="loan-select fl">  
                         <select class="select_hide" id="select-nature" data-text="学校主体性质">
                              <option value="">选择一项</option>
                              {%foreach $data.nature as $key=>$item%}
                              <option value="{%$key%}">{%$item%}</option>
                              {%/foreach%}
                         </select>
                      </div>
                      <div class="input-icon fl" id="nature-icon"></div>
                      <div class="input-error fl" id="nature-error"></div>
                </div>
                <div class="line"></div>
                 <div class="form-default_element form-inpt">
                      <div class="loan-label fl" >
                         您从哪里了解到我们
                      </div> 
                      <div class="loan-select fl">  
                         <select class="select_hide" id="select-school_source" data-text="了解渠道">
                              <option value="">选择一项</option>
                              {%foreach $data.school_source as $key=>$item%}
                              <option value="{%$key%}">{%$item%}</option>
                              {%/foreach%}
                         </select>
                      </div>
                      <div class="input-icon fl" id="school_source-icon"></div>
                      <div class="input-error fl" id="school_source-error"></div>
                </div>
                <div class="form-default_element form-inpt">
                   <div class="loan-label fl"> </div>
                    
                        <a class="loan-btn loan-submit fl">提交评估</a>
                    
                </div> 
                <div class="form-default_element">
                   <div class="loan-label fl"> </div>
                   <div class="color-red fl" id="error-box">  
                        
                   </div>
                </div>   
        </div>
        <div class="right">
             {%include file='../../../views/common/loaninfo.phtml' type="2"%}
        </div>
       
    </div>
</div> 
{%/block%}