<div class="finish-nav">
    <div class="finish-nav-top">
        <div class="finish-nav-top-user">Hi,xxx</div>
        <div class="finish-top-icon">
            <a href="###" class="top-icon-link user"></a>
            <a href="{%$webroot%}/account/edit/chphone" class="top-icon-link phone current"></a>
            <a href="###" class="top-icon-link other"></a>
        </div>
        <div class="finish-top-schedule">
            <div class="top-schedule-internal"></div>
        </div>
        <div class="finish-top-grade">
            <span>安全等级</span>
            <a href="###" class="grade-high">低</a>
            <a href="###" class="grade-high">[提升]</a>
        </div>
    </div>
    <ul class="finish-nav-item">
        <li class="finish-nav-item-list">
            <a href="{%$webroot%}/account/overview/index" class="finish-nav-item-link all {%if $current == '1'%}current{%/if%}">账户总览</a>
        </li>
        <li class="finish-nav-item-list">
            <a href="{%$webroot%}/account/invest/index" class="finish-nav-item-link mymoney {%if $current == '2'%}current{%/if%}">我的投资</a>
        </li>
        <li class="finish-nav-item-list">
            <a href="###" class="finish-nav-item-link pay {%if $current == '3'%}current{%/if%}">充值提现</a>
        </li>
        <li class="finish-nav-item-list">
            <a href="{%$webroot%}/account/secure/index" class="finish-nav-item-link safe {%if $current == '4'%}current{%/if%}">安全中心</a>
        </li>
        <li class="finish-nav-item-list">
            <a href="###" class="finish-nav-item-link jiangli {%if $current == '5'%}current{%/if%}">邀请奖励</a>
        </li>
        <li class="finish-nav-item-list">
            <a href="###" class="finish-nav-item-link mynews {%if $current == '6'%}current{%/if%}">我的消息</a>
        </li>
    </ul>
</div>