{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                             Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
            用户列表 
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">用户列表</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <form class="form-horizontal" role="form" method="post" action="/admin/user">
            <div class="form-group">
                 <label for="username" class="col-sm-2 control-label">输入用户名或手机号</label>
                 <div class="col-sm-4">
                      <input type="text" class="form-control" name="username" id="username" placeholder="用户名|手机号">
                 </div>
                 <div class="form-group">
                       <input type="submit" class="btn btn-default" value="查询"/>
                       <a href="/admin/user/count"><input type="button" class="btn btn-default" value="查看统计数据"/></a>
                 </div>
            </div>
            </form>
            <div class="row-fluid">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>用户名</th>
                            <th>真实姓名</th>
                            <th>汇付号</th>
                            <th>手机号</th>
                            <th>邮箱</th>
                            <th>最近登录时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%foreach from=$arrUser key=i item=user%}
                        <tr>
                            <td>{%$user.userid%}</td>
                            <td>{%$user.name%}</td>
                            <td>{%$user.realname%}</td>
                            <td>{%$user.huifuid%}</td>
                            <td>{%$user.phone%}</td>
                            <td>{%$user.email%}</td>
                            <td>{%date("Y-m-d H:i:s",$user.login_time)%}</td>
                            <td><a href="/admin/user?userid={%$user.userid%}">删除该用户</a></td>
                        </tr>
                        {%/foreach%}
                    </tbody>
                </table>
            </div>
         <div id="setpage"  style = "text-align: center;font-size:17px;margin:0 auto;"></div> 
        </div>
    </div>
    <script src = "{%$feroot%}s/global/scripts/pageCut.js"></script>
    <script>
    cpage = {%$page%}; 
    totalpage = {%$pageall%}; 
    setpage(cpage,totalpage);
    </script>
{%/block%}
