{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                             Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
            添加用户 <small>管理员代开通</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">个人用户添加</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div class="row-fluid">
                <!-- BEGIN FORM-->
                <form class="form-horizontal" role="form" method="post" action="" enctype="multipart/form-data">
                    {%if $error_msg%}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <strong>Warning! </strong> {%$error_msg%}
                    </div>
                    {%/if%}
                    {%if $smarty.get.userid%}
                    {%else%}                  
                    <div class="form-group">
                        <label for="username" class="col-sm-2 control-label">用户名</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="username" id="username" placeholder="设置用户名">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password" class="col-sm-2 control-label">登录密码</label>
                        <div class="col-sm-4">
                            <input type="password" class="form-control" name="password" id="password" placeholder="设置登录密码">
                        </div>
                    </div>
                     <div class="form-group">
                        <label for="phone" class="col-sm-2 control-label">手机号</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="phone" id="phone" placeholder="设置手机号">
                        </div>
                     </div>   
                     
                     <div class="form-group">
                        <label class="col-sm-2 control-label">用户类型</label>
                        <div class="col-sm-4">
                            <label class="radio-inline">
                               <input type="radio" name="type" id="pri" value="1" style="padding-top:0">个人用户 
                            </label>  
                            <label class="radio-inline">                                                                  
                               <input type="radio" name="type" id="corp" value="2" >企业用户  
                            </label>      
                            <label class="radio-inline">                                                            
                               <input type="radio" name="type" id="angel" value="4" checked>天使  
                            </label> 
                        </div>
                     </div>
                     {%/if%}
                     <div class="form-group">
                        <label for="file" class="col-sm-2 control-label">上传图像</label>
                        <div class="col-sm-4">
                            <!--  <input type="file" class="form-control" name="file" id="file" placeholder="上传图像"  onchange="UpPic()">-->
                            <input type="file"  name="file" class="form-control" id="file">
                        </div>
                     </div>
                     <div><input type="hidden" name="add" value="{%$smarty.get.userid%}"></div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">提交</button>
                            <!-- <input type="buttom" class="btn btn-default" value="提交" onclick="/admin/user/reg" /> --> 
                        </div>
                    </div>
                </form>
                <!-- END FORM-->  
            </div>

        </div>
    </div>
      <script type="text/javascript">
    //创建XMLHttpRequest
    function createXmlHttpRequest(){
        if(window.XMLHttpRequest){
            return new XMLHttpRequest();
        }else{
            return new ActiveXObject("Microsoft.XMLHTTP");
        }
    }
    //ajax回调函数
    function finish(){
        if(XmlHttpRequest.readyState == 4&& XmlHttpRequest.status == 200){
            var result = XmlHttpRequest.responseText;
            if(result =="true"){
                alert("");
            }else{
                alert(result);
            }
        }
    }
    
    //当用户先择了标记时调用该方法
    function UpPic(){
    	var fileObj = document.getElementById("file").files[0];

        var url="/Upload/pic";
        var form = new FormData();
        form.append("file", fileObj);    
        //调用方法创建XMLHttpRequest对象
        XmlHttpRequest = createXmlHttpRequest();       
        //设置回调函数
        XmlHttpRequest.onreadystatechange=finish;
        //初始化xmlhttprequest
        XmlHttpRequest.open("POST",url,true);
        XmlHttpRequest.setRequestHeader("Content-Type","multipart/form-data");
        //发送请求
        XmlHttpRequest.onload = function () {
            alert(fileObj);
        };
        XmlHttpRequest.send(form);
    }   
    </script>
{%/block%}