{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/company/contact/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['company/common/common'], function(main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="company-nav"> 
	   <div class="company-navbar">  
	      <div class="container"> 
	         {%include file="common/menu.phtml" current="4"%}
	      </div>
	   </div>
</div>
<div class="container main-container">

<div class="container container2"> 
   <div class="company-box1"> 
   </div>
   <div class="company-box2">
       <ul class="company-link">  
	        <li>
				<img alt="公司总部" src="{%$feroot%}/company/contact/img/link_add.png">
				<br/>
				<strong>公司总部</strong>
				<span>北京市海淀区苏州街20号银丰大厦907</span>
			</li>
			<li>
				<img alt="客服热线" src="{%$feroot%}/company/contact/img/link_num.png"> 
				<br/>
				<strong>客服热线</strong>
				<span>400-016-2526<br/>周一至周五 9:00-18:00
				</span>
			</li>
			<li>
				<img alt="联络邮箱" src="{%$feroot%}/company/contact/img/link_mail.png"> 
				<br/> 
				<strong>联络邮箱</strong>
				<span>
				   kefu@xingjiaodai.com（客服）<br/>
				   biz@xingjiaodai.com（商务合作） 
				</span>
			</li>
	   </ul>
       <ul class="company-link2">  
          <li>
				<img alt="微信公众号" src="{%$feroot%}/company/contact/img/link_weixin.png">
				<br/> 
				<span>关注微信公众号</span>
			</li>
			<li>
				<img alt="兴教贷微博" src="{%$feroot%}/company/contact/img/link_weibo.png"> 
				<br/>
				<span>关注兴教贷微博</span>
			</li>
       </ul>
   </div> 
   <div  class="company-box3"> 
   </div>

   
</div>
</div>




{%/block%}