 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   <!--  <meta name="viewport"
              content="width=device-width,
               height=device-height,
               inital-scale=1.0,
               maximum-scale=1.0,
               user-scalable=no;"/> -->
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui" />
  
    <meta name="format-detection" content="telephone=no, email=no" />
    <title>
     {%if $title%}
         {%$title%}
     {%else%}  
                       兴教贷 - 专注教育领域的互联网金融投融资理财平台             
     {%/if%}
     </title> 
 
    <link rel="icon" href="{%$webroot%}/favicon.ico" type="image/x-icon" />

    <script src="{%$feroot%}/common/extra/esl.js"></script>

    <script>
        require.config({
            'baseUrl': '{%$feroot%}',
            'paths': {
            },
            'packages': [
                {
                    'name': 'echarts',
                    'location': '../dep/echarts/2.1.9/asset',
                    'main': 'echarts'
                },
                {
                    'name': 'est',
                    'location': '../dep/est/1.3.0/asset'
                },
                {
                    'name': 'etpl',
                    'location': '../dep/etpl/3.0.0/asset',
                    'main': 'main'
                },
                {
                    'name': 'jquery',
                    'location': '../dep/jquery/1.9.1/asset',
                    'main': 'jquery.min'
                },
                {
                    'name': 'moment',
                    'location': '../dep/moment/2.7.0/asset',
                    'main': 'moment'
                },
                {
                    'name': 'saber-emitter',
                    'location': '../dep/saber-emitter/1.0.0/asset',
                    'main': 'emitter'
                },
                {
                    'name': 'zrender',
                    'location': '../dep/zrender/2.0.6/asset',
                    'main': 'zrender'
                } 
            ]
        });

        window.GLOBAL = {
            token: '{%$token%}'
        };
    </script>
