<div class="header">
    <div class="container">
        <div class="header-left">
            <span class="header-left-phone">客服：400-888-6666</span>
            <span class="header-left-time">(工作时间：9：00 - 21：00)</span>
                <span class="header-left-attention">
                    <span class="attention-span">关注我们：</span>
                    <a class="attention-me xinlang" href="###">
                        <div class="xinlang-erweima">
                            <div class="triangle-top"></div>
                            <div class="triangle-bottom"></div>
                        </div>
                    </a>
                    <a class="attention-me weixin" href="###">
                        <div class="xinlang-erweima">
                            <div class="triangle-top"></div>
                            <div class="triangle-bottom"></div>
                        </div>
                    </a>
                </span>
        </div>
        <div class="header-right">
            <div class="header-right-default">
                <a href="{%$webroot%}/user/regist/index" class="default-fastlogin">快速注册</a>
                <a class="default-login" href="{%$webroot%}/user/login/index">登录</a>
            </div>
            <div class="header-right-login">
                <span class="default-fastlogin">您好，XXX</span>
                <a class="default-login" href="###">退出</a>
            </div>
        </div>
    </div>
</div>
<div class="nav">
    <div class="container">
        <a href="###" class="logo"><img width="100%" height="100%" src="{%$feroot%}/common/img/logo.png" /></a>
        <ul class="nav-item">
            <li class="nav-item-list">
                <a href="###" class="nav-item-link">我来投资</a>
            </li>
            <li class="nav-item-list">
                <a href="###" class="nav-item-link">我要借款</a>
            </li>
            <li class="nav-item-list">
                <a href="###" class="nav-item-link">安全保障</a>
            </li>
            <li class="nav-item-list">
                <a href="###" class="nav-item-link">新手指引</a>
            </li>
            <li class="nav-item-list last">
                <a href="###" class="nav-item-link">关于我们</a>
            </li>
        </ul>
        <a href="###" class="nav-myaccount">我的账户</a>
    </div>
</div>