{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="/src/my/account/index.less" />
{%/block%}

{%block name="script"%}
<script>
    require(['my/account/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="finish">
    <div class="container finish-bg-color">
        <div class="finish-nav">
            <div class="finish-nav-top">
                <div class="finish-nav-top-user">Hi,xxx</div>
                <div class="finish-top-icon">
                    <a href="###" class="top-icon-link user"></a>
                    <a href="###" class="top-icon-link phone current"></a>
                    <a href="###" class="top-icon-link other"></a>
                </div>
                <div class="finish-top-schedule">
                    <div class="top-schedule-internal"></div>
                </div>
                <div class="finish-top-grade">
                    <span>安全等级</span>
                    <a href="###" class="grade-high">低</a>
                    <a href="###" class="grade-high">[提升]</a>
                </div>
            </div>
            <ul class="finish-nav-item">
                <li class="finish-nav-item-list">
                    <a href="###" class="finish-nav-item-link all">账户总览</a>
                </li>
                <li class="finish-nav-item-list">
                    <a href="###" class="finish-nav-item-link mymoney">我的投资</a>
                </li>
                <li class="finish-nav-item-list">
                    <a href="###" class="finish-nav-item-link current pay">充值提现</a>
                </li>
                <li class="finish-nav-item-list">
                    <a href="###" class="finish-nav-item-link safe">安全中心</a>
                </li>
                <li class="finish-nav-item-list">
                    <a href="###" class="finish-nav-item-link jiangli">邀请奖励</a>
                </li>
                <li class="finish-nav-item-list">
                    <a href="###" class="finish-nav-item-link mynews">我的消息</a>
                </li>
            </ul>
        </div>
        <div class="finish-main">
            <div class="finish-main-title">账户总览</div>
            <div class="all-account-box">
                <div class="all-box-income">
                    <div class="all-box-income-title">
                        <p class="all-income-title-price">￥{%$totalProfit%}</p>
                        <p class="all-income-title-name">累计收益</p>
                    </div>
                    <div class="all-box-income-class">
                        <div class="all-class-money">
                            <p class="all-class-money-price">￥{%$totalInvest%}</p>
                            <p class="all-class-money-price">累计投资</p>
                        </div>
                        <div class="all-class-money">
                            <p class="all-class-money-price">￥{%$reposPrifit%}</p>
                            <p class="all-class-money-price">待收收益</p>
                        </div>
                        <div class="all-class-money">
                            <p class="all-class-money-price">￥{%$reposPrincipal%}</p>
                            <p class="all-class-money-price">待收本金</p>
                        </div>
                    </div>
                </div>
                <div class="all-box-pay">
                    <div class="all-box-pay-top">可用余额<span>￥{%$avlBal%}</span></div>
                    <div class="all-box-pay-top">冻结金额<span>￥{%$frzBal%}</span></div>
                    <div class="all-box-pay-top">资产总计<span><a href="###" class="all-pay-help"></a>￥{%$acctBal%}</span></div>
                    <a href="{%$rechargeurl%}" class="all-box-pay-link">充值</a>
                </div>
            </div>
            <div class="all-account-box-dredge">
                <div class="all-box-dredge-name">尚未开通资金托管账户</div>
                <a href="###" class="all-box-dredge-link">立即开通</a>
            </div>
            <div id="all-account-line" class="all-account-box-dredge quxian">
                加载中
            </div>
        </div>
    </div>
</div>

{%/block%}