{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="/src/my/success/index.less" />
{%/block%}

{%block name="script"%}
<script>
    require(['my/success/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}

<div class="success">
    <div class="container">
        <div class="kaitong-box" id="success-id">
            <div class="changephone-box">
                <div class="success-pic"></div>
                <div class="success-text email-box">充值成功,您的充值金额为 <span class="email-box-span color-red">100</span>元</div>
                <div class="success-box-time">
                    <span class="timer-span" id="time-span">6秒后自动跳转至</span>&nbsp;
                    <a class="success-link" href="/account/overview/index">我的账户</a>
                </div>
            </div>

        </div>
    </div>
</div>
{%/block%}