{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/setting/login/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['setting/login/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="login">
    <div class="container">
        <div class="login-left">
            <div class="login-left-box">
                <div class="login-left-title">登录兴教贷</div>
                <div id="login-error" class="login-error"></div>
                <div class="login-username">
                    <input autocomplete="off" class="login-input" id="login-user" type="text" />
                    <label class="user-lable" for="login-user">用户名/手机/邮箱登录</label>
                    <!--<div class="username-error">用户名错误</div>-->
                </div>
                <div class="login-username">
                    <input autocomplete="off" class="login-input" id="login-pwd" type="password" />
                    <label class="user-lable" for="login-pwd">密码</label>
                    <!--<div class="username-error">密码错误</div>-->
                </div>
                {%if isset($url)%}
                <div class="login-username">
                {%else%}
                <div class="login-username login-display-none">
                {%/if%}
                    <input autocomplete="off" class="login-input testing" id="login-testing" type="text" />
                    <label class="user-lable" for="login-testing">验证码</label>
                    <a href="###" class="login-username-testing">
                        <img id="login-img-url" src="{%$url%}" width="162" height="35" />
                    </a>
                    <!--<div class="login-username-testing-box" id="testing-wait">10</div>-->
                    <div class="username-error yanzma" id="login-testing-error">
                    </div>
                </div>
                <div class="login-op">
                    <a href="{%$webroot%}/user/modifypwd" class="login-forget">忘记密码?</a>
                </div>
                <a href="###" class="login-fastlogin">快速登录</a>
                <div class="login-thirdlogin">
                    <span class="login-third-free">或<a href="{%$webroot%}/user/regist">免费注册</a></span>
                    <span class="login-third-tx">您也可以使用第三方账号登录</span>
                    <a href="{%$webroot%}/user/login/auth?type=qq" class="login-third-qq qq"></a>

                </div>

            </div>
        </div>
        <div class="login-right">
            <a class="login-right-linkleft left"></a>
            <div class="login-right-box">
                <ul class="login-item">
                    <li class="login-item-list">
                        <div class="introduce-list-logo baozhang"></div>
                        <div class="introduce-list-title">全方位投资保障</div>
                        <div class="introduce-list-title">安全稳健的互联网投机理财</div>
                        <a class="introduce-list-link" href="###">
                            <p class="introduce-list-link-text">360度实地尽调、本金保障</p>
                            <p class="introduce-list-link-text">第三方资金托管</p>
                        </a>
                    </li>
                    <li class="login-item-list">
                        <div class="introduce-list-logo highincome"></div>
                        <div class="introduce-list-title">低门槛高收入</div>
                        <a class="introduce-list-link" href="###">
                            <p class="introduce-list-link-text">互联网理财100元起投</p>
                            <p class="introduce-list-link-text">超过银行存款利率30倍</p>
                        </a>
                    </li>
                    <li class="login-item-list">
                        <div class="introduce-list-logo zhuanzhu"></div>
                        <div class="introduce-list-title">专注教育行业</div>
                        <a class="introduce-list-link" href="###">
                            <p class="introduce-list-link-text">深挖教育行业特性</p>
                            <p class="introduce-list-link-text">最权威教育行业评估体系</p>
                        </a>
                    </li>

                </ul>
            </div>
            <a class="login-right-linkleft right last"></a>
        </div>
    </div>
</div>
{%/block%}
