{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/my/angel/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['my/angel/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="finish">
    <div class="container finish-bg-color">
        {%include file='../../../views/common/nav.phtml' current="9"%}
        <div class="finish-main">
            <div class="finish-main-title">爱心天使</div>
            <div class="finish-main-tip f14 lh24 color-6">
                邀请您投资过的天使会显示在下方，如果您想添加某一位天使也可通过输入天使的专属码来添加到您的账户中来，方便您下次直接投资。
            </div> 
            <div id="my-angel-list" class="my-angel-list"> 
                  <div class="xjd-loading">&nbsp;</div>
             <!--     <ul> 
                 <li class="my-angel-item add-angel-li">
                   <span class="add-angel">+</span>
                   <span class="dis-block tl"> 
                     输入天使码：<input type="text" name="angelcode" class="add-angel-input" />
                     <a class="common-a-btn add-angel-btn">确定</a>
                   </span>
                  <span class="add-error color-red f12 tl dis-block"></span>
               </li>
                             </ul>  -->
            </div> 
            <div id="my-angel-pager" class="my-invest-pager"></div>
        </div>
    </div>
</div>
{%/block%}