{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/project/detail/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['project/detail/index'], function (main) {
        main.init({
            id: '{%$data.id%}',
            amountRest: '{%$data.amount_rest%}',
            userAmount: '{%if isset($user.amount)%}{%$user.amount%}{%else%}0.00{%/if%}',
            interest: +'{%$data.interest%}',
            days: +'{%$data.days%}',
            sTime: +'{%$data.create_time%}',
            eTime: +'{%$data.deadline%}',
            fullTime: +'{%$full_time%}'
        });
    });
</script>
{%/block%}

{%block name="content"%}
{%assign var=mapType value=['实地认证'=>'shidi', '营业执照'=>'yingye', '税务登记证'=>'shuiwu', '银行开户许可证'=>'bank',
'组织机构代码证'=>'zuzhi', '征信报告'=>'zhengxin', '抵押手续'=>'diya', '身份证'=>'shenfen', '户口本'=>'hukou',
'结婚证'=>'jiehun', '房产证'=>'fangchan', '行驶证'=>'xingshi', '登记证书'=>'yingye']%}
<div class="details">
    <div class="container">
        <div class="detail-left">
            <div class="detail-left-title title-icon">
                <a href="{%$webroot%}/invest" class="left-title-link">我来投资</a>
                <span class="left-title-greater">&gt;</span>
                <a href="{%$webroot%}/invest" class="left-title-link">项目列表</a>
                <span class="left-title-greater">&gt;</span>
                <span class="left-title-link-span">项目详情</span>
            </div>
            {%if isset($error)%}
            <div class="chongzhi-error show">{%$error%}</div>
            {%/if%}
            <div class="project">
                <div class="project-box">
                    <div class="project-title">
                        <div class="project-title-name" title="{%$data.title%}">
                            {%if isset({%$data.level_name%})%}
                            <span class="grade-star level-{%$data.level_name%}"></span>
                            {%/if%}
                            {%$data.title%}
                        </div>
                        <div class="project-title-number">
                            <span>借款编号：</span>
                            <span>{%$data.id%}</span>
                        </div>
                    </div>
                    <div class="project-gaishu">
                        <div class="project-gaishu-top">
                            <div class="gaisu-top-rental">
                                <div class="gaishu-top-rental-icon rental">借款总额</div>
                                <div class="gaishu-top-rental-number">
                                    <span>￥</span>
                                    <span class="rental-number-big">{%$data.amount%}</span>
                                </div>
                            </div>
                            <div class="gaisu-top-rental">
                                <div class="gaishu-top-rental-icon lilv">借款年利率</div>
                                <div class="gaishu-top-rental-number">
                                    <span class="rental-number-big">{%$data.interest%}</span>
                                    <span>%</span>
                                </div>
                            </div>
                            <div class="gaisu-top-rental">
                                <div class="gaishu-top-rental-icon time">借款期限</div>
                                <div class="gaishu-top-rental-number">
                                    <span class="rental-number-big">{%$data.duration_day%}</span>
                                    <span>{%$data.duration_type%}</span>
                                </div>
                            </div>

                        </div>
                        <div class="project-gaishu-bottom">
                            <div class="gaishu-bottom-guard">
                                <div class="gaishu-guard-baozhang">
                                    <span class="span">保障方式：</span>
                                    <div class="baozhang-box">
                                        {%foreach $data.safemode as $key => $item%}
                                        <span class="baozhang-type benxi">{%$item%}</span>
                                        {%/foreach%}

                                    </div>

                                </div>
                                <div class="jindu-top">
                                    <span class="jindu-top-text">筹款进度：</span>
                                    <div class="jindu-top-tiao">
                                        <div class="jindu-tio-tiao-within" style="width: {%$data.percent%}%;"></div>
                                    </div>
                                    <span class="jindu-top-bai">
                                        <span class="jindu-top-bai-number">{%$data.percent%}</span>%
                                    </span>
                                </div>

                            </div>
                            <div class="gaishu-bottom-jindu">
                                <div class="gaishu-guard-baozhang">
                                    <span>还款方式：</span>
                                    <span class="baozhang-return">{%$data.refund_typename%}</span>
                                </div>
                                <div class="jindu-btm">
                                    <span class="jindu-top-text">已投标：</span><span>{%$data.invest_cnt%}人</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="project-time">
                        <span class="project-time-start">开始时间：{%$data.create_time|date_format:'%Y-%m-%d %H:%M'%}</span>
                        <span class="project-time-start">截止日期：{%$data.deadline|date_format:'%Y-%m-%d %H:%M'%}</span>
                    </div>
                </div>

                <div class="project-main project">
                    <div class="project-main-title">
                        <div class="main-title-box showproject current">项目详情</div>
                        <div class="main-title-box showfile">文件资料</div>
                        <div class="main-title-box showrecord">投资记录</div>
                    </div>
                    <div class="main-box-details showproject-main">
                        {%if isset($user.amount)%}
                        {%if !empty($data.private)%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">借款人信息</div>
                            <div class="main-detail-content">
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">姓名：</div>
                                        <div class="file-left-text">{%$data.private.showname%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">所处职位：</div>
                                        <div class="file-left-text">{%$data.private.job_title%}</div>
                                    </div>
                                    <!-- <div class="file-left-box">
                                        <div class="file-left-name">婚否：</div>
                                        <div class="file-left-text">{%if $data.private.marriage == 1%}是{%else%}否{%/if%}</div>
                                    </div> -->
                                </div>
                                <div class="file-enter">
                                    <!-- <div class="file-left-box">
                                        <div class="file-left-name">单位类别：</div>
                                        <div class="file-left-text">{%$data.private.company_type%}</div>
                                    </div> -->
                                    <div class="file-left-box">
                                        <div class="file-left-name">婚否：</div>
                                        <div class="file-left-text">{%if $data.private.marriage == 1%}是{%else%}否{%/if%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">年龄：</div>
                                        <div class="file-left-text">{%$data.private.age%} 岁</div>
                                    </div>
                                </div>
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">户口：</div>
                                        <div class="file-left-text">{%$data.private.account%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">年收入：</div>
                                        <div class="file-left-text">{%$data.private.income%}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {%/if%}
                        {%if !empty($data.company)%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">借款机构</div>
                            <div class="main-detail-content">
                                <div class="main-detail-content-left">
                                    <div class="left-box">
                                        <div class="content-left-name">借款机构：</div>
                                        <div class="content-left-text">{%$data.company.school%}</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">区域位置：</div>
                                        <div class="content-left-text">{%$data.company.area_name%}</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">资产总值：</div>
                                        <div class="content-left-text">{%$data.company.assets%}</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">教职工数量：</div>
                                        <div class="content-left-text">{%$data.company.employers%}+ 名</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">借款用途：</div>
                                        <div class="content-left-text">{%$data.content%}</div>
                                    </div>

                                </div>
                                <div class="main-detail-content-right">
                                    <div class="left-box">
                                        <div class="content-left-name">成立日期：</div>
                                        <div class="content-left-text right-text">{%$data.company.years%} 年</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">注册资金：</div>
                                        <div class="content-left-text right-text">{%$data.company.funds%}</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">学生数量：</div>
                                        <div class="content-left-text right-text">{%$data.company.students%}+ 名</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {%/if%}
                        {%if !empty($data.counter)%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">信用档案</div>
                            <div class="main-detail-content">
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">成功借款：</div>
                                        <div class="file-left-text">{%$data.counter.success%} 笔</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">还清笔数：</div>
                                        <div class="file-left-text">{%$data.counter.finished%} 笔</div>
                                    </div>
                                </div>
                                <div class="file-enter">
                                    <div class="file-left-box">
                                        <div class="file-left-name">授信额度：</div>
                                        <div class="file-left-text">{%$data.counter.limit%} 元</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">已还金额：</div>
                                        <div class="file-left-text">{%$data.counter.refund%} 元</div>
                                    </div>
                                </div>
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">累计借款：</div>
                                        <div class="file-left-text">{%$data.counter.total%} 元</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">待还本息：</div>
                                        <div class="file-left-text">{%$data.counter.rest%} 元</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {%/if%}
                        {%if !empty($data.guarantee)%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">担保人信息</div>
                            <div class="main-detail-content">
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">姓名：</div>
                                        <div class="file-left-text">{%$data.guarantee.name%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">所处职位：</div>
                                        <div class="file-left-text">{%$data.guarantee.job_title%}</div>
                                    </div>
                                    <!-- <div class="file-left-box">
                                        <div class="file-left-name">婚否：</div>
                                        <div class="file-left-text">{%if $data.guarantee.marriage == 1%}是{%else%}否{%/if%}</div>
                                    </div> -->
                                </div>
                                <div class="file-enter">
                                    <!-- <div class="file-left-box">
                                        <div class="file-left-name">单位类别：</div>
                                        <div class="file-left-text">{%$data.guarantee.company_type%}</div>
                                    </div> -->
                                    <div class="file-left-box">
                                        <div class="file-left-name">婚否：</div>
                                        <div class="file-left-text">{%if $data.guarantee.marriage == 1%}是{%else%}否{%/if%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">年龄：</div>
                                        <div class="file-left-text">{%$data.guarantee.age%}岁</div>
                                    </div>
                                </div>
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">户口：</div>
                                        <div class="file-left-text">{%$data.guarantee.account%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">年收入：</div>
                                        <div class="file-left-text">{%$data.guarantee.income%}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {%/if%}
                        {%if !empty($data.audit)%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">审核信息</div>
                            {%foreach $data.audit as $key => $item%}
                            <div class="renzheng-box">
                                <div class="renzheng-title">{%$key%}</div>
                                <div class="renzheng-box-main">
                                    {%foreach $item as $index => $temp%}
                                    <div class="renzheng-big-box">
                                        <div class="renzheng-box-main-box-pic {%$mapType[$temp.name]%}"></div>
                                        <div class="renzheng-box-main-box-name">{%$temp.name%}</div>
                                    </div>
                                    {%/foreach%}
                                </div>
                            </div>
                            {%/foreach%}
                        </div>
                        {%/if%}
                        {%if isset($data.audit_info)%}
                        <div class="details-main-box bor-btm">
                            <div class="main-box-detail-title">审核通过</div>
                            <div class="detail-pass">{%$data.audit_info%}</div>
                            <div class="detail-symbol"></div>
                        </div>
                        {%/if%}
                        {%else%}
                        <div class="detail-unlogin">
                            请 <a href="/user/login">登录</a> 或 <a href="/user/regist">注册</a> 后查看
                        </div>
                        {%/if%}
                    </div>
                    <div class="main-box-details showfile-main">
                        {%if isset($user.amount)%}
                        {%if !empty($data.attach['认证材料'])%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">认证材料</div>
                            <div class="main-detail-content">
                                <ul class="detail-item">
                                    {%foreach $data.attach['认证材料'] as $key => $item%}
                                    <li class="detail-item-list img-city">
                                        <img alt="{%$item.title%}" class="detail-item-list-img img-width" src="{%$item.thumb%}" />
                                        <p class="detail-item-p">{%$item.title%}</p>
                                    </li>
                                    {%/foreach%}
                                </ul>
                            </div>
                        </div>
                        {%/if%}
                        {%if !empty($data.attach['合同协议'])%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">合同协议</div>
                            <div class="main-detail-content">
                                <ul class="detail-item">
                                    {%foreach $data.attach['合同协议'] as $key => $item%}
                                    <li class="detail-item-list">
                                        <img alt="{%$item.title%}" class="detail-item-list-img" src="{%$item.thumb%}" />
                                        <p class="detail-item-p">{%$item.title%}</p>
                                    </li>
                                    {%/foreach%}
                                </ul>
                            </div>
                        </div>
                        {%/if%}
                        {%if !empty($data.attach['实地照片'])%}
                        <div class="details-main-box item-last">
                            <div class="main-box-detail-title">实地照片</div>
                            <div class="main-detail-content">
                                <ul class="detail-item">
                                    {%foreach $data.attach['实地照片'] as $key => $item%}
                                    <li class="detail-item-list img-city" style="margin-right:70px">
                                        <img alt="{%$item.title%}" style="width: 250px;height:180px;" class="detail-item-list-img" src="{%$item.thumb%}" />
                                        <p class="detail-item-p">{%$item.title%}</p>
                                    </li>
                                    {%/foreach%}
                                </ul>
                            </div>
                        </div>
                        {%/if%}
                        {%else%}
                        <div class="detail-unlogin">
                            请 <a href="/user/login">登录</a> 或 <a href="/user/regist">注册</a> 后查看
                        </div>
                        {%/if%}
                    </div>
                    <div class="main-box-details showrecord-main">
                        {%if isset($user.amount)%}
                        <div class="details-main-box">
                            <div class="main-box-detail-title">投资记录</div>
                            <div class="main-detail-content" id="toulist">
                            </div>
                        </div>
                        <div id="page"></div>
                        {%else%}
                        <div class="detail-unlogin">
                            请 <a href="/user/login">登录</a> 或 <a href="/user/regist">注册</a> 后查看
                        </div>
                        {%/if%}
                    </div>
                </div>
            </div>
        </div>
        <div class="detail-right">
            {%if $data.status == 3%}
            <div class="right-top right-bg-color">
                <div class="right-top-title">我来投资</div>
                {%if $data.fresh%}
                <div class="right-top-new"></div>
                {%/if%}
                <div class="right-box-top">
                    <div class="right-top2nd-title">已满标</div>
                    <div class="right-top2nd-box">满标时间：{%$data.full_time|date_format:'%Y-%m-%d %H:%M'%}</div>
                    <div class="right-top2nd-box">满标耗时：{%$data.expend_time%}</div>
                    <div class="right-top2nd-box">投标人数：{%$data.invest_cnt%}人</div>
                </div>
            </div>
            {%else if $data.status == 10%}
            <div class="right-top right-bg-color">
                <div class="right-top-title">我来投资</div>
                {%if $data.fresh%}
                <div class="right-top-new"></div>
                {%/if%}
                <div class="right-box-top">
                    <div style="width:200px;margin:20px" class="right-top2nd-title refund">即将开启</div>
                </div>
            </div>
            {%else if $data.status == 5%}
            <div class="right-top right-bg-color">
                <div class="right-top-title">我来投资</div>
                {%if $data.fresh%}
                <div class="right-top-new"></div>
                {%/if%}
                <div class="right-box-top">
                    <div class="right-top2nd-title refund">还款中</div>
                    <div class="right-top2nd-box">待还本息（元）: ￥{%$data.rest_total%}</div>
                    <div class="right-top2nd-box">剩余期数（月）: {%$data.left_month%}</div>
                    <div class="right-top2nd-box">下次合约还款日: {%$data.next_date|date_format:'%Y-%m-%d'%}</div>
                </div>
            </div>
            {%else if $data.status == 2%}
            <form id="invest-form" method="post" action="/invest/tender" class="right-top">
                <div class="right-top-title">我来投资</div>
                {%if $data.fresh%}
                <div class="right-top-new"></div>
                {%/if%}
                <div class="right-top-allmoney">
                    <div class="right-top-allmoney-money">可投金额：<span id="money-all">{%$data.amount_rest%}元</span></div>
                    <div class="right-top-allmoney-time">剩余时间：<span> </span></div>
                </div>
                <div class="right-top-ipt {%if !isset($user)%}disabled{%/if%}">
                    <input name="amount" maxlength="10" type="text" autocomplete="off" class="right-top-ipt-input" {%if !isset($user)%} disabled{%/if%} />
                    <input name="id" type="hidden" value="{%$data.id%}" />
                    <div class="chongzhi-right">预期收益：<span class="chongzhi-span">0.00</span></div>
                </div>
                <div id="chongzhi-error" class="chongzhi-error"></div>
                <div class="right-top-chongzhi">
                    <div class="chongzhi-left">可用金额：{%if isset($user.amount)%}<span id="my-money">{%$user.amount_text%}</span>元{%else%}<a href="/user/login" class="account-a-link">立即登录</a>{%/if%}<a target="_blank" href="{%$webroot%}/account/cash/recharge" class="chongzhi-link"> [充值]</a></div>
                </div>
                <div class="right-top-btn">
                    <a class="right-top-btn-confirm confirm-submit">确定投资</a>
                    <a class="right-top-btn-confirm confirm-all">全部投资</a>
                </div>
            </form>
            {%else%}
            <div class="right-top right-bg-color">
                <div class="right-top-title">我来投资</div>
                {%if $data.fresh%}
                <div class="right-top-new"></div>
                {%/if%}
                <div class="right-box-top">
                    <div class="right-top2nd-title">已结束</div>
                    <div class="right-top2nd-box">满标时间：{%$data.full_time|date_format:'%Y-%m-%d %H:%M'%}</div>
                    <div class="right-top2nd-box">满标耗时：<span id="full-time"></span></div>
                    <div class="right-top2nd-box">投标人数：{%$data.invest_cnt%}人</div>
                </div>
            </div>
            {%/if%}
            <div class="right-bottom">
                <div class="right-bottom-title">
                    <div class="bottom-title-name">还款计划</div>
                    <div class="bottom-title-number">共<span class="btm-title-number-sp">{%count($data.refunds)%}</span>期</div>
                </div>
                <div class="right-bottom-main">
                    <div class="bottom-main-title">
                        <div class="btm-main-title-box time">还款时间</div>
                        <div class="btm-main-title-box yinghuan">应还本息</div>
                        <div class="btm-main-title-box status">还款状态</div>
                    </div>
                    {%foreach $data.refunds as $key => $item%}
                    {%if $key % 2 == 1%}
                    <div class="btm-main-box btm-bg-color">
                    {%else%}
                    <div class="btm-main-box">
                    {%/if%}
                        <div class="btm-main-title-box time">{%$item.promise_time|date_format:'%Y-%m-%d'%}</div>
                        <div class="btm-main-title-box yinghuan">￥{%$item.interest%}</div>

                        <div class="btm-main-title-box status">
                            {%if $item.status == 1%}
                            未到期
                            {%else if $item.status == 2%}
                            已还款
                            {%else%}
                            已逾期
                            {%/if%}
                        </div>
                    </div>
                    {%/foreach%}

                </div>
            </div>
        </div>
    </div>
</div>

{%/block%}
