{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/project/detail/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['project/detail/index'], function (main) {
        main.init('{%$data.id%}');
    });
</script>
{%/block%}

{%block name="content"%}
{%assign var=mapType value=['实地认证'=>'shidi', '营业执照'=>'yingye', '税务登记证'=>'shuiwu', '银行开户许可证'=>'bank',
'组织机构代码证'=>'zuzhi', '征信报告'=>'zhengxin', '抵押手续'=>'diya', '身份证'=>'shenfen', '户口本'=>'hukou',
'结婚证'=>'jiehun', '房产证'=>'fangchan', '行驶证'=>'xingshi']%}
<div class="details">
    <div class="container">
        <div class="detail-left">
            <div class="detail-left-title">
                <a href="###" class="left-title-link">我来投资</a>
                <span class="left-title-greater">></span>
                <a href="###" class="left-title-link">项目列表</a>
                <span class="left-title-greater">></span>
                <span class="left-title-link">项目详情</span>
            </div>
            <div class="project">
                <div class="project-title">
                    <div class="project-title-name">{%$data.title%}</div>
                    <div class="project-title-number">
                        <span>借款编号：</span>
                        <span>{%$data.id%}</span>
                    </div>
                </div>
                <div class="project-gaishu">
                    <div class="project-gaishu-top">
                        <div class="gaisu-top-rental">
                            <div class="gaishu-top-rental-icon rental">借款总额</div>
                            <div class="gaishu-top-rental-number">
                                <span>￥</span>
                                <span class="rental-number-big">{%$data.amount%}</span>
                            </div>
                        </div>
                        <div class="gaisu-top-rental">
                            <div class="gaishu-top-rental-icon lilv">借款年利率</div>
                            <div class="gaishu-top-rental-number">
                                <span class="rental-number-big">{%$data.interest%}</span>
                                <span>%</span>
                            </div>
                        </div>
                        <div class="gaisu-top-rental">
                            <div class="gaishu-top-rental-icon time">借款期限</div>
                            <div class="gaishu-top-rental-number">
                                <span class="rental-number-big">{%$data.duration_day%}</span>
                                <span>{%$data.duration_type%}</span>
                            </div>
                        </div>

                    </div>
                    <div class="project-gaishu-bottom">
                        <div class="gaishu-bottom-guard">
                            <div class="gaishu-guard-baozhang">
                                <span class="span">保障方式：</span>
                                <div class="baozhang-box">
                                    {%foreach $data.safemode as $key => $item%}
                                    <span class="baozhang-type benxi">{%$item%}</span>
                                    {%/foreach%}

                                </div>

                            </div>
                            <div class="gaishu-guard-baozhang">
                                <span>还款方式：</span>
                                <span class="baozhang-return">{%$data.refund_typename%}</span>
                            </div>
                        </div>
                        <div class="gaishu-bottom-jindu">
                            <div class="jindu-top">
                                <span class="jindu-top-text">筹款进度：</span>
                                <div class="jindu-top-tiao">
                                    <div class="jindu-tio-tiao-within" style="width: {%$data.percent%}%;"></div>
                                </div>
                                    <span class="jindu-top-bai">
                                        <span class="jindu-top-bai-number">{%$data.percent%}</span>%
                                    </span>
                            </div>
                            <div class="jindu-btm">
                                已投标：<span>{%$data.invest_cnt%}人</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="project-time">
                    <span class="project-time-start">开始时间：{%$data.create_time|date_format:'%Y-%m-%d %H:%M:%S'%}</span>
                    <span class="project-time-start">截止日期：{%$data.deadline|date_format:'%Y-%m-%d %H:%M:%S'%}</span>
                </div>
                <div class="project-main project">
                    <div class="project-main-title">
                        <div class="main-title-box showproject current">项目详情</div>
                        <div class="main-title-box showfile">文件资料</div>
                        <div class="main-title-box showrecord">投资记录</div>
                    </div>
                    <div class="main-box-details showproject-main">
                        <div class="details-main-box">
                            <div class="main-box-detail-title">借款企业</div>
                            <div class="main-detail-content">
                                <div class="main-detail-content-left">
                                    <div class="left-box">
                                        <div class="content-left-name">借款学校：</div>
                                        <div class="content-left-text">{%$data.company.school%}</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">区域位置：</div>
                                        <div class="content-left-text">{%$data.company.area%}</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">资产总值：</div>
                                        <div class="content-left-text">{%$data.company.assets%}</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">教职工数量：</div>
                                        <div class="content-left-text">{%$data.company.employers%}名</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">借款用提：</div>
                                        <div class="content-left-text">{%$data.content%}</div>
                                    </div>

                                </div>
                                <div class="main-detail-content-right">
                                    <div class="left-box">
                                        <div class="content-left-name">注册年限：</div>
                                        <div class="content-left-text right-text">{%$data.company.years%}年</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">注册资金：</div>
                                        <div class="content-left-text right-text">{%$data.company.funds%}</div>
                                    </div>
                                    <div class="left-box">
                                        <div class="content-left-name">学生数量：</div>
                                        <div class="content-left-text right-text">{%$data.company.students%}名</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="details-main-box">
                            <div class="main-box-detail-title">信用档案</div>
                            <div class="main-detail-content">
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">成功借款：</div>
                                        <div class="file-left-text">{%$data.counter.success%}笔</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">还清笔数：</div>
                                        <div class="file-left-text">{%$data.counter.finished%}笔</div>
                                    </div>
                                </div>
                                <div class="file-enter">
                                    <div class="file-left-box">
                                        <div class="file-left-name">授信额度：</div>
                                        <div class="file-left-text">{%$data.counter.limit%}元</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">已还金额：</div>
                                        <div class="file-left-text">{%$data.counter.refund%}元</div>
                                    </div>
                                </div>
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">累计借款：</div>
                                        <div class="file-left-text">{%$data.counter.total%}元</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">待还本息：</div>
                                        <div class="file-left-text">{%$data.counter.rest%}元</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="details-main-box">
                            <div class="main-box-detail-title">担保人信息</div>
                            <div class="main-detail-content">
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">姓名：</div>
                                        <div class="file-left-text">{%$data.guarantee.name%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">所处职位：</div>
                                        <div class="file-left-text">{%$data.guarantee.job_title%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">婚否：</div>
                                        <div class="file-left-text">{%if $data.guarantee.marriage == 1%}是{%else%}否{%/if%}</div>
                                    </div>
                                </div>
                                <div class="file-enter">
                                    <div class="file-left-box">
                                        <div class="file-left-name">单位类别：</div>
                                        <div class="file-left-text">{%$data.guarantee.company_type%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">年龄：</div>
                                        <div class="file-left-text">{%$data.guarantee.age%}岁</div>
                                    </div>
                                </div>
                                <div class="file-left">
                                    <div class="file-left-box">
                                        <div class="file-left-name">户口：</div>
                                        <div class="file-left-text">{%$data.guarantee.account%}</div>
                                    </div>
                                    <div class="file-left-box">
                                        <div class="file-left-name">年收入：</div>
                                        <div class="file-left-text">{%$data.guarantee.income%}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="details-main-box">
                            <div class="main-box-detail-title">审核信息</div>
                            <div class="renzheng-box">
                                <div class="renzheng-title">企业认证</div>
                                <div class="renzheng-box-main">
                                    {%foreach $data.audit['1'] as $key => $item%}
                                    <div class="renzheng-pic {%$mapType[$item.name]%}"></div>
                                    {%/foreach%}
                                </div>
                            </div>
                            <div class="renzheng-box">
                                <div class="renzheng-title">个人认证</div>
                                <div class="renzheng-box-main">
                                    {%foreach $data.audit['2'] as $key => $item%}
                                    <div class="renzheng-pic {%$mapType[$item.name]%}"></div>
                                    {%/foreach%}

                                </div>
                            </div>
                        </div>
                        <div class="details-main-box bor-btm">
                            <div class="main-box-detail-title">审核通过</div>
                            <div class="detail-pass">{%$data.audit_info%}</div>
                            <div class="detail-symbol"></div>
                        </div>
                    </div>
                    <div class="main-box-details showfile-main">
                        <div class="details-main-box">
                            <div class="main-box-detail-title">借款企业</div>
                            <div class="main-detail-content">
                                <ul class="detail-item">
                                    {%foreach $data.attach['1'] as $key => $item%}
                                    <li class="detail-item-list">
                                        <img class="detail-item-list-img" src="{%$item.url%}" />
                                        <p class="detail-item-p">{%$item.title%}</p>
                                    </li>
                                    {%/foreach%}
                                </ul>
                            </div>
                        </div>
                        <div class="details-main-box">
                            <div class="main-box-detail-title">合同协议</div>
                            <div class="main-detail-content">
                                <ul class="detail-item">
                                    {%foreach $data.attach['2'] as $key => $item%}
                                    <li class="detail-item-list">
                                        <img class="detail-item-list-img" src="{%$item.url%}" />
                                        <p class="detail-item-p">{%$item.title%}</p>
                                    </li>
                                    {%/foreach%}
                                </ul>
                            </div>
                        </div>
                        <div class="details-main-box item-last">
                            <div class="main-box-detail-title">实地图片</div>
                            <div class="main-detail-content">
                                <ul class="detail-item">
                                    {%foreach $data.attach['3'] as $key => $item%}
                                    <li class="detail-item-list img-city">
                                        <img class="detail-item-list-img" src="{%$item.url%}" />
                                        <p class="detail-item-p">{%$item.title%}</p>
                                    </li>
                                    {%/foreach%}
                                </ul>
                            </div>
                        </div>

                    </div>
                    <div class="main-box-details showrecord-main">
                        <div class="details-main-box">
                            <div class="main-box-detail-title">投资记录</div>
                            <div class="main-detail-content" id="toulist">

                            </div>
                        </div>
                        <div id="page"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="detail-right">
            <div class="right-top">
                <div class="right-top-title">我来投资</div>
                <div class="right-top-allmoney">
                    <div class="right-top-allmoney-money">可投金额：<span id="money-all">{%$data.amount_rest%}</span>元</div>
                    <div class="right-top-allmoney-time">剩余时间：<span>1天1小时22分钟</span></div>
                </div>
                <div class="right-top-ipt">
                    <input type="text" class="right-top-ipt-input" />
                </div>
                <div class="right-top-chongzhi">
                    <div class="chongzhi-left">可用金额：{%if isset($user.amount)%}<span id="my-money">{%$user.amount%}</span>元{%else%}<a href="/user/login/index">立即登录</a>{%/if%}<a href="###" class="chongzhi-link">[充值]</a></div>
                    <div class="chongzhi-right">预期收益<span class="chongzhi-span">0.00</span></div>
                </div>
                <div class="right-top-btn">
                    <a class="right-top-btn-confirm">确定投资</a>
                    <a class="right-top-btn-confirm confirm-all">全部投资</a>
                </div>
            </div>
            <div class="right-bottom">
                <div class="right-bottom-title">
                    <div class="bottom-title-name">还款计划</div>
                    <div class="bottom-title-number">共<span class="btm-title-number-sp">12</span>期</div>
                </div>
                <div class="right-bottom-main">
                    <div class="bottom-main-title">
                        <div class="btm-main-title-box time">还款时间</div>
                        <div class="btm-main-title-box yinghuan">应还本息</div>
                        <div class="btm-main-title-box status">还款状态</div>
                    </div>
                    {%foreach $data.refunds as $key => $item%}
                    <div class="btm-main-box">
                        <div class="btm-main-title-box time">{%$item.promise_time|date_format:'%Y-%m-%d'%}</div>
                        <div class="btm-main-title-box yinghuan">￥{%$item.interest%}</div>

                        <div class="btm-main-title-box status">
                            {%if $item.status == 1%}
                            未到期
                            {%else if $item.status == 2%}
                            已还款
                            {%else%}
                            已逾期
                            {%/if%}
                        </div>
                    </div>
                    {%/foreach%}

                </div>
            </div>
        </div>
    </div>
</div>

{%/block%}