define('common/config', [], function () {
    var rootUrl = '' + window.location.protocol + '//' + window.location.host;
    var URL = {
            ROOT: rootUrl,
            IMG_GET: rootUrl + '/user/imagecode/getimage?type=',
            REGIST_CHECKNAME_CHECK: rootUrl + '/user/registapi/checkname',
            REGIST_CHECKPHONE_CHECK: rootUrl + '/user/registapi/checkphone',
            REGIST_SENDSMSCODE_CHECK: rootUrl + '/user/registapi/sendsmscode',
            REGIST_CHECKSMSCODE_CHECK: rootUrl + '/user/registapi/checksmscode',
            REGIST_INDEX_CHECK: rootUrl + '/user/registapi/index',
            REGIST_CHECKINVITER_CHECK: rootUrl + '/user/registapi/checkinviter',
            LOGIN_INDEX_CHECK: rootUrl + '/user/loginapi/index',
            LOGIN_IMGCODE_ADD: rootUrl + '/user/loginapi/getauthimageurl',
            LOGIN_IMGCODE_CHECK: rootUrl + '/user/loginapi/checkauthimage',
            EDIT_GETSMSCODE_CHECK: rootUrl + '/account/edit/getsmscode',
            EDIT_PHONE_SUBMITE: rootUrl + '/account/editapi/checkphone',
            EDIT_PHONE_SUBMITE2ND: rootUrl + '/account/editapi/bindnewphone',
            EDIT_EMAILCONFIRM: rootUrl + '/account/editapi/newemail',
            EDIT_CHPWD_SUBMITE: rootUrl + '/account/editapi/modifypwd',
            ACCOUNT_AWARD_RECEIVEAWARDS: rootUrl + '/account/award/receiveawards',
            ACCOUNT_CASH_LIST: rootUrl + '/account/cashapi/list',
            LINE_GET: rootUrl + '/account/overview/profitCurve',
            SECURE_DEGREE: rootUrl + '/account/secure/securedegree',
            SECURE_UNBIND_THIRD: rootUrl + '/account/editapi/unbindthird',
            ACCOUNT_CASH_RECHARGE_ADD: rootUrl + '/account/cashapi/recharge',
            ACCOUNT_CASH_WITHDRAW_ADD: rootUrl + '/account/cashapi/withdraw',
            INVEST_LIST: rootUrl + '/invest/api',
            INVEST_DETAIL_START: rootUrl + '/invest/list',
            INVEST_DETAIL_CONFIRM_ADD: rootUrl + '/invest/tender',
            MY_INVEST_GET: rootUrl + '/account/invest/backing',
            MY_INVEST_DETAIL: rootUrl + '/account/invest/repayplan',
            MY_INVEST_ENDED: rootUrl + '/account/invest/ended',
            MY_INVEST_TENDERING: rootUrl + '/account/invest/tendering',
            MY_INVEST_TENDERFAIL: rootUrl + '/account/invest/tenderfail',
            MY_MSG_LIST: rootUrl + '/msg/list',
            MY_MSG_SETREAD_ADD: rootUrl + '/msg/read',
            COMPANY_INFOS_LIST: rootUrl + '/infos/infoapi',
            USER_REGISTAPI_MODIFYPWD: rootUrl + '/user/registapi/modifypwd',
            LOAN_REQUEST: rootUrl + '/loan/request'
        };
    return { URL: URL };
});