{%extends file='common/layout.phtml'%}
{%block name='content'%} 
 <script type="text/javascript" charset="utf-8"    src="/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/ueditor/ueditor.all.min.js"> </script>
    <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
    <script type="text/javascript" charset="utf-8" src="/ueditor/lang/zh-cn/zh-cn.js"></script>

    <style type="text/css">
        div{
            width:100%;
        }
    </style>
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                             Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <form method="post" action="/infos/infoapi/save"  target="id_iframe">
              <br>公告标题: <input name="title" value="">&nbsp;&nbsp;类型(1:公告，2：媒体报道): <input name="type" value="">&nbsp;&nbsp;作者: <input name="author" value=""><br>
              <br>摘要：<input name="abstract" value="" style="width:1082px;"><br><br>
          <div>
           <script id="editor" type="text/plain" style="width:1124px;height:400px;"></script>
          </div>        
            
             <div id="btns">
             <div>
             <button onclick="getContent()" type="submit" name="ctx"  id="ctx11" value="">保存公告</button>&nbsp;&nbsp;
             </form>
             <iframe id="id_iframe" name="id_iframe" style="display:none;"></iframe>
           </div>
         </div>
            </div>

        </div>
    </div>
    <script type="text/javascript">

    //实例化编辑器
    //建议使用工厂方法getEditor创建和引用编辑器实例，如果在某个闭包下引用该编辑器，直接调用UE.getEditor('editor')就能拿到相关的实例 
    var ue = UE.getEditor('editor');
    function getContent() {
        var arr = [];
        arr.push(UE.getEditor('editor').getContent());
        document.getElementById("ctx11").value=arr;
    }
</script>
{%/block%}