{%extends file='common/layout.phtml'%}
{%block name='content'%} 
 <script type="text/javascript" charset="utf-8"    src="/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/ueditor/ueditor.all.min.js"> </script>
    <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
    <script type="text/javascript" charset="utf-8" src="/ueditor/lang/zh-cn/zh-cn.js"></script>

    <style type="text/css">
        div{
            width:100%;
        }
    </style>
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                             Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            {%if 0 ne count($post)%}
             <form method="post" action="/infos/infoapi/save?id={%$post.id%}"  target="id_iframe">
              <br>公告标题: <input name="title" value="{%$post.title%}">&nbsp;&nbsp; 
                   类型：<select name="type" id = "type">
           		<option value = 1>平台公告</option> 
           		<option value = 2>媒体报道</option> 
           		<option value = 3>还款公告</option>   
              </select> 
              <span id = span style="display: none">{%$post.author%}</span>
              &nbsp;&nbsp;作者：<select name="author" id = "origin">         		
                <option value = 管理员>管理员</option> 
           		<option value = souhu>搜狐财经</option> 
           		<option value = hexun>和讯网</option>
           		<option value = zjrx>浙江热线</option>
           		<option value = zhonghua>中华网</option>
           		<option value = sutu>速途网</option>
           		<option value = cn21>21CN生活</option>
           		<option value = fenghuang>凤凰网</option>             
              </select>  <br>
              <br>
              <br>文章摘要：<input name="abstract" value="{%$post.abstract%}" style="width:1082px;"><br><br>
              <div>
              <script id="editor" type="text/plain" style="width:1124px;height:400px;">{%$post.ctx%}</script>
              </div>        
            
             <div id="btns">
             <div>
             <button onclick="getContent()" type="submit" name="ctx"  id="ctx11" value="">保存修改</button>&nbsp;&nbsp;
             </form>
             <iframe id="id_iframe" name="id_iframe" style="display:none;" onload="refresh()"></iframe>
             </div>
             </div>
            {%else%}
            <form method="post" action="/infos/infoapi/save"  target="id_iframe">
              <br>公告标题: <input name="title" value="">&nbsp;&nbsp;类型(1:公告，2：媒体报道): <input name="type" value="">&nbsp;&nbsp;作者: <input name="author" value=""><br>
              <br>摘要：<input name="abstract" value="" style="width:1082px;"><br><br>
          <div>
           <script id="editor" type="text/plain" style="width:1124px;height:400px;"></script>
          </div>         
            
             <div id="btns">
             <div>
             <button onclick="getContent()" type="submit" name="ctx"  id="ctx11" value="">保存公告</button>&nbsp;&nbsp;
             </form>
             <iframe id="id_iframe" name="id_iframe" style="display:none;" onload="refresh()"></iframe>
           </div>
         </div>
         {%/if%}
            </div>

        </div>
    </div>
    <script type="text/javascript">
    //实例化编辑器
    //建议使用工厂方法getEditor创建和引用编辑器实例，如果在某个闭包下引用该编辑器，直接调用UE.getEditor('editor')就能拿到相关的实例 
    var ue = UE.getEditor('editor');
    function getContent() {
        var arr = [];
        arr.push(UE.getEditor('editor').getContent());
        document.getElementById("ctx11").value=arr;
    }

    function refresh(){
    	window.location.href="/admin/info/push";
    }
	
    </script>
    <script type="text/javascript">
    	var type = {%$post.type%};
        var typeSelect = document.getElementById('type');
        typeSelect.value = type;
        var author =  document.getElementById('span').innerHTML;
        var originSelect = document.getElementById('origin');
        originSelect.value = author;
    </script> 
    
{%/block%}