{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                             Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
            公告列表 
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div class="row-fluid">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>资讯类型</th>
                            <th>标题</th>
                            <th>摘要</th>
                            <th>作者</th>
                            <th>创建时间</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%foreach from=$arrInfo key=i item=info%}
                        <tr>
                            <td>{%$info.id%}</td>
                            <td>{%$info.type%}</td>
                            <td>{%$info.title%}</td>
                            <td>{%$info.abstract%}</td>
                            <td>{%$info.author%}</td>
                            <td>{%date("Y-m-d H:i:s",$info.create_time)%}</td>
                            {%if 1 eq $info.status%}
                               <td><form action="/admin/info/edit?id={%$info.id%}" method="POST"><input value="修改" type="submit"></form></td>
                               <td><form action="/infos/infoapi/del?id={%$info.id%}" method="POST"  target="id_iframe"><input value="删除" type="submit" ></form></td>
                            {%/if%}
                            {%if 2 eq $info.status%}                               
                               <td><form action="/infos/infoapi/publish?id={%$info.id%}" method="POST"  target="id_iframe"><input value="发布" type="submit"></form></td>
                               <td><form action="/admin/info/edit?id={%$info.id%}" method="POST"><input value="修改" type="submit"></form></td>
                               <td><form action="/infos/infoapi/del?id={%$info.id%}" method="POST"  target="id_iframe"><input value="删除" type="submit"></form></td>
                            {%/if%}
                        </tr>
                        <iframe id="id_iframe" name="id_iframe" style="display:none;" onload="refresh()"></iframe>
                        {%/foreach%}
                    </tbody>
                </table>
            </div>
            <div id="setpage"  style = "text-align: center;font-size:17px;margin:0 auto;"></div> 
        </div>
    </div>
   
    <script src = "{%$feroot%}s/global/scripts/pageCut.js"></script>
    <script>
    cpage = {%$page%}; 
    totalpage = {%$pageall%}; 
    setpage(cpage,totalpage);
    </script>
    <script>
     	function refresh(){
     		window.location.href="/admin/info/push";
        } 
    </script>
    
    
});
{%/block%}