{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/my/topup/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['my/topup/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="finish">
    <div class="container finish-bg-color">
        {%include file='../../../views/common/nav.phtml' current="3"%}
        <div class="finish-main">
            <div class="finish-main-title">充值

                <a class="return" href="{%$webroot%}/account/overview">返回</a>
                <a class="return" href="/account/cash">返回</a>
            </div>
            <div class="extract topup">
                <form method="post" action="/account/cash/recharge" class="topup-main" id="topup-form">
                    <div class="topup-main-select">
                        <div class="topup-main-select-title">选择充值网银</div>
                        <div class="topup-select-content">
                            <div class="topup-select-con-box current zhaoshang">
                                <input type="radio" name="id" class="topup-select-ipt" checked value="CMB" />
                            </div>
                            <div class="topup-select-con-box gongshang">
                                <input type="radio" name="id" class="topup-select-ipt" value="ICBC"/>
                            </div>
                            <div class="topup-select-con-box youzheng">
                                <input type="radio" name="id" class="topup-select-ipt" value="PSBC"/>
                            </div>
                            <div class="topup-select-con-box minsheng">
                                <input type="radio" name="id" class="topup-select-ipt" value="CMBC"/>
                            </div>
                            <div class="topup-select-con-box jianshe">
                                <input type="radio" name="id" class="topup-select-ipt" value="CCB"/>
                            </div>
                            <div class="topup-select-con-box zhongguo">
                                <input type="radio" name="id" class="topup-select-ipt" value="BOC"/>
                            </div>
                            <div class="topup-select-con-box pufa">
                                <input type="radio" name="id" class="topup-select-ipt" value="SPDB"/>
                            </div>
                            <div class="topup-select-con-box xingye">
                                <input type="radio" name="id" class="topup-select-ipt" value="CIB"/>
                            </div>
                            <div class="topup-select-con-box nongye">
                                <input type="radio" name="id" class="topup-select-ipt" value="ABC"/>
                            </div>
                            <div class="topup-select-con-box jiaotong">
                                <input type="radio" name="id" class="topup-select-ipt" value="BOCOM"/>
                            </div>
                            <div class="topup-select-con-box guangda">
                                <input type="radio" name="id" class="topup-select-ipt" value="CEB"/>
                            </div>
                            <div class="topup-select-con-box shanghai">
                                <input type="radio" name="id" class="topup-select-ipt" value="BOS"/>
                            </div>
                        </div>
                        <div class="topup-select-prompt">
                            <div class="topup-prompt-title">请关注您的充值金额是否超限:</div>
                            <div class="topup-prompt-box current">
                                <table border="0" cellpadding="0" cellspacing="0" class="top-prompt-table">
                                    <tr>
                                        <td class="dan">单笔限额(元)</td>
                                        <td class="xian">每日限额(元)</td>
                                        <td class="manzu">需要满足条件</td>
                                        <td class="beizhu">备注</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">500</td>
                                        <td class="xian">500</td>
                                        <td class="manzu">开通大众版网上银行</td>
                                        <td rowspan="2" class="beizhu">进行借记卡大额支付，可选择招商银行专业版支付及手机支付渠道进行交易；</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">无限额</td>
                                        <td class="xian">无限额</td>
                                        <td class="manzu">开通大众版网上银行</td>
                                    </tr>
                                </table>
                            </div>
                            <div class="topup-prompt-box">
                                <table border="0" cellpadding="0" cellspacing="0" class="top-prompt-table">
                                    <tr>
                                        <td class="dan">单笔限额(元)</td>
                                        <td class="xian">每日限额(元)</td>
                                        <td class="manzu">需要满足条件</td>
                                        <td class="beizhu">备注</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">300</td>
                                        <td class="xian">300</td>
                                        <td class="manzu">柜面注册存量静态支付密码客户</td>
                                        <td rowspan="4" class="beizhu">如您是柜面注册存量静态支付密码客户，当您所做的网上支付交易达到总支付限额后，您将不能继续进行网上支付交易。如您仍需进行网上支付交易，请您到中国工商银行营业网点申领电子银行口令卡或个人客户证书（U盾），当您成为电子银行口令卡客户或证书客户后，您将不再受到支付限额的限制。</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">2000</td>
                                        <td class="xian">5000</td>
                                        <td class="manzu">电子银行口令卡动态支付密码客户--通过手机短信认证</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">500</td>
                                        <td class="xian">1000</td>
                                        <td class="manzu">电子银行口令卡动态支付密码客户--无手机短信认证</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">无限额</td>
                                        <td class="xian">无限额</td>
                                        <td class="manzu">证书客户（U盾客户）</td>
                                    </tr>
                                </table>
                            </div>
                            <div class="topup-prompt-box"></div>
                            <div class="topup-prompt-box">
                                <table border="0" cellpadding="0" cellspacing="0" class="top-prompt-table">
                                    <tr>
                                        <td class="dan">单笔限额(元)</td>
                                        <td class="xian">每日限额(元)</td>
                                        <td class="manzu">需要满足条件</td>
                                        <td class="beizhu">备注</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">300</td>
                                        <td class="xian">300</td>
                                        <td class="manzu">无证书客户
                                            （个人网上银行大众版）</td>
                                        <td rowspan="3" class="beizhu">自2008年11月20日起，大众版支付限额由原日累计300元改为累计支付300元。</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">5000</td>
                                        <td class="xian">5000</td>
                                        <td class="manzu">贵宾版（浏览器证书）</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">20万</td>
                                        <td class="xian">50万</td>
                                        <td class="manzu">贵宾版（U宝）</td>
                                    </tr>

                                </table>
                            </div>
                            <div class="topup-prompt-box">
                                <table border="0" cellpadding="0" cellspacing="0" class="top-prompt-table">
                                    <tr>
                                        <td class="dan">单笔限额(元)</td>
                                        <td class="xian">每日限额(元)</td>
                                        <td class="manzu">需要满足条件</td>
                                        <td class="beizhu">备注</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">1000</td>
                                        <td class="xian">1000</td>
                                        <td class="manzu">动态口令卡（刮刮卡）客户、短信动态口令客户、账户支付(无需开通网银)</td>
                                        <td  class="beizhu">除文件证书客户不开放支付限额外，其他未提及的支付限额均以此限额为准。</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">3000</td>
                                        <td class="xian">3000</td>
                                        <td  class="manzu">文件证书+刮刮卡客户</td>
                                        <td rowspan="2" class="manzu">账号支付是建行客户小额线上支付方式，无需开通建行网上银行，使用账号支付前，需在建行预留您正在使用的手机号。</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">100万</td>
                                        <td class="xian">100万</td>
                                        <td class="manzu">USB Key客户</td>
                                    </tr>

                                </table>
                            </div>
                            <div class="topup-prompt-box">
                                <table border="0" cellpadding="0" cellspacing="0" class="top-prompt-table">
                                    <tr>
                                        <td class="dan">单笔限额(元)</td>
                                        <td class="xian">每日限额(元)</td>
                                        <td class="manzu">需要满足条件</td>
                                        <td class="beizhu">备注</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">1万</td>
                                        <td class="xian">10万</td>
                                        <td class="manzu">动态口令卡</td>
                                        <td  class="beizhu">如需使用中国银行网上支付服务，请先到我行营业网点申请开通新版中国银行网上银行,并申请安全认证工具“中银e令”并妥善保管。</td>
                                    </tr>


                                </table>
                            </div>
                            <div class="topup-prompt-box">
                                <table border="0" cellpadding="0" cellspacing="0" class="top-prompt-table">
                                    <tr>
                                        <td class="dan">单笔限额(元)</td>
                                        <td class="xian">每日限额(元)</td>
                                        <td class="manzu">需要满足条件</td>
                                        <td class="beizhu">备注</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">5万</td>
                                        <td class="xian">5万</td>
                                        <td class="manzu">动态密码版客户
                                            （签约用户）</td>
                                        <td rowspan="2" class="beizhu">如您是动态密码客户或数字证书客户，您需要开通网上支付功能，即开通个人网上银行。</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">无限额</td>
                                        <td class="xian">无限额</td>
                                        <td  class="manzu">证书客户
                                            （浏览器版和usbkey版）</td>
                                    </tr>


                                </table>
                            </div>
                            <div class="topup-prompt-box">
                                <table border="0" cellpadding="0" cellspacing="0" class="top-prompt-table">
                                    <tr>
                                        <td class="dan">单笔限额(元)</td>
                                        <td class="xian">每日限额(元)</td>
                                        <td class="manzu">需要满足条件</td>
                                        <td class="beizhu">备注</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">1000或5000</td>
                                        <td class="xian">1000或5000</td>
                                        <td class="manzu">个人网银自主开通</td>
                                        <td rowspan="2" class="beizhu">1、证书客户或短信保护客户直接在个人网银“网上购物”板块“开通/关闭网上购物支付”里日限额只能选1000或5000元，总额度最大100万元；
                                            2、客户在柜面或者使用证书可自行设置日限额和总额度（最大100万元）；
                                            3、e卡默认开通网上支付功能，日限额5000元，总额度由客户申请e卡时自行设置（最大100万元），但是可以采取以上两种方式修改。</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">无限额</td>
                                        <td class="xian">无限额</td>
                                        <td  class="manzu">柜面或
                                            证书客户个人网银开通</td>
                                    </tr>


                                </table>
                            </div>
                            <div class="topup-prompt-box">
                                <table border="0" cellpadding="0" cellspacing="0" class="top-prompt-table">
                                    <tr>
                                        <td class="dan">单笔限额(元)</td>
                                        <td class="xian">每日限额(元)</td>
                                        <td class="manzu">需要满足条件</td>
                                        <td class="beizhu">备注</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">1000</td>
                                        <td class="xian">3000</td>
                                        <td class="manzu">动态口令卡</td>
                                        <td rowspan="3" class="beizhu">中国农业银行于2007年11月1日推出动态口令卡服务。动态口令卡是一种新型安全认证产品。动态口令卡与IE证书绑定后，使用IE证书对外支付将不受上述限额限制，请至农业银行网点申领。</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">50万</td>
                                        <td class="xian">100万</td>
                                        <td  class="manzu">一代K版（USBN证书用户）</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">100万</td>
                                        <td class="xian">500万</td>
                                        <td  class="manzu">二代K版（USBN证书用户）</td>
                                    </tr>


                                </table>
                            </div>

                            <div class="topup-prompt-box">
                                <table border="0" cellpadding="0" cellspacing="0" class="top-prompt-table">
                                    <tr>
                                        <td class="dan">单笔限额(元)</td>
                                        <td class="xian">每日限额(元)</td>
                                        <td class="manzu">需要满足条件</td>
                                        <td class="beizhu">备注</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">5万</td>
                                        <td class="xian">5万</td>
                                        <td class="manzu">短信密码客户</td>
                                        <td rowspan="2" class="beizhu">1、您需要到交通银行营业网点柜面申请成为个人网上银行手机注册用户或者证书认证用户，并开通网上支付功能。
                                            2、用户在开通网上支付功能后，需到交通银行个人网上银行激活该功能方可使用。
                                            3、客户可根据自身需求登录个人网银进行日累计限额调整。</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">100万</td>
                                        <td class="xian">100万</td>
                                        <td  class="manzu">证书客户</td>
                                    </tr>
                                </table>
                            </div>
                            <div class="topup-prompt-box">
                                <table border="0" cellpadding="0" cellspacing="0" class="top-prompt-table">
                                    <tr>
                                        <td class="dan">单笔限额(元)</td>
                                        <td class="xian">每日限额(元)</td>
                                        <td class="manzu">需要满足条件</td>
                                        <td class="beizhu">备注</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">5000</td>
                                        <td class="xian">5000</td>
                                        <td class="manzu">手机动态密码（令牌）</td>
                                        <td rowspan="2" class="beizhu">1、办理数字证书支付签约需开通个人网上银行专业版，并登录网上银行专业版进行签约。
                                            2、办理银行卡直接支付签约可通过我行网点柜台办理，也可登录个人网上银行专业版进行签约。</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">20万</td>
                                        <td class="xian">50万</td>
                                        <td  class="manzu">网银专业版
                                            阳光网盾</td>
                                    </tr>
                                </table>
                            </div>
                            <div class="topup-prompt-box">
                                <table border="0" cellpadding="0" cellspacing="0" class="top-prompt-table">
                                    <tr>
                                        <td class="dan">单笔限额(元)</td>
                                        <td class="xian">每日限额(元)</td>
                                        <td class="manzu">需要满足条件</td>
                                        <td class="beizhu">备注</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">5000</td>
                                        <td class="xian">5000</td>
                                        <td class="manzu">专业版文件证书</td>
                                        <td rowspan="2" class="beizhu">可至上海银行营业网点申请开通个人网上银行专业版，获得文件证书或usbkey证书，成为专业版客户。</td>
                                    </tr>
                                    <tr>
                                        <td class="dan">5万</td>
                                        <td class="xian">5万</td>
                                        <td  class="manzu">专业版USBKEY证书</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div class="topop-money">
                            <div class="topop-money-box">
                                <div class="topop-money-box-text">输入充值金额</div>
                                <div class="topop-money-box-right">
                                    <input name="value" class="topup-money-box-ipt" type="text" id="box-ipt" />
                                </div>
                                <div class="topup-money-box-error" id="topup-error"></div>
                            </div>
                            <div class="topop-money-box">
                                <div class="topop-money-box-text"></div>
                                <div class="topop-money-box-right right-link">
                                    <a class="topop-money-box-link" id="pay">充值</a>
                                    <a class="topop-money-box-link" href="/account/cash">返回</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="extract-main-bottom">
                        <div class="extract-main-bottom-title">温馨提示：</div>
                        <div class="extract-main-bottom-text">1、投资人充值过程全程免费，兴教贷不收取任何手续费；</div>
                        <div class="extract-main-bottom-text">2、充值/提现必须为银行借记卡，不支持存折、信用卡充值；</div>
                        <div class="extract-main-bottom-text">3、请投资人根据发标计划合理充值；</div>
                        <div class="extract-main-bottom-text">4、因兴教贷不会接触用户资金账户，无法收取用户任何费用，为防止套现，所充资金必须经投标回款后才能提现；</div>
                        <div class="extract-main-bottom-text">5、严禁利用充值功能进行信用卡套现、转账、洗钱等行为，一经发现，兴教贷将封停账号15天以上；</div>
                        <div class="extract-main-bottom-text">6、充值期间，请勿关闭浏览器，待充值成功并返回首页后，所充资金才能入账，如有疑问，请联系客服；</div>
                        <div class="extract-main-bottom-text">7、充值需开通银行卡网上支付功能，如有疑问请咨询开户行客服；</div>
                        <div class="extract-main-bottom-text">8、支付限额请参照支付说明。</div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
{%/block%}