{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/my/message/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['my/message/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="finish">
    <div class="container finish-bg-color">
        {%include file='../../../views/common/nav.phtml' current="6"%}
        <div class="finish-main">
            <div class="finish-main-title">我的消息</div>
            <div class="my-invest-tab">
                <span class="my-invest-tab-item current" data-value="0">全部</span>
                <span class="my-invest-tab-item" data-value="1">已读</span>
                <span class="my-invest-tab-item" data-value="2">未读</span>
            </div>
            <div id="my-msg-list" class="my-invest-list">
                <div class="xjd-loading">&nbsp;</div>
            </div>
            <div id="my-msg-pager" class="my-invest-pager"></div>
        </div>
    </div>
</div>
{%/block%}