{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/my/account/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['my/account/index'], function (main) {
        main.init('{%$openthirdpay%}');
    });
</script>
{%/block%}

{%block name="content"%}
<div class="finish">
    <div class="container finish-bg-color">
        {%include file='../../../views/common/nav.phtml' current="1"%}
        <div class="finish-main">
            <div class="finish-main-title">账户总览</div>
            <div class="all-account-box">
                <div class="all-box-income">
                    <div class="all-box-income-title">
                        <p class="all-income-title-price">￥{%$totalProfit%}</p>
                        <p class="all-income-title-name">累计收益</p>
                    </div>
                    <div class="all-box-income-class">
                        <div class="all-class-money">
                            <p class="all-class-money-price">￥{%$totalInvest%}</p>
                            <p class="all-class-money-price">累计投资</p>
                        </div>
                        <div class="all-class-money">
                            <p class="all-class-money-price">￥{%$reposPrifit%}</p>
                            <p class="all-class-money-price">待收收益</p>
                        </div>
                        <div class="all-class-money">
                            <p class="all-class-money-price">￥{%$reposPrincipal%}</p>
                            <p class="all-class-money-price">待收本金</p>
                        </div>
                    </div>
                </div>
                <div class="all-box-pay">
                    <div class="all-box-pay-top">可用余额<span>￥{%$avlBal%}</span></div>
                    <div class="all-box-pay-top">冻结金额<span>￥{%$frzBal%}</span></div>
                    <div class="all-box-pay-top">资产总计<span><a class="all-pay-help" title="获得帮助"></a>￥{%$acctBal%}</span></div>
                    <a href="{%$rechargeurl%}" class="all-box-pay-link">充值</a>
                </div>
            </div>
            {%if $openthirdpay == 2%}
            <div class="all-account-box-dredge">
                <div class="all-box-dredge-name">尚未开通资金托管账户</div>
                <a href="###" class="all-box-dredge-link">立即开通</a>
            </div>
            {%else%}
            <div id="all-account-line" class="all-account-box-dredge quxian">
                <div class="xjd-loading">&nbsp;</div>
            </div>
            {%/if%}
        </div>
    </div>
</div>

{%/block%}