{%extends file='common/layout.phtml'%}
{%block name='content'%} 
<style type="text/css">
    .panel-body label{
        width:300px;
    }
</style>
<div class="page-content-wrapper">
<div class="page-content">
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">
            基本借款信息
        </h3>
    </div>
    <div class="panel-body">
        暂不提供编辑功能
    </div>

</div>
</div>
</div>
{%/block%}