{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/home/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['home/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
{%assign var="bannerList" value=[0 => "banner-one", 1 => "banner-two", 2 => "banner-three", 3 => "banner-four"]%}

<div class="banner-floation">


    <ul class="banner-item">
        {%foreach $bannerList as $key => $item%}
        <li class="banner-item-list">
            <div class="banner-item-list-link {%$item%}">

                <div class="banner-container">
                    <div class="jiantou-left"></div>
                    <div class="jiantou-right"></div>
                    <div class="fix-box">
                        {%if isset($user)%}
                        <div class="fix-box-title">
                            <p class="fix-title-number logining">欢迎您
                            </p>
                            <p class="fix-title-text">{%$user.username%}</p>
                        </div>
                        <div class="fix-box-main mar-top">
                            <a href="{%$webroot%}/account/overview" class="fix-box-main-regist ">管理我的账户</a>
                            <div class="fix-box-main-box">

                            </div>
                        </div>
                        {%else%}
                        <div class="fix-box-title">
                            <p class="fix-title-number">15.8
                                <span class="fix-title-number-bai">%</span>
                            </p>
                            <p class="fix-title-text">最高年化收利率</p>
                        </div>
                        <div class="fix-box-main">
                            <a href="{%$webroot%}/user/login" class="fix-box-main-regist">快速注册</a>
                            <div class="fix-box-main-box">
                                已有账号？<a href="{%$webroot%}/user/regist" class="fix-box-main-box-login">立即登录</a>
                            </div>
                        </div>
                        {%/if%}

                    </div>
                </div>

            </div>

        </li>
        {%/foreach%}
    </ul>
    <div class="banner-select">
        <a class="banner-select-link current"></a>
        <a class="banner-select-link"></a>
        <a class="banner-select-link"></a>
        <a class="banner-select-link"></a>
    </div>
</div>
<div class="introduce">
    <div class="container">
        <div class="introduce-left">
            <div class="introduce-left-title"><span>兴教贷</span>是什么?</div>
            <div class="introduce-left-text">兴教贷是国内首家专注于教育平台的投融资公司兴教贷是国内首家专注于教育平台的投融资公司兴教贷是国内首家专注于教育平台的投融资公司。<a href="{%$webroot%}/guide">查看更多></a></div>
        </div>
        <div class="introduce-right">
            <a href="{%$webroot%}/security" class="introduce-right-list">
                <div class="introduce-list-logo income"></div>
                <div class="introduce-list-title">低门槛高收入</div>
                <p class="introduce-list-link-text">互联网理财100元起投</p>
                <p class="introduce-list-link-text">超过银行存款利率30倍</p>
            </a>
            <a href="{%$webroot%}/security/profit" class="introduce-right-list">
                <div class="introduce-list-logo baozhang"></div>
                <div class="introduce-list-title">全方位投资保障</div>
                <p class="introduce-list-link-text">360度实地尽调、本金保障</p>
                <p class="introduce-list-link-text">第三方资金托管</p>
            </a>
            <a href="{%$webroot%}/security/focus" class="introduce-right-list last">
                <div class="introduce-list-logo teaching"></div>
                <div class="introduce-list-title">专注教育行业</div>
                <p class="introduce-list-link-text">深挖教育行业特性</p>
                <p class="introduce-list-link-text">最权威教育行业评估体系</p>
            </a>
        </div>
    </div>
</div>
<div class="main">
    <div class="container">
        <div class="newgonggao">
            <span class="newgonggao-title">最新公告</span>

            <a href="{%$webroot%}/infos/post/detail?id={%$data.newpost.id%}" class="newgonggao-txt">
                <span class="symbol">•</span>{%$data.newpost.title%}<span class="newgonggao-time">{%$data.newpost.publish_time|date_format:'%Y-%m-%d'%}</span>
            </a>

            <a class="newgonggao-more" href="{%$webroot%}/infos/post">更多 &gt; &gt;</a>
        </div>
        <div class="investlist">
            <div class="investlist-title">投资列表</div>
            <div class="investlist-box">
                <div class="investlist-box-title border-bottom">
                    <div class="investlist-box-title-name name">借款标题</div>
                    <div class="investlist-box-title-name grade">评估等级</div>
                    <div class="investlist-box-title-name lilv">年利率</div>
                    <div class="investlist-box-title-name price">金额</div>
                    <div class="investlist-box-title-name time">期限</div>
                    <div class="investlist-box-title-name jindu">进度</div>
                    <div class="investlist-box-title-name status">状态</div>
                </div>
                <div class="investlist-box-title">
                    {%foreach $data.list as $key => $item%}
                    <div class="investlist-box-title-name name text-align-name">
                        <span class="name-shi">
                            {%if $item.type_id == 1%}实
                            {%else if $item.type_id == 2%}信
                            {%else%}机
                            {%/if%}
                        </span>
                        <div class="school">
                            <a href="{%$webroot%}/invest/detail?id={%$item.id%}" class="school-link">{%$item.title%}</a>
                        </div>
                        {%if $item.fresh == 1%}
                        <span class="school-new">新手专享</span>
                        {%/if%}
                    </div>
                    <div class="investlist-box-title-name grade">
                        <span class="grade-star level-{%$item.level_name%}"></span>
                    </div>
                    <div class="investlist-box-title-name lilv">
                        <span class="lilv-number">{%$item.interest%}</span>
                        <span class="lilv-bai">%</span>
                    </div>
                    <div class="investlist-box-title-name price">
                        <span class="lilv-number color-blank">{%$item.amount%}</span>
                        <span class="lilv-bai">元</span>
                    </div>
                    <div class="investlist-box-title-name time">
                        <span class="lilv-number color-blank">{%$item.duration_day%}</span>
                        <span class="lilv-bai">{%$item.duration_type%}</span>
                    </div>
                    <div class="investlist-box-title-name jindu">
                        <div class="jindu-box">
                            <div class="jindu-box-inline" style="width: {%$item.percent%}%;"></div>
                        </div>
                        <div class="jindu-number">
                            <span class="lilv-number">{%$item.percent%}</span>
                            <span class="lilv-bai">%</span>
                        </div>
                    </div>
                    <div class="investlist-box-title-name status">
                        {%if $item.status == 2%}
                        <a class="status-biding" href="###">{%$item.status_name%}</a>
                        {%else%}
                        <span class="status-biding current">{%$item.status_name%}</span>
                        {%/if%}
                    </div>
                    {%/foreach%}
                </div>
            </div>
            <a href="{%$webroot%}/invest" class="investlist-more">查看更多标的></a>
        </div>
    </div>
</div>

{%/block%}