{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/home/index.css" /> 
{%/block%}

{%block name="script"%}
<script>
    require(['home/index'], function (main) {
        main.init();
    }); 
</script>

{%/block%}
{%block name="content"%}
<div class="box1">
    <div class="container "> 
    </div>
    <div class="navbar">
        <div class="container "> 
             <i class="navbar-icon tenmin fl"></i>
             <a href="{%$webroot%}/loan" class="navbar-btn fl" style="">融资贷款</a>

             <a href="{%$webroot%}/invest" class="navbar-btn fr">投资理财</a>
             <i class="navbar-icon high fr"></i>
        </div>     
    </div>  
</div>
<div class="box2">
    <div class="container "> 
       <div class="content fl">
           <div class="content-title">
              获取最高 <label class="color-red">300万 </label>企业融资贷款<br/>已有超过100家教育机构获得兴教贷快速贷款
            </div>
            <ul class="content-text">
              <li>
                 <span class="icon icon1 fl"></span> 
                 <span class="icon-text">
                   <label class="color-font-green">低成本</label><br/>
                   融资年化13%起，收费透明
                </span>
              </li>
               <li>
                 <span class="icon icon2 fl"></span> 
                 <span class="icon-text">
                     <label class="color-font-green">极速放款</label><br/>
                     10分钟申请，24小时审核，1周内放款
                 </span>
              </li>
              <li>
                 <span class="icon icon3 fl"></span> 
                 <span class="icon-text">
                    <label class="color-font-green">简单便捷</label><br/>
                    在线申请在线申请在线放款，周期灵活
                </span>
              </li>
            </ul>
       </div>
       <div class="content fr">
            <div class="content-title">
               投资最优质的项目，获取稳健收益<br/>
               已有超过<label class="color-red">10000名</label>用户加入我们 
            </div>
             <ul class="content-text">
              <li>
                 <span class="icon icon4 fl"></span> 
                 <span class="icon-text" style="line-height: 50px;">远超银行定期存款利率</span>
              </li>
               <li>
                 <span class="icon icon5 fl"></span> 
                 <span class="icon-text" style="line-height: 50px;">项目信息公开透明</span>
              </li>
              <li>
                 <span class="icon icon6 fl"></span> 
                 <span class="icon-text" style="line-height: 50px;">安全的投资选择，稳定的还款保证</span>
              </li>
            </ul>
       </div>
    </div> 
</div>
<div class="box3">
   <div class="container">
        <div class="title">
          累计为教育机构融资超过 <label class="color-white">¥10,000,000</label>
        </div>
        <div class="content">
            兴教贷是国内首家专注教育领域投融资的平台，通过兴教贷在线平台，我们撮合投资人与需要融<br/>
            资借款的优质教育机构，我们希望成为教育事业新推力，让更多人投资教育，分享收益。
            <a href="" class="color-red">了解更多&gt;</a>
        </div>
   </div>
</div>
<div class="box4">
   <div class="container">
       
   </div>
</div>
<div class="media box5">
    <div class="container media-box ">
         <ul class="media-box2 fl">
               <li>
                   <a  href="http://www.zhejrx.com/html/2015/02/10/9013.html" class="media-box-img-link" target="_blank" >
                      <span class="media-box-img zjrx"></span>
                   </a>
               </li>
                <li>
                   <a  href="http://tech.hexun.com/2015-02-09/173203577.html" class="media-box-img-link" target="_blank" >
                      <span class="media-box-img hexun"></span>
                   </a>
               </li>
                <li>
                   <a  href="http://www.sootoo.com/content/550811.shtml" class="media-box-img-link" target="_blank" >
                      <span class="media-box-img sutu"></span>
                   </a>
               </li>
                <li>
                   <a  href="http://sn.ifeng.com/gongyi/newswire/detail_2015_02/11/3553569_0.shtml?_from_ralated" class="media-box-img-link" target="_blank" >
                      <span class="media-box-img fenghuang"></span>
                   </a>
               </li>
           </ul> 
    </div>
</div>
{%/block%}
