 
{%extends file="../../../views/common/m/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/app/index.css" />
{%/block%}

{%block name="script"%}
<script>
   
</script>
{%/block%}

{%block name="content"%}
 <div class="invite">
      <div class="invite-box-title flex-center">
          <div  class="logo-img logo-img1"> 
             <img  alt="兴教贷" src="{%$feroot%}/app/img/app_logo11.png" /> 
          </div>
      </div>
     <div class="invite-box-title flex-center">
          <div  class="logo-img logo-img2"> 
             <img  alt="兴教贷" src="{%$feroot%}/app/img/app_logo22.png" />
          </div>
      </div>
      <div class="invite-box-title flex-center">
          <div  class="logo-img logo-img3"> 
             <img  alt="兴教贷" src="{%$feroot%}/app/img/app_logo33.png" />
          </div>
      </div>
      <div class="invite-box-title flex-center">
          <div  class="logo-img logo-img4"> 
             <img  alt="兴教贷" src="{%$feroot%}/app/img/app_logo44.png" />
          </div>
      </div>
      <div class="invite-box-title flex-center">
          <div  class="logo-img logo-img5"> 
             <img  alt="兴教贷" src="{%$feroot%}/app/img/app_logo55.png" />
          </div>
      </div>    

        <div class="invite-box-content app-home-box six">
            <span class="six-title">好友{%$data.invname%}邀请您注册,开启您最好的投资理财</span>
            <a class="regist-btn" href="/m/regist">立即注册</a> 
            <div class="six-bottom">
                 填写邀请手机号：{%$data.phone%}
            </div>
        </div>
   </div>
 

{%/block%}
