{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="/src/setlogin/forgetpwd/index.less" />
{%/block%}

{%block name="script"%}
<script>
    require(['setlogin/forgetpwd/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="login">
    <div class="container">
        <div class="login-left">
            <div class="login-left-box">
                <div class="login-left-title">忘记密码</div>
                <div class="login-username">
                    <input class="login-input" id="login-user" type="text" />
                    <label class="user-lable" for="login-user">用户名</label>
                    <div class="username-error">用户名错误</div>
                </div>
                <div class="login-username">
                    <input class="login-input" id="login-phone" type="text" />
                    <label class="user-lable" for="login-phone">手机号</label>
                    <div class="username-error">请输入正确手机号</div>
                </div>
                <div class="login-username">
                    <input class="login-input testing" id="login-testing" type="password" />
                    <label class="user-lable" for="login-testing">验证码</label>
                    <a href="###" class="login-username-testing">获取验证码</a>
                    <div class="username-error">验证码错误</div>
                </div>
                <div class="login-username">
                    <input class="login-input" id="login-reset" type="text" />
                    <label class="user-lable" for="login-reset">重置密码</label>
                    <div class="username-error">密码错误</div>
                </div>
                <div class="login-username">
                    <input class="login-input" id="login-affirm" type="text" />
                    <label class="user-lable" for="login-affirm">确认密码</label>
                    <div class="username-error">两次密码输入不一致</div>
                </div>
                <a href="###" class="login-fastlogin">确认修改</a>
            </div>
        </div>
        <div class="login-right">
            <a href="###" class="login-right-linkleft left"></a>
            <div class="login-right-box">
                <ul class="login-item">
                    <li class="login-item-list">
                        <div class="introduce-list-logo baozhang"></div>
                        <div class="introduce-list-title">全方位投资保障</div>
                        <div class="introduce-list-title">安全稳健的互联网投机理财</div>
                        <a class="introduce-list-link" href="###">
                            <p class="introduce-list-link-text">360度实地尽调、本金保障</p>
                            <p class="introduce-list-link-text">第三方资金托管</p>
                        </a>
                    </li>
                    <li class="login-item-list">
                        <div class="introduce-list-logo highincome"></div>
                        <div class="introduce-list-title">低门槛高收入</div>
                        <a class="introduce-list-link" href="###">
                            <p class="introduce-list-link-text">互联网理财100元起投</p>
                            <p class="introduce-list-link-text">超过银行存款利率30倍</p>
                        </a>
                    </li>
                    <li class="login-item-list">
                        <div class="introduce-list-logo zhuanzhu"></div>
                        <div class="introduce-list-title">专注教育行业</div>
                        <a class="introduce-list-link" href="###">
                            <p class="introduce-list-link-text">深挖教育行业特性</p>
                            <p class="introduce-list-link-text">最权威教育行业评估体系</p>
                        </a>
                    </li>

                </ul>
            </div>
            <a href="###" class="login-right-linkleft right last"></a>
        </div>
    </div>
</div>
{%/block%}