{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/setting/regist/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['setting/regist/index'], function (regist) {
        regist.init('{%$type%}');
    });  
    require(['common/header'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="regist">
     {%if isset($type)%} 
            <div class="container bound">
                 <p class="bound-text">
                      尊敬的{%$type%}用户:
                    <span class="bound-name">{%$third%}</span>，
                    请完善您的个人信息，以后就可以直接使用{%$type%}登录兴教贷。已有兴教贷账户的用户，请点击
                    <a class="fix-box-register">快速绑定</a>
                </p> 
            </div>
    {%/if%}   
    <div class="container">
        <div  class="regist-box-step fl regist-box-step1"> 
             <div class="regist-box-step-box ">
                  <span class="step1">填写注册信息</span>
                  <span class="step2"> 开通托管账户</span>
                  <span class="step3">注册完成</span> 
             </div>
       </div> 
        <div  class="regist-box fr"> 
            <div class="regist-box-title  fl">注册兴教贷</div>
            <div class="regist-radio fl">
                <div class="radiobox">
                    <input type="radio" id="usertype-3" name="usertype" value="3" checked="" />
                     <label for="house_type-3">我要贷款</label>
                </div>
                <div class="radiobox">
                    <input type="radio" id="usertype-2" name="usertype" value="1" />
                     <label for="house_type-2">我要投资</label>
                 </div>  
            </div>
            <div class="regist-box-content  fl" data-tab="3" >
                 <div class="login-username">
                    <label class="login-username-label">*邮箱</label> 
                    <input autocomplete="off" class="login-input" id="regist-email" type="text" data-text="用户名" />
                    <label class="user-lable" for="regist-email">输入邮箱</label>
                    <div class="username-error" id="regist-email-error"></div>
                    <div id="regist-email-point"></div>
                    <div class="username-point" style="line-height: 18px;">请选择您的常用邮箱</div>
                </div>
                <div class="login-username">
                    <label class="login-username-label">*密码</label> 
                    <input autocomplete="off" class="login-input" id="regist-pwd" type="password" data-text="密码" />
                    <label class="user-lable" for="regist-pwd">输入密码</label>
                    <div class="username-error" id="regist-pwd-error"></div>
                    <div id="regist-pwd-point"></div>
                    <div class="username-point" >密码由6～32位字母、数字及常用符号组成</div>
                </div>
                <div class="login-username">
                    <label class="login-username-label">*确认密码</label> 
                    <input autocomplete="off" class="login-input" id="regist-pwd2" type="password" data-text="确认密码" />
                    <label class="user-lable" for="regist-pwd2">再次输入密码</label>
                    <div class="username-error" id="regist-pwd2-error"></div>
                    <div id="regist-pwd2-point"></div>
                    <div class="username-point">确保两次输入的密码一致</div>
                </div>
                <div class="login-username">
                    <label class="login-username-label">*验证码</label> 
                    <input autocomplete="off" class="login-input testing imgcode" id="regist-imgcode" type="text" data-text="验证码"/> <i></i>
                    <a href="###" class="regist-username-imgcode">
                        <img id="login-img-url" src="{%$url%}" width="162" height="42" />
                    </a> 
                    <div class="username-error" id="regist-imgcode-error"></div>
                </div>
                <a href="###" class="login-fastlogin">快速注册</a>
                <div class="login-tiaoyue">
                    <input autocomplete="off" type="checkbox" checked id="tiaoyue-itp" />
                    <label class="tiaoyue-lable" for="tiaoyue-itp">同意兴教贷<a href="/agreements">用户协议</a></label>
               
                </div>
                <div class="login-thirdlogin">
                <span class="login-tiaoyue-have">已有账户？&nbsp;&nbsp;<a href="{%$webroot%}/user/login">登录</a>&nbsp;&nbsp;</span> 
                </div>
            </div>
            <div class="regist-box-content  fl" data-tab="1" style="display:none;">
                <div class="login-username">
                    <label class="login-username-label">*用户名</label> 
                    <input autocomplete="off" class="login-input" id="regist-user" type="text" data-text="用户名" />
                    <label class="user-lable" for="regist-user">输入用户名</label>
                    <div class="username-error" id="regist-user-error"></div>
                    <div id="regist-user-point"></div>
                    <div class="username-point" style="line-height: 18px;">用户名由6～25位字母、数字、下划线或横线组合，首字符必须为字母</div>
                </div>
                <div class="login-username">
                    <label class="login-username-label">*密码</label> 
                    <input autocomplete="off" class="login-input" id="regist-pwd" type="password" data-text="密码" />
                    <label class="user-lable" for="regist-pwd">输入密码</label>
                    <div class="username-error" id="regist-pwd-error"></div>
                    <div id="regist-pwd-point"></div>
                    <div class="username-point" >密码由6～32位字母、数字及常用符号组成</div>
                </div>
                <div class="login-username">
                    <label class="login-username-label">*确认密码</label> 
                    <input autocomplete="off" class="login-input" id="regist-pwd2" type="password" data-text="确认密码" />
                    <label class="user-lable" for="regist-pwd2">再次输入密码</label>
                    <div class="username-error" id="regist-pwd2-error"></div>
                    <div id="regist-pwd2-point"></div>
                    <div class="username-point">确保两次输入的密码一致</div>
                </div>
                <div class="login-username">
                    <label class="login-username-label">*手机号</label> 
                    <input autocomplete="off" class="login-input" id="regist-phone" type="text" data-text="手机号" />
                    <label class="user-lable" for="regist-phone">输入手机号</label>
                    <div class="username-error" id="regist-phone-error"></div>
                    <div id="regist-phone-point"></div>
                    <div class="username-point">请输入11位手机号</div>
                </div>
                <div class="login-username">
                    <label class="login-username-label">*验证码</label> 
                    <input autocomplete="off" class="login-input testing" id="regist-testing" type="text" data-text="验证码" />
                    <label class="user-lable" for="regist-testing">输入验证码</label>
                    <a href="###" class="login-username-testing disabled"></a>
                    <div class="testTip">点击获取验证码</div>
                    <div class="login-username-testing-box" id="testing-wait">60秒后重新获取验证码</div>
                    <div class="username-error yanzma" id="regist-testing-error">
                    </div>
                </div>
                <div class="login-username">
                    <label class="login-username-label">推荐人</label> 
                    <input autocomplete="off" {%if $result.data.inviter%}readonly value="{%$result.data.inviter%}"{%/if%} class="login-input login-tuijian" id="regist-tuijian" type="text" />
                    <label class="user-lable {%if $result.data.inviter%}hidden{%/if%}" for="regist-tuijian">输入推荐人手机号(选填)</label>
                    <div class="username-error" id="regist-tuijian-error"></div>
                    <div id="regist-tuijian-point"></div>
                    <div class="username-point">请输入推荐人的11位手机号</div>
                </div> 
                <a href="###" class="login-fastlogin">快速注册</a>
                <div class="login-tiaoyue">
                    <input autocomplete="off" type="checkbox" checked id="tiaoyue-itp" />
                    <label class="tiaoyue-lable" for="tiaoyue-itp">同意兴教贷<a href="/agreements">用户协议</a></label>
               
                </div>
                <div class="login-thirdlogin">
                <span class="login-tiaoyue-have">已有账户？&nbsp;&nbsp;<a href="{%$webroot%}/user/login">登录</a>&nbsp;&nbsp;</span>
                    <span class="login-third-tx">您也可以使用第三方账号登录</span>
                    <a href="{%$webroot%}/user/login/auth?type=qq" class="login-third-qq qq"></a>
                    <!-- <a href="{%$webroot%}/user/login/auth?type=weixin" class="login-third-weixin weixin"></a>   -->
                </div>
            </div> 
        </div>
     </div>
</div>   
   

{%/block%}
