{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/my/angelprofit/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['my/angelprofit/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="finish">
    <div class="container finish-bg-color">
        {%include file='../../../views/common/nav.phtml' current="9"%}
        <div class="finish-main">
            <div class="finish-main-title">爱心收益</div>
            <div class="all-account-box">
                <div class="all-box-income">
                      <div class="all-box-income-title">
                          <p class="all-income-title-price">￥11,035,820.66</p>
                          <p class="all-income-title-name">爱心收益</p>
                      </div>
                      <div class="all-box-income-title">
                          <p class="all-income-title-price">3人</p>
                          <p class="all-income-title-name">累计投标人</p>
                      </div>
                  </div>  
                  <div class="all-box-income-class"> 
                      <a target="_blank" href="http://www.xingjiaodai.com.cn:8089/account/cash/withdraw" class="all-box-pay-link cash-link">提现</a>
                   </div> 
            </div>
            <div id="my-angel-list" class="my-invest-list">
               <table border="0" cellspacing="0" cellpadding="0" class="my-invest-table">
                <tbody>
                  <tr>  
                    <th>投资项目</th><th>年利率</th><th>投标人</th><th>投标时间</th><th>期限</th><th>收益分配（您自己</th><th></th>
                  </tr>
                  <tr>
                    <td><a href="/invest/angeldetail/index?id=15" class="invest-name">全走一遍(1)</a></td><td><span class="invest-em">10.60</span>%</td><td>￥1000000.00</td><td>1个月</td><td>2015-02-08 18:50</td><td>2015-02-14</td><td>￥1008131.51</td><td><span class="invest-em">￥8131.51</span></td><td><span class="view-plan-btn" data-id="211">查看还款计划</span></td></tr>
                  </tbody>
                </table>
               <!--  <div class="xjd-loading">&nbsp;</div> -->
               
            </div> 
            <div id="my-angel-pager" class="my-invest-pager"></div>
        </div>
    </div>
</div>
{%/block%}