{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/my/angelprofit/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['my/angelprofit/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="finish">
    <div class="container finish-bg-color">
        {%include file='../../../views/common/nav.phtml' current="9"%}
        <div class="finish-main">
            <div class="finish-main-title">爱心收益</div>
            <div class="all-account-box">
                <div class="all-box-income">
                      <div class="all-box-income-title">
                          <p class="all-income-title-price">￥{%$money%}</p>
                          <p class="all-income-title-name">爱心收益</p>
                      </div>
                      <div class="all-box-income-title">
                          <p class="all-income-title-price">{%$person%}人</p>
                          <p class="all-income-title-name">累计投标人</p>
                      </div>
                  </div>  
                  <div class="all-box-income-class"> 
                      <a target="_blank" href="http://www.xingjiaodai.com.cn:8089/account/cash/withdraw" class="all-box-pay-link cash-link">提现</a>
                   </div> 
            </div>
            <div id="my-angel-list" class="my-invest-list">
              <ul>
                <li class="my-invest-header">
                    <span class="my-invest-title invest-name">投资项目</span>
                    <span class="my-invest-title invest-rate">年利率</span>
                    <span class="my-invest-title invest-money">投标人</span>
                    <span class="my-invest-title invest-time">投标时间</span>
                    <span class="my-invest-title invest-finish">期限</span>
                    <span class="my-invest-title invest-profit">收益分配(您自己)</span>
                    <span class="my-invest-title invest-op"></span>
                </li> 
                <li class="my-invest-item  my-heart-item">
                    <div class="my-invest-content"> 
                        <a href="/invest/detail/index?id=${item.proId}" class="my-invest-project invest-name"> <i class="iconfont icon-heart"></i> 投资项目</a>
                        <span class="my-invest-project invest-rate"><span class="invest-em">12</span>%</span>
                        <span class="my-invest-project invest-money">投标人</span>
                        <span class="my-invest-project invest-time">投标时间</span>
                        <span class="my-invest-project invest-finish">期限</span>
                        <span class="my-invest-project invest-profit">收益分配</span>
                        <span class="my-invest-project view-plan"><span class="view-plan-btn" data-id="${item.invest_id}">查看还款计划</span></span>
                    </div>  
                    <div class="my-invest-detail">
                      <span class="trangle-border"></span>
                      <span class="trangle-content"></span>
                      <table border="0" cellspacing="0" cellpadding="0">
                          <tr>
                              <th>时间</th> 
                              <th>待收收益</th> 
                              <th>已收收益</th>
                              <th>还款状态</th> 
                          </tr> 
                          <tr>
                              <td>${item.timeInfo}</td> 
                              <td>${item.repossProfit}</td> 
                              <td>${item.receProfit}</td>
                              <td>未到期</td> 
                          </tr> 
                          <tr class="my-invest-plan-all">
                              <td>总计</td> 
                              <td>${data.total.repossProfit}</td> 
                              <td>${data.total.receProfit}</td>
                              <td></td> 
                          </tr>
                      </table>
                  </div>
                </li>
               <!--  <div class="xjd-loading">&nbsp;</div> -->
               
            </div> 
            <div id="my-angel-pager" class="my-invest-pager"></div>
        </div>
    </div>
</div>
{%/block%}