{%extends file="../../../views/common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/company/detail/index.css"/>
{%/block%}

{%block name="script"%}
<!--<script>-->
<!--    window._bd_share_config = {-->
<!--        "common": {-->
<!--            "bdSnsKey": {},-->
<!--            "bdText": "{%$data.title%}",-->
<!--            "bdDesc": "{%$data.abstract%}",-->
<!--            "bdUrl": window.location.href,-->
<!--            "bdMini": "2",-->
<!--            "bdMiniList": false,-->
<!--            "bdPic": "",-->
<!--            "bdStyle": "0",-->
<!--            "bdSize": "16"-->
<!--        },-->
<!--        "share": {}-->
<!--    };-->
<!--    with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];-->
<!--</script>-->
<script> 
    require(['company/detail/index'], function(main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="company-nav"> 
	   <div class="company-navbar">  
	      <div class="container"> 
	          {%include file="../../../views/common/menu2.phtml" current="2"%}
	      </div>
	   </div>
</div> 
<div class="container company"> 
    <div class="company-box">
        <div class="company-part-title"> 
            <!--  <a class="company-part-back-icon fl" href="{%$webroot%}/infos/post"></a> -->
             <a class="company-part-back fr" href="{%$webroot%}/infos/post">&lt; 返回列表</a>
        </div>
        <div class="infos-detail">
            <h2 class="infos-detail-title">{%$data.title%}</h2>
            <div class="infos-detail-subtitle"> 
             <span class="infos-detail-time ">{%$data.publish_time|date_format:'%Y-%m-%d'%}</span>
<!--                <span class="infos-share">-->
<!--                    <span class="infos-share-box">分享到：</span>-->
<!--                    <div class="bdsharebuttonbox">-->
<!--                        <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>-->
<!--                        <a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>-->
<!--                        <a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>-->
<!--                        <a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a>-->
<!--                        <a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a>-->
<!--                        <a href="#" class="bds_more" data-cmd="more"></a>-->
<!--                    </div>-->
<!---->
<!--                </span>-->
            </div>
            <p class="infos-detail-ctx">
                {%$data.ctx%}
            </p>
        </div>
    </div>
</div>

{%/block%}
