{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/guide/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['guide/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="newhand">
    <div class="newhand-one">
        <div class="container">
            <div class="newhand-one-symbol number-one"></div>
            <div class="newhand-one-title">什么是兴教贷?</div>
            <div class="newhand-one-text">兴教贷是国内首家专注教育领域投融资的平台，通过兴教贷平台，您可以将手中的富余资金出借给由我们认证的教育机构或个人，并获得利息回报。我们希望用金融推动教育事业发展，让更多人投资教育，分享收益。</div>
            <div class="newhand-one-main"></div>
        </div>
    </div>
    <div class="newhand-one two">
        <div class="container">
            <div class="newhand-one-symbol number-two"></div>
            <div class="newhand-one-title">为什么选择兴教贷?</div>
            <div class="newhand-two-main">
                <div class="newhand-two-main-box">
                    <div class="two-box-pic quan"></div>
                    <div class="two-box-title">全方位投资保障</div>
                    <div class="two-box-text">360度实地尽调、本金保障</div>
                    <div class="two-box-text">第三方资金托管</div>
                    <a class="two-box-link" href="{%$webroot%}/security">了解更多&gt;&gt;</a>
                </div>
                <div class="newhand-two-main-box">
                    <div class="two-box-pic zhuan"></div>
                    <div class="two-box-title">专注教育行业</div>
                    <div class="two-box-text">深挖教育行业特性</div>
                    <div class="two-box-text">最权威教育行业风险评估体系</div>
                    <a class="two-box-link" href="{%$webroot%}/security/focus">了解更多&gt;&gt;</a>
                </div>
                <div class="newhand-two-main-box">
                    <div class="two-box-pic di"></div>
                    <div class="two-box-title">低门槛高收益</div>
                    <div class="two-box-text">互联网理财100元起投</div>
                    <div class="two-box-text">超过银行存款利率30倍</div>
                    <a class="two-box-link" href="{%$webroot%}/security/profit">了解更多&gt;&gt;</a>
                </div>
            </div>

        </div>
    </div>
    <div class="newhand-one">
        <div class="container">
            <div class="newhand-one-symbol number-three"></div>
            <div class="newhand-one-title">如何投资?</div>
            <div class="newhand-three-main">
                <div class="three-main-step-box">
                    <div class="three-step-box-number step-one"></div>
                </div>
                <div class="three-main-step-content">
                    <div class="three-main-step-left"></div>
                    <div class="three-step-con-box">
                        <ul class="three-step-item">
                            <li class="three-step-item-list step-pic-one"></li>
                            <li class="three-step-item-list step-pic-two"></li>
                            <li class="three-step-item-list step-pic-three"></li>
                            <li class="three-step-item-list step-pic-four"></li>
                        </ul>
                    </div>
                    <div class="three-main-step-right"></div>
                </div>
            </div>
        </div>
    </div>
</div>

{%/block%}