<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8"/>
<title>兴教贷</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="{%$feroot%}s/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE STYLES -->
<link href="{%$feroot%}s/admin/pages/css/tasks.css" rel="stylesheet" type="text/css"/>
<!-- END PAGE STYLES -->
<!-- BEGIN THEME STYLES -->
<!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
<link href="{%$feroot%}s/global/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/css/plugins.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/admin/layout/css/layout.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/admin/layout/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
<link href="{%$feroot%}s/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico"/>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed page-quick-sidebar-over-content page-sidebar-closed-hide-logo"> 
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
	<!-- BEGIN HEADER INNER -->
	<div class="page-header-inner">
		<!-- BEGIN LOGO -->
		<div class="page-logo">
			<a href="/admin">
			<img src="{%$feroot%}s/admin/layout/img/logo.png" alt="logo" class="logo-default"/>
			</a>
			<div class="menu-toggler sidebar-toggler">
				<!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
			</div>
		</div>
		<!-- END LOGO -->
		<!-- BEGIN RESPONSIVE MENU TOGGLER -->
		<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
		</a>
		<!-- END RESPONSIVE MENU TOGGLER -->
		<!-- BEGIN TOP NAVIGATION MENU -->
		<div class="top-menu">
			<ul class="nav navbar-nav pull-right">
			<li class="dropdown dropdown-quick-sidebar-toggler">
					<a href="{%$root%}/index" class="dropdown-toggle">
					<i class="icon-logout"></i>
					</a>
				</li>
			<li class="dropdown dropdown-quick-sidebar-toggler">
					<a href="{%$root%}/admin/logout" class="dropdown-toggle">
					<i class="icon-key"></i>
					</a>
				</li>
				<!-- BEGIN NOTIFICATION DROPDOWN -->
				<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
<!-- 				<li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar"> -->
<!-- 					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> -->
<!-- 					<i class="icon-bell"></i> -->
<!-- 					<span class="badge badge-default"> -->
<!-- 					7 </span> -->
<!-- 					</a> -->
<!-- 					<ul class="dropdown-menu"> -->
<!-- 						<li class="external"> -->
<!-- 							<h3><span class="bold">12 pending</span> notifications</h3> -->
<!-- 							<a href="extra_profile.html">view all</a> -->
<!-- 						</li> -->
<!-- 						<li> -->
<!--							<ul class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">-->
<!-- 								<li> -->
<!-- 									<a href="javascript:;"> -->
<!-- 									<span class="time">just now</span> -->
<!-- 									<span class="details"> -->
<!-- 									<span class="label label-sm label-icon label-success"> -->
<!-- 									<i class="fa fa-plus"></i> -->
<!-- 									</span> -->
<!-- 									New user registered. </span> -->
<!-- 									</a> -->
<!-- 								</li> -->
<!-- 							</ul> -->
<!-- 						</li> -->
<!-- 					</ul> -->
<!-- 				</li> -->
				<!-- END NOTIFICATION DROPDOWN -->
				<!-- BEGIN USER LOGIN DROPDOWN -->
				<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
<!-- 				<li class="dropdown dropdown-user"> -->
<!-- 					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> -->
<!-- 					<img alt="" class="img-circle" src="{%$feroot%}s/admin/layout/img/avatar3_small.jpg"/> -->
<!-- 					<span class="username username-hide-on-mobile"> -->
<!-- 					Nick </span> -->
<!-- 					<i class="fa fa-angle-down"></i> -->
<!-- 					</a> -->
<!-- 					<ul class="dropdown-menu dropdown-menu-default"> -->
<!-- 						<li> -->
<!-- 							<a href="/logout"> -->
<!-- 							<i class="icon-key"></i> Log Out </a> -->
<!-- 						</li> -->
<!-- 					</ul> -->
<!-- 				</li> -->
				<!-- END USER LOGIN DROPDOWN -->
				<!-- BEGIN QUICK SIDEBAR TOGGLER -->
				<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
<!-- 				<li class="dropdown dropdown-quick-sidebar-toggler"> -->
<!-- 					<a href="javascript:;" class="dropdown-toggle"> -->
<!-- 					<i class="icon-logout"></i> -->
<!-- 					</a> -->
<!-- 				</li> -->
				<!-- END QUICK SIDEBAR TOGGLER -->
		</ul> 
		</div>
		<!-- END TOP NAVIGATION MENU -->
	</div>
	<!-- END HEADER INNER -->
</div>
<!-- END HEADER -->
<div class="clearfix">
</div>
<!-- BEGIN CONTAINER -->
<div class="page-container">
    {%include file='common/sidebar.phtml'%}
	<!-- BEGIN CONTENT -->
	{%block name='content'%}{%/block%}
	<!-- END QUICK SIDEBAR -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="page-footer">
	<div style = "text-align: center;margin:0 auto;" class="page-footer-inner">
		    北京百年兴教网络技术有限公司<br> © 2014-2015 
	</div>
	<div class="scroll-to-top">
		<i class="icon-arrow-up"></i>
	</div>
</div>
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="{%$feroot%}s/global/plugins/respond.min.js"></script>
<script src="{%$feroot%}s/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="{%$feroot%}s/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="{%$feroot%}s/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS
<script src="{%$feroot%}s/global/plugins/jqvmap/jqvmap/jquery.vmap.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/flot/jquery.flot.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/flot/jquery.flot.resize.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/flot/jquery.flot.categories.min.js" type="text/javascript"></script> -->
<script src="{%$feroot%}s/global/plugins/jquery.pulsate.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-daterangepicker/moment.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
<!-- IMPORTANT! fullcalendar depends on jquery-ui-1.10.3.custom.min.js for drag & drop support -->
<script src="{%$feroot%}s/global/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{%$feroot%}s/global/scripts/metronic.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/layout/scripts/demo.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/pages/scripts/index.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/pages/scripts/tasks.js" type="text/javascript"></script>

<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {    
   Metronic.init(); // init metronic core componets
   Layout.init(); // init layout
   QuickSidebar.init(); // init quick sidebar
   Demo.init(); // init demo features 
   Index.init();   
   Index.initDashboardDaterange();
   Index.initJQVMAP(); // init index page's custom scripts
   Index.initCalendar(); // init index page's custom scripts
   Index.initCharts(); // init index page's custom scripts
   Index.initChat();
   Index.initMiniCharts();
   Tasks.initDashboardWidget();
});
</script>
{%block name='script'%}{%/block%}
<!-- END JAVASCRIPTS -->
</body>

<!-- END BODY -->
</html>
