{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/company/team/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['company/common/common'], function(main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="container company">
    {%include file="common/menu.phtml" current="3"%}
    <div class="company-box">
        <div class="company-part-title">
            <h2 class="company-part-titlectx">合作伙伴</h2>
        </div>
        <ul class="team-list">
            <li class="team-item">
                <img src="{%$feroot%}/company/us/img/huifu.png" class="huifu" />
                <div class="team-item-intro">
                    <div class="team-name">
                        汇付天下
                    </div>
                    <p class="team-intro">
                        汇付天下成立于2006年7月，投资额近10亿元人民币。公司致力于为中国小微企业、金融机构、行业客户和投资者提供金融支付、账户托管、理财平台等综合支付服务。目前，汇付天下建立了国内首个第三方P2P托管账户体系，国内超200家P2P网贷公司接入汇付天下P2P托管账户。
                    </p>
                </div>
            </li>
            <li class="team-item">
                <img src="{%$feroot%}/company/us/img/xingye.png" />
                <div class="team-item-intro">
                    <div class="team-name">
                        兴业银行
                    </div>
                    <p class="team-intro">
                        兴业银行成立于1988年8月，是经国务院、中国人民银行批准成立的首批股份制商业银行之一，注册资本190.52亿元。目前，兴业银行已在全国各主要城市设立了98家分行、826家分支机构；拥有全资子公司——兴业金融租赁有限责任公司和控股子公司——兴业国际信托有限公司、兴业基金管理有限公司。
                    </p>
                </div>
            </li>

        </ul>
    </div>
</div>

{%/block%}