{%extends file="common/page.phtml"%}

{%block name="link"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/security/index/index.css" />
{%/block%}

{%block name="script"%}
<script>
    require(['security/index/index'], function (main) {
        main.init();
    });
</script>
{%/block%}

{%block name="content"%}
<div class="insurance">
    <div class="insurance-type">
    
        <a class="insurance-type-box low" href="{%$webroot%}/security/profit">
            低门槛高收益
            <div class="insurance-banner-triangle low-color"></div>
        </a>
        <a class="insurance-type-box allposition current" href="">
            全方位投资保障
             <!--  <div class="insurance-banner-triangle allposition-color"></div>   -->
        </a>
        <a class="insurance-type-box teach" href="{%$webroot%}/security/focus">
            专注教育行业
            <div class="insurance-banner-triangle teach-color"></div>
        </a>
    </div>
    <div class="insurance-banner allposition">

    </div>
    <div class="container">
        <div class="allposition-main">
            <div class="allposition-main-left">
                <div class="allposition-main-left-pic"></div>
            </div>
            <div class="allposition-main-right">
                <div class="allposition-main-right-box">
                    <div class="main-box-icon shouyi"></div>
                    <div class="main-box-con">
                        <div class="main-right-box-title">收费权质押
                        </div>
                        <div class="main-right-box-text">借款学校将其学费收益权全部质押给投资者，以全面保证投资者的投资本息安全。经平台融资的每所学校，均与平台签订了一揽子《收益权质押协议》，收益权质押后，借款学校每年度的学费收入将优先用于偿付其在平台的借款本息。</div>
                    </div>
                </div>
                <div class="allposition-main-right-box">
                    <div class="main-box-icon liyi"></div>
                    <div class="main-box-con">
                        <div class="main-right-box-title">利益相关方担保</div>
                        <div class="main-right-box-text">借款学校的股东方为借款提供个人无限连带责任担保。平台通过个人征信报告、房屋所有权登记、车辆所有权登记等信息对担保人个人背景、综合信用情况、还款实力进行详细调查，确保其担保能力真实有效。</div>
                    </div>
                </div>
                <div class="allposition-main-right-box">
                    <div class="main-box-icon benjin"></div>
                    <div class="main-box-con">
                        <div class="main-right-box-title">本金保障计划</div>
                        <div class="main-right-box-text">平台建立了完善的投资者本金保障计划。当投资者的投资出现逾期，平台将优先通过风险备用金账户向投资者垫付本息，从而最大限度的保障投资者的投资安全。</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="allposition-main bg-color">
        <div class="container">
            <div class="allposition-main-right">
                <div class="allposition-main-right-box">
                    <div class="main-box-icon fangwei"></div>
                    <div class="main-box-con">
                        <div class="main-right-box-title">全方位尽职调查和实地认证</div>
                        <div class="main-right-box-text">我们建立了专业的尽职调查团队，团队成员主要来自于国内著名投资银行、商业银行和教育机构。我们对平台的每一个项目，均由团队成员进行现场调查走访，以确保每个项目的真实性和可靠性。我们对学校的尽职调查报告涉及其征信数据、资产情况、财务情况、教学情况、师生员工情况等各项指标，全面反映学校的综合运营能力，以确保项目融资需求真实合理，从而为风险控制提供重要依据和支持。</div>
                    </div>
                </div>
                <div class="allposition-main-right-box">
                    <div class="main-box-icon jianli"></div>
                    <div class="main-box-con">
                        <div class="main-right-box-title">建立定期跟踪机制</div>
                        <div class="main-right-box-text">我们对平台的每一个借款学校，均采取实时跟踪、定期回访的持续跟踪评价策略。我们根据学校的运作情况，定期要求学校及时反馈运营中的各项信息，并采取抽样调查的方式进行实地重复走访、考察，以进一步保证在借款存续期间内的学校运营情况稳定，降低投资者的投资风险。</div>
                    </div>
                </div>
            </div>
            <div class="allposition-main-left">
                <div class="allposition-main-left-pic second"></div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="allposition-main">
            <div class="allposition-main-left">
                <div class="allposition-main-left-pic third"></div>
            </div>
            <div class="allposition-main-right">
                <div class="allposition-main-right-box">
                    <div class="main-box-icon zijin"></div>
                    <div class="main-box-con">
                        <div class="main-right-box-title">资金第三方托管</div>
                        <div class="main-right-box-text">投资者投入的每一分钱都不会经过平台，而是通过第三方支付机构进行托管，平台无法通过任何方式支配投资者的资金。同时，投资者投出的每一笔资金都有清晰明确的路径并能被实时监控。目前，我们已经专门委托汇付天下为我们的投资者全面提供线上支付和提现服务。汇付天下在互联网金融领域的支付领域排名第一，是首批获得央行颁发的《支付业务许可证》的企业，持有中国证监会批准的《网上基金销售支付结算许可》，是中国支付清算协会常务理事单位。</div>
                    </div>
                </div>
                <div class="allposition-main-right-box">
                    <div class="main-box-icon zhanghu"></div>
                    <div class="main-box-con">
                        <div class="main-right-box-title">账户信息安全</div>
                        <div class="main-right-box-text">平台运用先进的安全技术保护用户的全部个人信息及交易记录。平台严格遵守国家相关法律法规，严格保护用户隐私信息，平台所有用户个人隐私信息均通过加密处理，包括公司员工在内的任何人都无法超越自身权限获取用户信息。未经投资者的同意，平台不会以任何形式向任何第三方公司、组织或个人泄漏您的个人账户信息。SSH安全机制保证您的账号登陆安全。</div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{%/block%}
